<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
<script type="text/javascript" src="../jwplayer.js"></script>
<script type="text/javascript" src="../jwplayer.html5.js"></script>
<script type="text/javascript">jwplayer.key = "CxCVpLlE64weMpm8vjiNVAMrRicsKBkO+7Vfcg==";</script>
<style>
#myElement_wrapper {
	margin: 0 auto !important;
	width: 100% !important;
	min-height: {VIDEO_HEIGHT
}
px
 
!
important
;

        
}
</style>
</head>
<body>
	<center>
		<div id="myElement">Loading the player...</div>
	</center>
	<script type="text/javascript">
            jwplayer("myElement").setup({
                {CONTENT_FLASH}
            });
        </script>
</body>
</html>