branch-defaults:
  dev:
    environment: memreasdev-frontend
global:
  application_name: memreasdev
  default_ec2_keyname: memreas-dev
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running PHP 5.5
  default_region: us-east-1
  profile: eb-cli
  sc: git
