/**
 * inner includes 
 */
require("/memreas/js-location-slider/jquery.elastislide.js");
require("/memreas/js-location-slider/jquerypp.custom.js");
require("/memreas/js/ajax.js");
require("/memreas/js/bgstretcher.js");
require("/memreas/js/bootstrap-datepicker.js"); 
require("/memreas/js/bootstrap-typeahead.js");
require("/memreas/js/bootstrap.min.js");
require("/memreas/js/chosen.jquery.js");
require("/memreas/js/constants.js");
require("/memreas/js/friend_memreas.js");
require("/memreas/js/gallery_location.js");
require("/memreas/js/gallery.js");
require("/memreas/js/global.js");
require("/memreas/js/jquery.akordeon.js");
require("/memreas/js/jquery.cookie.js");
require("/memreas/js/jquery.elastislide.js");
require("/memreas/js/jquery.mCustomScrollbar.concat.min.js");
require("/memreas/js/jquery.mouseSwipe.js");
require("/memreas/js/jquery.oauthpopup.js");
require("/memreas/js/jquery.simplePagination.js");
require("/memreas/js/jquery.swipebox.min.js");
require("/memreas/js/jquerypp.custom.js");
require("/memreas/js/memreas_details.js");
require("/memreas/js/memreas_tab/buymedia.js");
require("/memreas/js/memreas.js");
require("/memreas/js/modernizr.custom.17475.js");
require("/memreas/js/more_page.js");
require("/memreas/js/more_tabs/account.js");
require("/memreas/js/more_tabs/buycredit.js");
require("/memreas/js/more_tabs/feedback.js");
require("/memreas/js/more_tabs/friends.js");
require("/memreas/js/more_tabs/help.js");
require("/memreas/js/more_tabs/sellmedia.js");
require("/memreas/js/more_tabs/subscription.js");
require("/memreas/js/notification.js");
require("/memreas/js/popup.js");
require("/memreas/js/queue.js");
require("/memreas/js/record/audio_record.js");
require("/memreas/js/record/AudioContextMonkeyPatch.js");
require("/memreas/js/record/recorder.js");
require("/memreas/js/search.js");
require("/memreas/js/share.js");
require("/memreas/js/slides.min.jquery.js");
require("/memreas/js/strings.js");
require("/memreas/js/underscore-min.js");
require("https://maps.google.com/maps/api/js?libraries=places&region=uk&language=en&sensor=true");
