<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php if ($this->enableAdvertising) : ?>
	<div class="clear:both; display:block;"></div>
	<div id="bottomad" class="ad bottom-ads-secion">Loading...</div>
	<div class="clear:both; display:block;"></div>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- memreas_auto_size_ad -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2182144607113281"
     data-ad-slot="4950165058"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<?php endif; ?>