<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<!--Bootstrap Css-->
<link href="/memreas/css/responsive.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/datepicker.css" rel="stylesheet" type="text/css">
<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/transtyle.css" rel="stylesheet" type="text/css">
<!-- <link href="/memreas/css/davidstyle.css" rel="stylesheet" type="text/css">  -->
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link href="/memreas/css/fotorama.4.6.4.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/memreas/css/elastislide.css" />
<link rel="stylesheet" href="/memreas/css/swipebox.css">
<link href="/memreas/css/jquery.akordeon.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="/memreas/css/jNotify.jquery.css">
<link rel="stylesheet" href="/memreas/css/handheld.css">
<link rel="stylesheet" href="/memreas/css/chosen.css">
<link rel="stylesheet" href="/memreas/css/simplePagination.css">


<link rel="stylesheet" href="/memreas/cssblue/blueimp-gallery.css">
<link rel="stylesheet" href="/memreas/cssblue/blueimp-gallery-indicator.css">
<link rel="stylesheet" href="/memreas/cssblue/blueimp-gallery-video.css">
<?php
 if ($this->enableAdvertising){
   ?> 
<link href="/memreas/css/mobile-style-with-ads.css" rel="stylesheet" type="text/css">
<?php 
 } 
   
 else{
  ?>
 <link href="/memreas/css/mobile-style-without-ads.css" rel="stylesheet" type="text/css">     
  <?php  
 }

?>
