<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/transtyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/davidstyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link href="/memreas/css/fotorama.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/memreas/css/elastislide.css" />
<link rel="stylesheet" href="/memreas/css/swipebox.css">
<link href="/memreas/css/jquery.akordeon.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="/memreas/css/jNotify.jquery.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/datepicker.css" rel="stylesheet" type="text/memreas/css">