<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
use Application\Model\MemreasConstants;

?>
<div class="modal-backdrop fade out" style="display:none;"></div>
<!-- Start : Footer -->
        <footer class="rel">
            <p><?php echo MemreasConstants::COPYRIGHT?></p>
        </footer>
<!-- End : Footer -->
