<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php 
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;
use Application\Model\MemreasConstants;

$username = $_SESSION['username'];
$domain = MemreasConstants::CLOUDFRONT_DOWNLOAD_HOST;
?>
<div class="modal-backdrop fade out" style="display:none;"></div>
<!-- Start : Footer -->
        <footer class="rel">
            <p><?php echo MemreasConstants::COPYRIGHT?></p>
        </footer>
<!-- End : Footer -->
