<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<script type="text/javascript">
/////////////////////
//Login
/////////////////////
jQuery.login - function () {
	var obj = new Object();
	obj.username = $(#username).val();
	obj.password = $(#password).val();
	var json_Login =  JSON.stringify(obj);
	var data = ""

	data = '{"action": "login", ' +
	 '"type":"jsonp", ' +
	 '"json": ' + json_Login  +
	 '}';
		 
	
}

jQuery.execAjax = function (url, data, form_name) {
    console.log("Inside gallery.phtml ---> jQuery.execAjax url-->" + url);
	$.ajax( {
		  type:'post',
		  url: url,
		  dataType: 'jsonp',
		  data: 'json=' + data,
		  success: function(json){
		  	var req_resp = $(form_name).val() + "\n\n" + JSON.stringify(json, null, '\t');
		  	$(form_name).val(req_resp);
		  },
		  error: function (jqXHR, textStatus, errorThrown) {
		  	//alert("Inside error jqXHR...");
	    	alert(jqXHR.responseText);
	    	alert(jqXHR.status);
	 		//alert(textStatus);
	    	//alert(errorThrown);
		  }
		});
		return false;
}

jQuery.addSeller = function () {

	var obj = new Object();
	obj.user_name = $("#add_seller_user_name").val();
	obj.stripe_email_address = $("#add_seller__email_address").val();
	obj.first_name = $("#add_seller_first_name").val();
	obj.last_name = $("#add_seller_last_name").val();
	obj.address_line_1 = $("#add_seller_address_line_1").val();
	obj.address_line_2 = $("#add_seller_address_line_2").val();
	obj.city = $("#add_seller_city").val();
	obj.state = $("#add_seller_state").val();
	obj.zip_code = $("#add_seller_zip_code").val();
 var json_AddSeller = JSON.stringify(obj);
 var data = "";
 

 data = '{"action": "AddSeller", ' +
 '"type":"jsonp", ' +
 '"json": ' + json_AddSeller  +
 '}';

	//var results += json_AddSeller;
	$("#add_seller_form_results").val(json_AddSeller, null, '\t');

	$.ajax( {
	  type:'post',
	  url: stripeAddSeller_url,
	  dataType: 'jsonp',
	  data: 'json=' + data,
	  success: function(json){
	  	var req_resp = $("#add_seller_form_results").val() + "\n\n" + JSON.stringify(json, null, '\t');
	  	$("#add_seller_form_results").val(req_resp);
	  },
	  error: function (jqXHR, textStatus, errorThrown) {
	  	//alert("Inside error jqXHR...");
    	alert(jqXHR.responseText);
    	alert(jqXHR.status);
 	//alert(textStatus);
    	//alert(errorThrown);
	  }
	});
	return false;
}

</script>

<div class="span11 tabcontent-detail" id="gallery">
	<!--<div class="<?php echo ($this->enableAdvertising) ? 'span9' : 'span11';?> left-gallery">-->
	<div class="span11 left-gallery">
		<ul id="tabs" class="medium_tabs">
			<li><a href="#" title="tab1">view</a></li>
			<li><a href="#" title="tab2" class="delete-tab">delete</a></li>
			<li><a href="#" title="tab3" class="location-tab">location</a></li>
		</ul>
		<div id="tab-content" class="clearfix">
			<div id="tab1" class="hideCls hidden-onload">
				<!-- <div class="fotoama" data-width="100%" data-ratio="800/600">  -->
				<!--				<div class="preload-files">
					<ul class="pics"></ul>
				</div>-->
				<!--				<div id="mGallery" class="fotorama user-resources"	data-swipe="true" data-max-width="100%" data-width="100%" data-height="80%" data-allow-full-screen="true" data-fit="cover" data-click="true" data-nav="thumbs">
					 user resources to be loaded here... 
				</div>-->

				<!-- The Gallery as lightbox dialog, should be a child element of the document body -->
				<!-- 
				<div id="blueimp-gallery"
					class="blueimp-gallery blueimp-gallery-controls blueimp-gallery-carousel "
					data-start-slideshow="false">
					<div class="slides"></div>
					<h3 class="title"></h3>
					<a class="prev">‹</a> <a class="next">›</a> <a class="close">×</a>
					<a class="play-pause"></a>
				</div> -->

				<div id="links" class="links"></div>
				<div id="blueimp-gallery" class="blueimp-gallery">
					<div class="slides"></div>
					<h3 class="title"></h3>
					<a class="prev">‹</a>
					<a class="next">›</a> 
					<a class="close">×</a>
					<a class="play-pause"></a>
					<ol class="indicator"></ol>
				</div>



			</div>
			<div id="tab2" class="hideCls hidden-onload">
				<div class="edit-area">
					<ul id="content_1" class="pics edit-area-scroll scroll-area">
					</ul>
					<div style="clear: both;"></div>
					<a class="black_btn_skin" href="javascript:;"
						onclick="deleteFiles(false);">Delete</a>&nbsp;<a
						class="black_btn_skin" href="javascript:;" id="btn-upload"
						onclick="$('a[title=queue]').click();">Upload</a>
				</div>
			</div>
			<div id="tab3" class="hideCls hidden-onload">
				<div class="gallery-address-box input-wrap">
					<input id="txt_gallery_address" name="input" type="text" /><a
						id="btn_gallerymap_ok" class="black_btn_skin" href="javascript:;">Update</a>
				</div>
				<div id="gallery-location">
					<!-- <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Canada,+KY,+USA&amp;aq=0&amp;oq=Canada,&amp;sll=35.101934,-94.570312&amp;sspn=38.075006,86.572266&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Canada,+Pike,+Kentucky,+United+States&amp;ll=41.934977,-81.738281&amp;spn=11.438126,18.720703&amp;z=5&amp;iwloc=A&amp;output=embed"></iframe> -->
				</div>
				<div class="row-fluid carousel-area">
					<ul class="elastislide-list galleries-location"></ul>
				</div>
			</div>
		</div>
		<div class="change-location" style="display: none;">
			<a class="fetch-local" href="#" style="margin-left: 10px;">Change
				local directory</a><a class="browse-server" href="#">Browse Server</a>
		</div>
		<!------------------First-pop-up-------------------->
		<div id="popupplayer" class="video_popups">
			<a id="popupplayerClose" onClick="disablePopup('popupplayer')"
				class='popupClose'>x</a>
		</div>
		<div id="bgpopupplayer" class="backgroundPopup"></div>
	</div>

	<!-- Ads Section -->
    <?php include('right_advertising.phtml'); ?>
    <!-- End Ads Section -->

	<!-- Bottom Ads -->
    <?php include('bottom_advertising.phtml'); ?>
    <!-- End Bottom Ads -->

</div>