<?php
/**
 * Copyright memreas llc 2013
 */
use Guzzle\Http\Client;
use Application\Model\MemreasConstants;
// error_log('header.phtml->session_id()'.session_id().PHP_EOL);
// error_log('header.phtml->_Session[memreascookie]'.$_SESSION['memreascookie'].PHP_EOL);
error_log ( '_COOKIE---->' . print_r ( $_COOKIE, true ) );
// error_log('header.phtml->_Session[sid]'.$_SESSION['sid'].PHP_EOL);
// error_log('_SESSION vars inside header.phtml start...'.print_r($_SESSION, true).PHP_EOL);
$username = $_SESSION ['username'];
$domain = MemreasConstants::CLOUDFRONT_DOWNLOAD_HOST;
?>

<!-- Begin : Header -->
<div class="row-fluid rowfixed">
	<header>
		<div class="container clearfix">
			<div class="header-inner">
				<h1 id="logo">
					<a href="">memreas</a>
				</h1>

				<div class="search-sec">
					<div class="relative">
						<div class="input-wrap top-search">
							<input data-provide="typeahead" id="search" name="input"
								type="text" class="search_bar"
								value="@person, #hastag, !memreas"
								onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
								onFocus="if(this.value == '@person, #hastag, !memreas')this.value = '';" />
						</div>
						<span class="clear"></span>
					</div>
				</div>
				<div class="pro-info clicker">
					<div class="noti left">
						<a href="javascript:;" class="notification_icon"></a>
					</div>
					<div class="right toggle">
						<figure class="pro-pic">
							<img id="profile_picture" src="/memreas/img/profile-pic.jpg"
								alt="">
							<span id="noti" class="notification-count"><img
								src="/memreas/img/loading-line.gif" class="small-loading" /></span>
						</figure>
						<div class="pro-name">
							<img src="/memreas/img/loading-line.gif" class="loading-small" />
						</div>

						<div class="drop-inner click-nav slide-down">
							<ul class="no-js">
								<li>
									<ul>
										<li class="drop-1"><a href="javascript:;"
											onclick="goHomeTab();">HOME</a></li>
										<li class="drop-2"><a href="javascript:;"
											onclick="toggleNotification();"> <span class="arrow toggle-1"></span>Notification
										</a>
											<div class="slide-down-1 notification-head">
												<ul>

												</ul>
											</div></li>
										<li class="drop-3"><a href="javascript:;"
											onclick="goMoreTab();">More</a></li>
										<li class="drop-4"><a href="/index/logout" onClick="logout();">Log
												Out</a></li>
									</ul>
								</li>
							</ul>
							<span></span>
						</div>
					</div>
					<span class="clear"></span>
				</div>
			</div>
		</div>
	</header>
</div>
<div id="popupGiveMessage" class="popups">
	<a id="popupaccountviewcardClose"
		onClick="disablePopup('popupGiveMessage');" class='popupClose'>x</a>
	<h2>reply message</h2>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<ul id="content_1" class="scrollpopup give-message-form">
		<li><input type="hidden" name="card_id" id="card_id" value=""> <textarea
				name="notification-popup-message" class="notification-popup-message"
				style="width: 389px; height: 150px;" placeholder="Your message"></textarea>
		</li>
	</ul>
	<a class="black_btn_skin f-left" href="javascript:;"
		id="accept-notification"
		onclick="updateNotificationHeader(1, 'accept');">Update</a> <a
		class="black_btn_skin f-right"
		href="javascript:disablePopup('popupGiveMessage');">close</a>
</div>
<div id="bgpopupGiveMessage" class="backgroundPopup"></div>
<!-- End : Header -->

<!-- Script for logout -->
function logout() { var user_id = $("input[name=user_id]").val();
ajaxRequest( 'logout', [ {tag: 'user_id', value: user_id} ],function
(response){ if (getValueFromXMLTag(response, 'status') == "Success"){
alert('logging you out...'); } }); }
<!-- End script for logout -->

<!--Script for toggle down-->
<script>

$(document).ready(function() {

	
/* In case accordion is not hover instead on click, uncomment this script
	$('.toggle').toggle(function(){
		$('.slide-down').slideDown();
		return false;
	}, function() {
		$('.slide-down').slideUp();
		return false;
	});
*/

	$('.arrow').toggle(function(){
		$(this).addClass('arrow-2');
		$('.slide-down-1').slideDown();
		return false;
	}, function() {
		$(this).removeClass('arrow-2');
		$('.slide-down-1').slideUp();
		return false;
	});
});
</script>
<!--End of Script for toggle down-->