<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<!-- High piority scripts -->
<script type="text/javascript" src="/memreas/js/global.js"></script>
<script type="text/javascript" src="/memreas/js/constants.js"></script>
<script type="text/javascript" src="/memreas/js/strings.js"></script>
<!-- Fotorama -->
<script src="/memreas/jsblue/blueimp-helper.js"></script>
<script src="/memreas/jsblue/blueimp-gallery.js"></script>
<script src="/memreas/jsblue/blueimp-gallery-fullscreen.js"></script>
<script src="/memreas/jsblue/blueimp-gallery-indicator.js"></script>
<script src="/memreas/jsblue/blueimp-gallery-video.js"></script>
<script src="/memreas/jsblue/jquery.blueimp-gallery.js"></script>


<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="/memreas/js/jquery.cookie.js"></script>
<!-- akordeon -->
<script src="/memreas/js/jquery.akordeon.js" type="text/javascript"></script>
<script type="text/javascript" src="/memreas/js/ajax.js"></script>
<!--Bootstrap Typeahead -->
<script src="/memreas/js/search.js"></script>
<script src="/memreas/js/bootstrap-typeahead.js"></script>
<script src="/memreas/js/underscore-min.js"></script>
<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>

<!--Google Map-->
<script
	src="https://maps.google.com/maps/api/js?libraries=places&region=uk&language=en&sensor=true"></script>
<script type="text/javascript" src="/memreas/js/chosen.jquery.js"></script>
<script type="text/javascript" src="/memreas/js/jquery.simplePagination.js"></script>

<script src="/memreas/js/jquery.oauthpopup.js"></script>
<script src="/memreas/js/friend_memreas.js"></script>
<script src="/memreas/js/popup.js" type="text/javascript"></script>

<!-- custom scrollbars plugin -->
<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>

<!-- jQuery File Upload Dependencies -->
<link rel="stylesheet" href="/memreas/css/jquery-ui/jquery-ui.css">
<script src="/memreas/js/jquery-ui.min.js"></script>
<script src="/memreas/assets/js/jquery.iframe-transport.js"></script>
<script src="/memreas/assets/js/jquery.fileupload.js"></script>

<!--Backgound Strecher-->
 <script type="text/javascript" src="/memreas/js/jNotify.jquery.min.js"></script>
 <script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>

<!-- Ajax upload -->
 <script src="/memreas/js/s3upload.js"></script>

<!-- Audio -->
 <script src="/memreas/js/record/AudioContextMonkeyPatch.js"></script>
 <script src="/memreas/js/record/recorder.js"></script>
 <script src="/memreas/js/record/audio_record.js"></script>
 
 <!-- Location SLider-->
 <script type="text/javascript" src="/memreas/js-location-slider/jquerypp.custom.js"></script>
 <script type="text/javascript" src="/memreas/js-location-slider/jquery.elastislide.js"></script>
 <!-- Location SLider-->
                        
<!-- Memreas -->
<!-- 
<script type="text/javascript" src="/memreas/js/jquery.mouseSwipe.js"></script>
<script type="text/javascript" src="/memreas/js/gallery.js"></script>
<script type="text/javascript" src="/memreas/js/gallery_location.js"></script>
<script type="text/javascript" src="/memreas/js/share.js"></script>
<script type="text/javascript" src="/memreas/js/queue.js"></script>
<script type="text/javascript" src="/memreas/js/memreas.js"></script>
<script type="text/javascript" src="/memreas/js/jquerypp.custom.js"></script>
<script type="text/javascript" src="/memreas/js/jquery.elastislide.js"></script>
<script type="text/javascript" src="/memreas/js/memreas_details.js"></script>
<script type="text/javascript" src="/memreas/js/notification.js"></script>
<script type="text/javascript" src="/memreas/js/more_tabs/subscription.js"></script>
<script type="text/javascript" src="/memreas/js/more_tabs/sellmedia.js"></script>
<script type="text/javascript" src="/memreas/js/more_tabs/feedback.js"></script>
<script type="text/javascript" src="/memreas/js/more_tabs/account.js"></script>
<script type="text/javascript" src="/memreas/js/more_tabs/buycredit.js"></script>
<script type="text/javascript" src="/memreas/js/more_tabs/friends.js"></script>
<script type="text/javascript" src="/memreas/js/more_tabs/help.js"></script>
<script type="text/javascript" src="/memreas/js/more_page.js"></script>
<script src="/memreas/js/jquery.swipebox.min.js"></script>
<script type="text/javascript" src="/memreas/js/memreas_tab/buymedia.js"></script>
<script src="/memreas/js/bootstrap-datepicker.js"></script>' 
 -->
<script type="text/javascript">

    $(function(){
       $('body').append(
    					'<!--Social Library-->' +
                       '<script src="\/memreas\/js\/jquery.oauthpopup.js"><\/script>' +
                       '<script src="\/memreas\/js\/friend_memreas.js"><\/script>' +

                        '<!-- pop-up -->' +
                        '<script src="\/memreas\/js\/popup.js" type="text\/javascript"><\/script>' +

                        '<!-- custom scrollbars plugin -->' +
                        '<script src="\/memreas\/js\/jquery.mCustomScrollbar.concat.min.js"><\/script>' +

                        '<!-- jQuery File Upload Dependencies -->' +
                        '<link rel="stylesheet" href="\/memreas\/css\/jquery-ui\/jquery-ui.css">' +
                        '<script src="\/memreas\/js\/jquery-ui.min.js"><\/script>' +
                        '<script src="\/memreas\/assets\/js\/jquery.iframe-transport.js"><\/script>' +
                        '<script src="/memreas/assets/js/jquery.fileupload.js"><\/script>' +

                        '<!--Backgound Strecher-->' +
                        '<script type="text\/javascript" src="\/memreas\/js\/jNotify.jquery.min.js"><\/script>' +
                        '<script type="text\/javascript" src="\/memreas\/js\/bgstretcher.js"><\/script>' +

                        '<!-- Ajax upload -->' +
                        '<script src="\/memreas\/js\/s3upload.js"><\/script>' +

                        '<!-- Audio -->' +
                        '<script src="\/memreas\/js\/record\/AudioContextMonkeyPatch.js"><\/script>' +
                        '<script src="\/memreas\/js\/record\/recorder.js"><\/script>' +
                        '<script src="\/memreas\/js\/record\/audio_record.js"><\/script>' +
                        
 		               '<!-- Memreas -->' +
		               '<script type="text\/javascript" src="\/memreas\/js\/jquery.mouseSwipe.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/gallery.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/gallery_location.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/share.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/queue.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/memreas.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/jquerypp.custom.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js/jquery.elastislide.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/memreas_details.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/notification.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/more_tabs\/subscription.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/more_tabs\/sellmedia.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/more_tabs\/feedback.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/more_tabs\/account.js"><\/script>' +
						'<script type="text\/javascript" src="\/memreas\/js\/more_tabs\/buycredit.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/more_tabs\/friends.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/more_tabs\/help.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/more_page.js"><\/script>' +
		               '<script src="\/memreas\/js\/jquery.swipebox.min.js"><\/script>' +
		               '<script type="text\/javascript" src="\/memreas\/js\/memreas_tab\/buymedia.js"><\/script>' +
		               '<script src="\/memreas\/js\/bootstrap-datepicker.js"><\/script>' 

		               );
       
    });
</script>


