<!-- JW Player plugin -->
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.js"></script>
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.html5.js"></script>

<!--jQuery Lybrary-->
<script src="/memreas/js/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/memreas/js/global.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="/memreas/js/jquery.cookie.js"></script>

<!--Google Map-->
<script src="http://maps.google.com/maps/api/js?libraries=places&region=uk&language=en&sensor=true"></script>

<!-- Fotorama -->
<script src="/memreas/js/fotorama.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>
<script src="/memreas/js/bootstrap-datepicker.js"></script>

<!--Social Library-->
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script src="/memreas/js/facebook.js"></script>
<script src="/memreas/js/jquery.oauthpopup.js"></script>
<script src="/memreas/js/twitter.js"></script>
<script src="/memreas/js/friend_memreas.js"></script>

<!-- akordeon -->
<script src="/memreas/js/jquery.akordeon.js" type="text/javascript"></script>

<!-- pop-up -->
<script src="/memreas/js/popup.js" type="text/javascript"></script>

<!-- custom scrollbars plugin -->
<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>

<!-- For drag and drop upload -->
<link href="/memreas/assets/css/style.css" rel="stylesheet" />
<!-- jQuery File Upload Dependencies -->
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="/memreas/assets/js/jquery.iframe-transport.js"></script>
<script src="/memreas/assets/js/jquery.fileupload.js"></script>

<!--Backgound Strecher-->
<script src="/memreas/js/jNotify.jquery.min.js"></script>
<script type="text/javascript" src="/memreas/js/jquery.xml2json.js"></script>
<script type="text/javascript" src="/memreas/js/fetchLocalMedia.js"></script>
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript" src="/memreas/js/serverSide.js"></script>
<script src="/memreas/js/base_func.js"></script>
<script type="text/javascript" src="/memreas/js/ajax.js"></script>
<script src="/memreas/js/share.js"></script>
<script type="text/javascript" src="/memreas/js/syncing.js"></script>

<!-- Our main JS file -->
<script src="/memreas/assets/js/script.js"></script>

<!-- <script src="/memreas/js/record/AudioContextMonkeyPatch.js"></script> -->
<!-- <script src="/memreas/js/record/recorder.js"></script> -->
<!-- <script src="/memreas/js/record/audio_record.js"></script> -->

<!-- Memreas -->
<script src="/memreas/js/jquery.mouseSwipe.js" type="text/javascript"></script>
<script type="text/javascript" src="/memreas/js/queue.js"></script>
<script type="text/javascript" src="/memreas/js/memreas.js"></script>
<script type="text/javascript" src="/memreas/js/jquerypp.custom.js"></script>
<script type="text/javascript" src="/memreas/js/jquery.elastislide.js"></script>
<script type="text/javascript" src="/memreas/js/memreas_details.js"></script>
<script type="text/javascript" src="/memreas/js/notification.js"></script>
<script type="text/javascript" src="/memreas/js/more_page.js"></script>
<script src="/memreas/js/jquery.swipebox.min.js"></script>

<!--Bootstrap Typeahead -->
<script src="/memreas/js/search.js"></script>

<script src="/memreas/js/bootstrap-typeahead.js"></script>
<script src="//underscorejs.org/underscore-min.js"></script>

<script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>
<script type="text/javascript">
    var featherEditor = new Aviary.Feather({
       apiKey: '057e9da017baf0f8',
       apiVersion: 3,
       theme: 'dark', // Check out our new 'light' and 'dark' themes!
       tools: 'crop,resize',
       appendTo: '',
       onSave: function(imageID, newURL) {
           var img = document.getElementById(imageID);
           img.src = newURL;
       },
       onError: function(errorObj) {
           alert(errorObj.message);
       }
    });
    function launchEditor(id, src) {
       featherEditor.launch({
           image: id,
           url: src
       });
      return false;
    }
</script>