<div class="span11 tabcontent-detail" id="more" style="display: none;">
      <div class="<?php echo ($this->enableAdvertising) ? 'span9' : 'span11';?>">
          <div class="row-fluid">
            <ul id="tabs-more" class="small_tabs">
                <li><a href="#" title="tab1-more">account</a></li>
                <li><a href="#" title="tab2-more">groups</a></li>
                <li><a href="#" title="tab3-more">network</a></li>
                <li><a href="#" title="tab4-more">notification</a></li>
                <li><a href="#" title="tab5-more">help</a></li>
                <li><a href="#" title="tab6-more">memreas</a></li>
                <li><a href="#" title="tab7-more">Subscriptions</a></li>
                <li><a href="#" title="tab8-more">Buy credit</a></li>
            </ul>

<div id="tab-content-more">
    <div id="tab1-more" class="hideCls account">
          <figure class="pro-pics" id="setting-userprofile"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
          <div class="pro-names2" id="setting-username">User Name</div>
          <form name="frm_profile_pic" id="frm-profile-pic" enctype="multipart/form-data" action="https://<?php echo $data['bucket']; ?>.s3.amazonaws.com/">
            <input type="hidden" name="key" value="{$filename}">
            <input type="hidden" name="AWSAccessKeyId" value="">
            <input type="hidden" name="acl" value="public-read">
            <input type="hidden" name="success_action_status" value="201">
            <input type="hidden" name="policy" value="">
            <input type="hidden" name="signature" value="">
            <input type="file" name="file" id="file" style="opacity: 0; -moz-opacity:0; -webkit-opacity: 0; filter: alpha(opacity = 0); margin: 0;width: 1px;height: 1px;">
        </form>
          <a class="black_btn_skin f-center change-profile-btn" href="javascript:;">Change Picture</a>
          <div class="clear"></div>
          <div class="akordeon" id="buttons-moretab" style="margin-top: 10px;">
              <?php include('more_tabs/account.phtml'); ?>
        </div>
    </div>
    <div id="tab2-more" class="hideCls">
          <div class="akordeon" id="buttons2-moretab">
              <?php include('more_tabs/group.phtml'); ?>
          </div>
         <a class="black_btn_skin f-center" href="javascript:;" onclick="addFriendNetwork();" style="margin-left: 10% !important;">Add friend</a>
         <a class="black_btn_skin" href="javascript:;" onclick="updateNetworkFriends();">update</a>
         <a class="black_btn_skin" href="#">cancel</a>

         <!-- POPUP FRIEND HERE -->
         <div id="popupNetworkFriends" class="popups">
            <a id="popupNetworkFriendsClose" onClick="disablePopup('popupNetworkFriends')" class='popupClose'>x</a>
            <h2>select friends</h2>
            <div class="styled-select">
                <select style="width: 390px" id="network-dropfriend">
                  <option value="facebook">facebook</option>
                  <option value="twitter">twitter</option>
                  <option value="memreas">memreas</option>
                </select>
            </div>
            <ul id="content_1" class="popupContact popupNetworkFriends_list scrollpopup">
                <!-- Ajax friend will load here -->
            </ul>
            <div style="clear: both;">
                <h2 id="network-groupname" name="demo_lbl_6">Group: <span></span></h2>
            </div>
            <a class="black_btn_skin f-left memreas-addfriend-btn" href="javascript:;" onclick="acceptAddFriendNetwork();">ok</a> <a class="black_btn_skin f-right" href="javascript:;" onClick="disablePopup('popupNetworkFriends')">cancel</a>
        </div>
        <div id="bgpopupNetworkFriends" class="backgroundPopup"></div>
         <!-- END POPUP FRIEND -->

    </div>
    <div id="tab3-more" class="hideCls">
         <div class="akordeon" id="buttons3-moretab">
            <?php include ('more_tabs/network.phtml'); ?>
        </div>
    </div>
    <div id="tab4-more" class="hideCls">
       <div class="akordeon" id="buttons4-moretab">
            <?php include ('more_tabs/notification.phtml'); ?>
        </div>
    </div>
     <div id="tab5-more" class="hideCls">
      <div class="akordeon" id="buttons5-moretab">
        <?php include ('more_tabs/help.phtml'); ?>
      </div>
    </div>
    <div id="tab6-more" class="hideCls">
       <div class="akordeon" id="buttons6-moretab">
            <?php include ('more_tabs/manage_event.phtml'); ?>
        </div>
    </div>
    <div id="tab7-more" class="hideCls">
        <input type="hidden" name="stripe_url" value="<?php echo $this->stripeUrl; ?>" />
       <div class="akordeon" id="buttons7-moretab">
            <?php include ('more_tabs/subscription.phtml'); ?>
        </div>
    </div>
    <div id="tab8-more" class="hideCls">
        <div class="akordeon" id="buttons8-moretab">
            <?php include ('more_tabs/buycredit.phtml'); ?>
        </div>
    </div>
</div>
        </div>
      </div>
        <!-- Ads Section -->
        <?php include('right_advertising.phtml'); ?>
        <!-- End Ads Section -->

        <!-- Bottom Ads -->
        <?php include('bottom_advertising.phtml'); ?>
        <!-- End Bottom Ads -->
      </div>

<div id="more_dlg_locationmap" class="popups2">
    <a id="more_btn_locationmap_close" onClick="javascript:more_closeGoogleMap(false);" class='popupClose'>x</a>
    <h2>location</h2>
    <a id="more_btn_locationmap_ok" class="black_btn_skin btn_locationmap_ok" href="javascript:more_closeGoogleMap(true);">OK</a>
    <input id="more_txt_locationmap_address" class="txt_locationmap_address" name="input" type="text" />
    <div class="clear"></div>
    <div id="more_div_locationmap_maparea" class="map_box"></div>
</div>
<div id="more_div_locationmap_back" class="backgroundPopup"></div>

<div id="popupaddcard" class="popups">
    <a id="popupaddcardClose" onClick="disablePopup('popupaddcard');" class='popupClose'>x</a>
    <h2>Add new card</h2>
    <ul id="content_1" class="scrollpopup addCardForm">
        <li>
            <label class="textfield_names">First name*</label>
            <input name="input" type="text" id="addcard_fname" class="" value="first name" default="first name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'first name')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Last name*</label>
            <input name="input" type="text" id="addcard_lname" class="" value="last name" default="last name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'last name')this.value = '';"/>
        </li>
         <li>
            <label class="textfield_names">Address 1*</label>
            <input name="input" type="text" id="addcard_address1" class="" value="Address line 1" default="Address line 1" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Address line 1')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Address 2</label>
            <input name="input" type="text" id="addcard_address2" class="" value="Address line 2" default="Address line 2" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Address line 2')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">City*</label>
            <input name="input" type="text" id="addcard_city" class="" value="City" default="City" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'City')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">State*</label>
            <input name="input" type="text" id="addcard_state" class="" value="State" default="State" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'State')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Zip*</label>
            <input name="input" type="text" id="addcard_zip" class="" value="Zip" default="Zip" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Zip')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Card type*</label>
            <select name="addcard_cctype" id="addcard_cctype">
                <option value="">-Choose-</option>
                <option value="visa">Visa</option>
                <option value="master">Master</option>
                <option value="discover">Discover</option>
                <option value="amex">Amex</option>
            </select>
        </li>
        <li>
            <label class="textfield_names">Card no.*</label>
            <input name="input" type="text" id="addcard_ccnum" class="" value="Card number" default="Card number" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Card number')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Exp mon.*</label>
            <select name="addcard_expmonth" id="addcard_expmonth">
                <option value="">-Choose-</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
        </li>
        <li>
            <label class="textfield_names">Exp year*</label>
            <select name="addcard_expyear" id="addcard_expyear">
                <option value="">-Choose-</option>
                <option value="2014">2014</option>
                <option value="2015">2015</option>
                <option value="2016">2016</option>
                <option value="2017">2017</option>
                <option value="2018">2018</option>
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
                <option value="2023">2023</option>
                <option value="2024">2024</option>
                <option value="2025">2025</option>
                <option value="2026">2026</option>
            </select>
        </li>
        <li>
            <label class="textfield_names">Card CVC*</label>
            <input name="input" type="text" id="addcard_ccv" class="" value="Card code" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Card code')this.value = '';"/>
        </li>
    </ul>
    <a class="black_btn_skin f-left" href="javascript:;" onclick="stripeAddCard();">ok</a> <a class="black_btn_skin f-right" href="javascript:disablePopup('popupaddcard');">cancel</a>
</div>
<div id="bgpopupaddcard" class="backgroundPopup"></div>

<!-- Order summary content -->
<div class="order-summary-preview hide-onload">
    <ul>
        <li>
            <label class="textfield_names">Name :</label>
            <input name="input" type="text" id="order-summary-name" class="share-txtfield" value="name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'name')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Address :</label>
            <input name="input" type="text" id="order-summary-address1" class="share-txtfield" value="address line 1" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address line 1')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Address Line 2:</label>
            <input name="input" type="text" id="order-summary-address2" class="share-txtfield" value="address line 2" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address line 2')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Card type :</label>
            <div class="styled-select" style="width: 72%; margin: 0;">
                <select id="order-summary-cardtype">
                    <option value="">-Choose-</option>
                    <option value="VisaCard">Visa</option>
                    <option value="MasterCard">Master</option>
                    <option value="discover">Discover</option>
                    <option value="Amex">Amex</option>
                </select>
            </div>
        </li>
        <li>
            <label class="textfield_names">Card number</label>
            <input name="input" type="text" id="order-summary-ccnum" class="" value="card number" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'card number')this.value = '';" readonly />
        </li>
        <li>
            <label class="textfield_names">Exp date:</label>
            <input name="input" type="text" id="order-summary-expdate" class="" value="exp date" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'exp date')this.value = '';" readonly />
        </li>
        <li>
            <label class="textfield_names">Exp year:</label>
            <input name="input" type="text" id="order-summary-expyear" class="" value="exp year" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'exp year')this.value = '';" readonly />
        </li>
        <li>
            <label class="textfield_names">City:</label>
            <input name="input" type="text" id="order-summary-city" class="" value="city" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'city')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">State:</label>
            <input name="input" type="text" id="order-summary-state" class="" value="state" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'state')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Zip:</label>
            <input name="input" type="text" id="order-summary-zip" class="" value="zip" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'zip')this.value = '';"/>
        </li>
        <li>
            <label class="textfield_names">Plan name:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 300px;" id="choose-plan-name">Plan A</label>
        </li>
        <li>
            <label class="textfield_names">Cost:</label>
            <label class="textfield_names" style="margin-left: 10px;" id="choose-plan-cost">$12</label>
        </li>
    </ul>
</div>
<!-- END -->
<div class="order-summary-recept hide-onload">
    <ul>
        <li>
            <label class="textfield_names" style="width: 150px;">Name:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-name">John Miller</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Address:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-address1">Address line 1</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Address 2:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-address2">Address line 2</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Card type :</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-cardtype">Visa</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Card number</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-ccnum">xxxxxxxxxxxx5452</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Exp date:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-expdate">02</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Exp year:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-expyear">2016</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">City:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-city">Newyork</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">State:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-state">NY</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Zip:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="order-recept-zip">25525</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Plan name:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="choose-planrecept-name">Plan A</label>
        </li>
        <li>
            <label class="textfield_names" style="width: 150px;">Cost:</label>
            <label class="textfield_names" style="margin-left: 10px; width: 200px;" id="choose-planrecept-cost">$12</label>
        </li>
    </ul>
</div>
