<div class="span11 tabcontent-detail" id="more" style="display: none;">
      <div class="<?php echo ($this->enableAdvertising) ? 'span9' : 'span11';?>">
          <div class="row-fluid">
            <ul id="tabs-more" class="small_tabs">
                <li><a href="#" title="tab1-more">account</a></li>
                <li><a href="#" title="tab2-more">groups</a></li>
                <li><a href="#" title="tab3-more">network</a></li>
                <li><a href="#" title="tab4-more">notification</a></li>
                <li><a href="#" title="tab5-more">help</a></li>
                <li><a href="#" title="tab6-more">memreas</a></li>
            </ul>

<div id="tab-content-more">
    <div id="tab1-more" class="hideCls account">
          <figure class="pro-pics" id="setting-userprofile"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
          <div class="pro-names2" id="setting-username">User Name</div>
          <form name="frm_profile_pic" id="frm-profile-pic" enctype="multipart/form-data" action="https://<?php echo $data['bucket']; ?>.s3.amazonaws.com/">
            <input type="hidden" name="key" value="{$filename}">
            <input type="hidden" name="AWSAccessKeyId" value="">
            <input type="hidden" name="acl" value="public-read">
            <input type="hidden" name="success_action_status" value="201">
            <input type="hidden" name="policy" value="">
            <input type="hidden" name="signature" value="">
            <input type="file" name="file" id="file" style="opacity: 0; -moz-opacity:0; -webkit-opacity: 0; filter: alpha(opacity = 0); margin: 0;width: 1px;height: 1px;">
        </form>
          <a class="black_btn_skin f-center change-profile-btn" href="javascript:;">Change Picture</a>
          <div class="clear"></div>
          <div class="akordeon" id="buttons-moretab" style="margin-top: 10px;">
              <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            profile
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                          <input name="account_email" type="text" class="more-input" value="email" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'email')this.value = '';"/><br/>
                          <input name="account_password" type="password" class="more-input" value="password" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'password')this.value = '';" /><br/>
                          <input name="account_repassword" type="password" class="more-input" value="password" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'password')this.value = '';" />
                        <a class="black_btn_skin f-center" href="javascript:;" onclick="saveUserDetail();">ok</a>
                        <a class="black_btn_skin" href="#">cancel</a>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            plans
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <label class="label_text"><input type="radio" id="radio-1-1" name="radio-1-set" class="regular-radio" checked /><label for="radio-1-1"></label>example text plans</label>
                        <label class="label_text"><input type="radio" id="radio-1-2" name="radio-1-set" class="regular-radio" /><label for="radio-1-2"></label>example text plans-2</label>
                        <label class="label_text"><input type="radio" id="radio-1-3" name="radio-1-set" class="regular-radio" /><label for="radio-1-3"></label>example text plans-3</label>
                    </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            credit card data
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <div class="more-select">
                           <select>
                              <option>credit card type</option>
                              <option>Visa</option>
                              <option>Mastro</option>
                           </select>
                        </div>
                        <input name="input" type="text" class="more-input" value="credit card number " onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'credit card number')this.value = '';"/>
                        <div class="more-select2">
                           <select>
                              <option>expiration month</option>
                              <option>January</option>
                              <option>February</option>
                              <option>March</option>
                              <option>April</option>
                              <option>May</option>
                              <option>June</option>
                              <option>July</option>
                              <option>August</option>
                              <option>September</option>
                              <option>October</option>
                              <option>November</option>
                              <option>December</option>
                           </select>
                        </div>
                        <div class="more-select2">
                           <select>
                              <option>expiration year</option>
                              <option>2013</option>
                              <option>2014</option>
                              <option>2015</option>
                              <option>2016</option>
                              <option>2017</option>
                              <option>2018</option>
                              <option>2019</option>
                              <option>2020</option>
                           </select>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            billing address
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <input name="input" type="text" class="more-input" value="address line 1" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address line 1')this.value = '';"/>
                        <input name="input" type="text" class="more-input" value="address line 2" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address line 2')this.value = '';"/>
                        <input name="input" type="text" class="more-input" value="city" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'city')this.value = '';"/>
                        <div class="more-select2">
                           <select>
                              <option>state</option>
                              <option>Alaska</option>
                              <option>California</option>
                              <option>Florida</option>
                              <option>Georgia</option>
                              <option>Hawaii</option>
                              <option>New York</option>
                              <option>New Jersey</option>
                              <option>Washington</option>
                           </select>
                        </div>
                        <input name="input" type="text" class="more-input2" value="postal / zip code" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'postal / zip code')this.value = '';"/>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            paypal section
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <input name="input" type="text" class="more-input" value="Paypal user name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Paypal user name')this.value = '';"/>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            Logout
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                      <h5 style="float: right;">System will log you out when clicking on logout button below</h5>
                        <a class="black_btn_skin" href="/index/logout">Logout</a>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="tab2-more" class="hideCls">
          <div class="akordeon" id="buttons2-moretab">
              <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            group
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                       <div class="group-select">
                         <select class="account-groups" name="account_groups">
                            <option value="">-Choose-</option>
                         </select>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container network-heading">
                        <div class="akordeon-heading">
                            network
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="more-select">
                       <select name="friend_network">
                          <option value="">-Choose-</option>
                          <option value="memreas">memreas</option>
                          <option value="facebook">facebook</option>
                          <option value="twitter">twitter</option>
                       </select>
                      </div>
                      <ul class="group scrollClass network-friends">
                        <!-- Friend network will loaded here -->
                      </ul>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            email address list
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <input name="input" type="text" class="more-input" value="add your email list here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'add your email list here')this.value = '';"/>
                    </div>
                </div>
            </div>
        </div>
         <a class="black_btn_skin f-center" href="javascript:;" onclick="addFriendNetwork();" style="margin-left: 10% !important;">Add friend</a> <a class="black_btn_skin" href="javascript:;" onclick="updateNetworkFriends();">update</a> <a class="black_btn_skin" href="#">cancel</a>

         <!-- POPUP FRIEND HERE -->
         <div id="popupNetworkFriends" class="popups">
            <a id="popupNetworkFriendsClose" onClick="disablePopup('popupNetworkFriends')" class='popupClose'>x</a>
            <h2>select friends</h2>
            <div class="styled-select">
                <select style="width: 390px" id="network-dropfriend">
                  <option value="facebook">facebook</option>
                  <option value="twitter">twitter</option>
                  <option value="memreas">memreas</option>
                </select>
            </div>
            <ul id="content_1" class="popupContact popupNetworkFriends_list scrollpopup">
                <!-- Ajax friend will load here -->
            </ul>
            <div style="clear: both;">
                <h2 id="network-groupname" name="demo_lbl_6">Group: <span></span></h2>
            </div>
            <a class="black_btn_skin f-left memreas-addfriend-btn" href="javascript:;" onclick="acceptAddFriendNetwork();">ok</a> <a class="black_btn_skin f-right" href="javascript:;" onClick="disablePopup('popupNetworkFriends')">cancel</a>
        </div>
        <div id="bgpopupNetworkFriends" class="backgroundPopup"></div>
         <!-- END POPUP FRIEND -->

    </div>
    <div id="tab3-more" class="hideCls">
         <div class="akordeon" id="buttons3-moretab">
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            Wifi Settings
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body"  style="padding-bottom: 10px;">
                    <div class="akordeon-item-content">
                        <input id="demo_box_1" class="css-checkbox" type="checkbox" checked="checked"/>
                           <label for="demo_box_1" name="demo_lbl_4" class="css-label margin-none" >Queue uploads and downloads only when on Wifi (default)</label>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            Upload / Download Options
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <ul class="option" >
                               <li>
                                <input id="demo_box_2" class="css-checkbox" type="checkbox" checked="checked"/>
                                      <label for="demo_box_2" name="demo_lbl_4" class="css-label margin-none" >Download Full Resolution Photos<br><small> Note: not recommended for devices with low disk space</small></label>
                            </li>
                            <li>
                                   <input id="demo_box_3" class="css-checkbox" type="checkbox" checked="checked"/>
                                      <label for="demo_box_3" name="demo_lbl_4" class="css-label margin-none" >Auto Upload<br><small> Enable automatic uploads of photos when added to gallery or events (default)</small></label>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="tab4-more" class="hideCls">
       <div class="akordeon" id="buttons4-moretab">
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            media
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <label class="label_text2"><input type="radio" id="radio-2-1" name="radio-2-set" class="regular-radio" /><label for="radio-2-1"></label>off</label>
                        <label class="label_text2"><input type="radio" id="radio-2-2" name="radio-2-set" class="regular-radio" /><label for="radio-2-2"></label>people I follow</label>
                        <label class="label_text2"><input type="radio" id="radio-2-3" name="radio-2-set" class="regular-radio" checked /><label for="radio-2-3"></label>everyone (default)</label>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            like notification
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <label class="label_text2"><input type="radio" id="radio-3-1" name="radio-3-set" class="regular-radio" /><label for="radio-3-1"></label>off</label>
                        <label class="label_text2"><input type="radio" id="radio-3-2" name="radio-3-set" class="regular-radio" /><label for="radio-3-2"></label>people I follow</label>
                        <label class="label_text2"><input type="radio" id="radio-3-3" name="radio-3-set" class="regular-radio" checked /><label for="radio-3-3"></label>everyone (default)</label>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            comment notification
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <label class="label_text2"><input type="radio" id="radio-4-1" name="radio-4-set" class="regular-radio" /><label for="radio-4-1"></label>off</label>
                        <label class="label_text2"><input type="radio" id="radio-4-2" name="radio-4-set" class="regular-radio" /><label for="radio-4-2"></label>people I follow</label>
                        <label class="label_text2"><input type="radio" id="radio-4-3" name="radio-4-set" class="regular-radio" checked /><label for="radio-4-3"></label>everyone (default)</label>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            event requests
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <label class="label_text2"><input type="radio" id="radio-5-1" name="radio-5-set" class="regular-radio" /><label for="radio-5-1"></label>off</label>
                        <label class="label_text2"><input type="radio" id="radio-5-2" name="radio-5-set" class="regular-radio" /><label for="radio-5-2"></label>friends</label>
                        <label class="label_text2"><input type="radio" id="radio-5-3" name="radio-5-set" class="regular-radio" checked /><label for="radio-5-3"></label>everyone (default)</label>
                      </div>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            friend requests
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <div class="button-holder">
                        <label class="label_text2"><input type="radio" id="radio-6-1" name="radio-6-set" class="regular-radio" /><label for="radio-6-1"></label>off</label>
                        <label class="label_text2"><input type="radio" id="radio-6-2" name="radio-6-set" class="regular-radio" /><label for="radio-6-2"></label>friends</label>
                        <label class="label_text2"><input type="radio" id="radio-6-3" name="radio-6-set" class="regular-radio" checked /><label for="radio-6-3"></label>everyone (default)</label>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <div id="tab5-more" class="hideCls">
      <div class="akordeon" id="buttons5-moretab">
              <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            feedback
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                      <ul class="share_memreas_details">
                        <li>
                          <label class="textfield_names">name :</label>
                          <input name="input" type="text" class="share-txtfield" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';"/>
                        </li>
                        <li>
                          <label class="textfield_names">email :</label>
                          <input name="input" type="text" class="share-txtfield" value="sample@mail.com" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample@mail.com')this.value = '';"/>
                        </li>
                        <li>
                          <label class="textfield_names">message :</label>
                          <textarea name="" cols="" rows="" class="share-txtfield"></textarea>
                          <a class="black_btn_skin f-center" href="#" style="margin-left: 30% !important;">ok</a>
                          <a class="black_btn_skin" href="#">cancel</a>
                        </li>
                      </ul>
                    </div>
                </div>
            </div>
              <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            usage basics
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.</p>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            faqs
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.</p>
                        <p>Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend.</p>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            member guidelines
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.</p>
                        <p>Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend.</p>
                    </div>
                </div>
            </div>
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            privacy policy
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.</p>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            terms of service
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.</p>
                        <p>Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend.</p>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            version:
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body">
                    <div class="akordeon-item-content">
                        <p><strong>Application Version: </strong>0.987</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="tab6-more" class="hideCls">
       <div class="akordeon" id="buttons6-moretab">
            <div class="akordeon-item expanded">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container">
                        <div class="akordeon-heading">
                            memreas detail
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body"  style="padding-bottom: 10px;">
                    <div class="akordeon-item-content">
                        <ul id="content_1" class="share_memreas_details">
                            <li>
                                <label class="textfield_names">name :</label>
                                <div class="styled-select">
                                    <select id="cmd_MorepageEvents"></select>
                                </div>
                            </li>
                            <li>
                                <label class="textfield_names">date :</label>
                                <input name="input" type="text" id="morepage_eventDate" class="share-txtfield date-picker" readonly value="from" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'from')this.value = '';"/>
                            </li>
                            <li>
                                <label class="textfield_names">location :</label>
                                <input name="input3" type="text" id="morepage_eventLocation" class="share-txtfield" value="address or current location" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address or current location')this.value = '';" onClick="share_showGoogleMap('div_locationmap_maparea');"/>
                            </li>
                            <li>
                                <input id="" class="css-checkbox" type="checkbox" name="ckb_canpost"/>
                                <label for="ckb_canpost" name="demo_lbl_1" class="css-label margin-none" >friends can post pics/videos</label>
                            </li>
                            <li>
                                <input id="" class="css-checkbox" type="checkbox" name="ckb_canadd"/>
                                <label for="ckb_canadd" name="demo_lbl_2" class="css-label margin-none" >friends can add Friends</label>
                            </li>
                            <li>
                                <input id="" class="css-checkbox" type="checkbox" name="ckb_public"/>
                                <label for="ckb_public" name="demo_lbl_3" class="css-label margin-none" onClick="javascript:share_clickCkbPublic();" >public (anyone can add or post)</label>
                            </li>
                            <li>
                                <input id="" class="css-checkbox" type="checkbox" />
                                <label for="ckb_viewable" name="demo_lbl_4" class="css-label margin-none" >viewable :</label>
                                <input name="input" type="text" id="moredate_eventDateFrom" class="date-picker" readonly value="from" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'from')this.value = '';"/>
                                <input name="input" type="text" id="moredate_eventDateTo" class="date-picker" readonly value="to" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'to')this.value = '';"/>
                            </li>
                            <li>
                                <input id="" class="css-checkbox" type="checkbox" />
                                <label for="ckb_selfdestruct" name="demo_lbl_5" class="css-label margin-none" >self destruct :</label>
                                <input name="input" type="text" id="morepage_eventSelfDestruct" class="share-txtfield-2 date-picker" readonly value="" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '')this.value = '';"/>
                            </li>
                        </ul>
                        <a class="black_btn_skin f-center" href="javascript:;" onclick="morepage_saveEvent();">Save</a>
                        <a class="black_btn_skin" href="javascript:;">cancel</a>
                    </div>
                </div>
            </div>
            <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container memreas-media-header">
                        <div class="akordeon-heading">
                            media
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body" style="height: 300px;">
                    <div class="akordeon-item-content">
                        <ul class="memreasEventMedia"></ul>
                    </div>
                </div>
            </div>
             <div class="akordeon-item">
                <div class="akordeon-item-head">
                    <div class="akordeon-item-head-container memreas-friend-header">
                        <div class="akordeon-heading">
                            Friends
                        </div>
                    </div>
                </div>
                <div class="akordeon-item-body" style="height: 300px;">
                    <div class="akordeon-item-content">
                        <ul class="memreasMorepageFriends"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        </div>
      </div>
        <!-- Ads Section -->
        <?php include('right_advertising.phtml'); ?>
        <!-- End Ads Section -->

        <!-- Bottom Ads -->
        <?php include('bottom_advertising.phtml'); ?>
        <!-- End Bottom Ads -->
      </div>