<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php
use Guzzle\Http\Client;
use Zend\Session\Container;
use Application\Model\MemreasConstants;

$username = $_SESSION['username'];
$domain = MemreasConstants::CLOUDFRONT_DOWNLOAD_HOST;
?>

<!-- Begin : Nav -->
<div class="span1" id="main-tab">
    <nav>
        <ul>
            <li><a href="javascript:;" class="gallery active" title="gallery" onclick="return false;"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="javascript:;" class="queue" title="queue" onclick="return false;"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="javascript:;" class="share" title="share"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="javascript:;" class="memreas" title="memreas"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="javascript:;" class="more" title="more"><img src="/memreas/img/more.png" alt=""></a></li>
        </ul>
    </nav>
</div>
<!-- End : Nav -->
