<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<div class="span11 notification-area" style="display: none;">
    <div class="<?php echo ($this->enableAdvertising) ? 'span9' : 'span11';?>">
        <ul class="notificationresults scrollClass">

        </ul>
        <!--
        <a class="black_btn_skin f-center" href="#">ok</a>
        <a class="black_btn_skin" href="#">cancel</a>
        -->
    </div>
    <!-- Ads Section -->
    <?php include('right_advertising.phtml'); ?>
    <!-- End Ads Section -->

    <!-- Bottom Ads -->
    <?php include('bottom_advertising.phtml'); ?>
    <!-- End Bottom Ads -->
</div>