<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php
use Application\Model\MemreasConstants;
?>
<div class="span11 tabcontent-detail" id="queue" style="display: none;">
	<div
		class="span11">
		<div class="row-fluid">
			<ul id="tabs-queue" class="medium_tabs">
				<li><a href="#" title="upload-queue" class="tabs2">uploads</a></li>
				<li><a href="#" title="complete" class="tabs2">completed</a></li>
			</ul>
			<div id="tab-content-queue">
				<div id="upload-queue" class="hideCls">
					<ul id="content_1" class="image_upload_box">
						<li class="first-upload"></li>
					</ul>
					<!-- Direct Upload to S3 -->
                    <form action="https://<?php echo MemreasConstants::S3BUCKET; ?>.s3.amazonaws.com/" method="POST" enctype="multipart/form-data" class="media-upload" id="media-upload-form" form-type="media-upload">
	                    <input type="hidden" name="key" value="">
    	        				<input type="hidden" name="Content-Type" value="">
	                    <input type="hidden" name="acl" value="">
        		    			<input type="hidden" name="success_action_status" value="">
            				<input type="hidden" name="policy" value="">
            				<input type="hidden" name="x-amz-algorithm" value="">
	            			<input type="hidden" name="x-amz-credential" value="">
    	    	    				<input type="hidden" name="x-amz-date" value="">
        		    			<input type="hidden" name="x-amz-expires" value="">
    		        			<input type="hidden" name="x-amz-signature" value="">
    		        			<input type="hidden" name="x-amz-server-side-encryption" value="AES256">

                        <div id="upload-dropzone" class="upload-dropzone upload-from-event" style="position: relative;">
							<input type="file" name="file" multiple style="opacity: 0; -moz-opacity:0; -webkit-opacity: 0; filter: alpha(opacity = 0); width: 100%; height: 100%;"/>
						</div>
                    </form>
                                  <!-- Blueimp Upload-->      
                                  <form id="fileupload" action="//jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">
                                      <!-- Redirect browsers with JavaScript disabled to the origin page -->
                                      <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
                                      <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
                                      <div class="fileupload-buttonbar">
                                          <div class="fileupload-buttons">
                                              <!-- The fileinput-button span is used to style the file input field as button -->
                                              <span class="fileinput-button">
                                                  <span>Add files...</span>
                                                  <input type="file" name="files[]" multiple>
                                              </span>
                                              <button type="submit" class="start">Start upload</button>
                                              <button type="reset" class="cancel">Cancel upload</button>
                                              <button type="button" class="delete">Delete</button>
                                              <input type="checkbox" class="toggle">
                                              <!-- The global file processing state -->
                                              <span class="fileupload-process"></span>
                                          </div>
                                          <!-- The global progress state -->
                                          <div class="fileupload-progress fade" style="display:none">
                                              <!-- The global progress bar -->
                                              <div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
                                              <!-- The extended global progress state -->
                                              <div class="progress-extended">&nbsp;</div>
                                          </div>
                                      </div>
                                      <!-- The table listing the files available for upload/download -->
                                      <table role="presentation"><tbody class="files"></tbody></table>
                                  </form>    
                                  
                                  <!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress"></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="start" disabled>Start</button>
            {% } %}
            {% if (!i) { %}
                <button class="cancel">Cancel</button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
            </p>
            {% if (file.error) { %}
                <div><span class="error">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            <button class="delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>Delete</button>
            <input type="checkbox" name="delete" value="1" class="toggle">
        </td>
    </tr>
{% } %}
</script>
                                  
            <!-- Blueimp Upload-->                            
                                        
					</div>
				<div id="complete" class="hideCls">
					<ul id="content_1" class="pics completed-upload scroll-area">
						<div class="first-element"></div>
					</ul>
					<a class="black_btn_skin f-left" href="javascript:;"
						onclick="clearUploadedMedia();">clear</a>
				</div>
			</div>
		</div>
	</div>
	<!-- Ads Section -->
    <?php include('right_advertising.phtml'); ?>
    <!-- End Ads Section -->

	<!-- Bottom Ads -->
    <?php include('bottom_advertising.phtml'); ?>
    <!-- End Bottom Ads -->
</div>