<?php if ($this->enableAdvertising) : ?>
<div class="span3 right-ads ">
    <section id="ad">
        <div class="adbox">Your <br>Advertisement <br>space </div>
        <div class="adbox">Your <br>Advertisement <br>space </div>
        <div class="adbox-port">Your <br>Advertisement <br>space </div>
        <div class="adbox-port">Your <br>Advertisement <br>space </div>
    </section>
</div>
<?php endif; ?>