<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php if ($this->enableAdvertising) : ?>
<div class="span3 right-ads " style="z-index: -1;">
<!--    <section id="ad" class="right-ads-section" style="display: none;">
       	Loading...
    </section>-->
    <section class="right-ads-section-1">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- memreas_responsive_side_bar_ad -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2182144607113281"
     data-ad-slot="9363121856"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
    </section>

    
</div>
<?php endif; ?>