<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php if ($this->enableAdvertising) : ?>
<div class="span3 right-ads ">
<!--    <section id="ad" class="right-ads-section" style="display: none;">
       	Loading...
    </section>-->
    <section class="right-ads-section-1">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

            <!-- memreas_side_bar_ad -->

            <ins class="adsbygoogle"
                 style="display:inline-block;width:300px;height:600px"
                 data-adtest="on" data-ad-client="ca-pub-2182144607113281"
                 data-ad-slot="7903631451"></ins>
            <script type="text/javascript">
                //google_adtest="on";
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
    </section>

    
</div>
<?php endif; ?>