<div  id="search-result" class="span11 tabcontent-detail" style="display: none;">
    <div  class="<?php echo ($this->enableAdvertising) ? 'span9' : 'span11';?>">
         <div class="results">over <span id="search-count">300</span> results found.</div>
        <ul class="personresults scrollClass">
          
        </ul>
        
    </div>
    <!-- Ads Section -->
    <?php include('right_advertising.phtml'); ?>
    <!-- End Ads Section -->

    <!-- Bottom Ads -->
    <?php include('bottom_advertising.phtml'); ?>
    <!-- End Bottom Ads -->
</div>