<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<div  id="search-result" class="span11 tabcontent-detail" style="display: none;">

     <div  class="<?php echo ($this->enableAdvertising) ? 'span9' : 'span11';?>">
         <div class="results">Results found:  <span id="search-count"></span>.
		 <div id="linkpaginations">
		 	
		 </div>
		<!-- <button class="btn-event-p"><<</button><button class="btn-event-n">>></button>-->
         </div>

        <ul class="personresults">

        </ul>

    </div>
    <!-- Ads Section -->
    <?php include('right_advertising.phtml'); ?>
    <!-- End Ads Section -->

    <!-- Bottom Ads -->
    <?php include('bottom_advertising.phtml'); ?>
    <!-- End Bottom Ads -->
</div>
