<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<div class="akordeon-item expanded buycredit-order-init">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Payment Method
            </div>
        </div>
    </div>
    <div class="akordeon-item-body"  style="padding-bottom: 10px;">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <ul class="share_memreas_details buycredit-payment preload-null">
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-card-1" name="radio-4-set" class="regular-radio" />
                            <label for="subscription-plan-1"></label>Card A | xxxxxxxxxxxx7576 01/2016</label>
                    </li>
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-card-2" name="radio-4-set" class="regular-radio" />
                            <label for="subscription-plan-2"></label>Card A | xxxxxxxxxxxx8547 06/2016</label>
                    </li>
                </ul>
                <div style="clear: both;"></div>
                <div class="text-center" style="margin-bottom:20px;"> <a class="black_btn_skin" href="javascript:;" onclick="buycredit_addCardPopup();" style="margin-top: 20px; display: inline-block;">Add</a>
                <!-- <a class="black_btn_skin buycredit-card-functions hide-onload" href="javascript:;" onclick="buycredit_removeCard();" style="margin-top: 20px; display: inline-block;">Remove</a> -->
                <a class="black_btn_skin" href="javascript:;" onclick="activeAkordeon('buycredit-order-tab', fill_account_detail);" style="margin-top: 20px; display: inline-block;">Next</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item buycredit-order-tab">
    <div class="akordeon-item-head buycredit-order">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Order detail
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="share_memreas_details buycredit-form">
                <li>
                    <label class="textfield_names" style="min-width: 50px;">Name :</label>
                    <label class="textfield_names" style="margin-left: 10px; min-width: 50px; width: 300px; color:#F5FF00;" id="credit-account-name">John Meah</label>
                </li>
                <li>
                    <label class="textfield_names" style="min-width: 50px;">Balance :</label>
                    <label class="textfield_names" style="margin-left: 10px; min-width: 50px; width: 300px; color:#F5FF00;" id="credit-account-balance">$50.00</label>
                </li>
               <li>
                    <label class="textfield_names"style="min-width: 50px;">Amount to add :</label>
                    <div class="styled-select" style="width: 72%; float: left;  min-width: 50px; margin: 0 0 0 10px;;margin-bottom:20px;">
                        <select id="credit-amount">
                            <option value="10">$10</option>
                            <option value="15">$15</option>
                            <option value="20">$20</option>
                        </select>
                    </div>
                </li>
            </ul>
            <div style="clear: both;"></div>
            <div style="text-align: center;" class="credit-message-order hide-onload">Thank you! You will receive an email confirmation shortly</div>
            <div class="text-center" style="text-align: center;"><a class="black_btn_skin" href="javascript:;" onclick="buycredit_confirmAmount();" style="margin-top: 20px; display: inline-block;">Ok</a>
            <a class="black_btn_skin" href="javascript:;" onclick="activeAkordeon('buycredit-order-init', false);" style="margin-top: 20px; display: inline-block;">Cancel</a>
            </div>
        </div>
    </div>
</div>

<div id="popup-addcard-buycredit-payment" class="popups" >
    <a id="popup-addcard-buycredit-paymentClose" onClick="disablePopup('popup-addcard-buycredit-payment');" class='popupClose'>x</a>
    <h2>Add new card</h2>
    <ul id="content_1" class="scrollpopup creditAddCardForm add_card_buy_credit">
        <li>
            <label class="textfield_names">First name*</label>
            <input name="input" type="text" id="addcard_fname" class="field-txtfield" value="first name" default="first name" onBlur="if(!/\S/.test(this.value)){this.value=this.defaultValue; $(this).css('color', '#a0a0a0');}" onFocus="if(this.value == 'first name'){this.value = ''; $(this).css('color', '#000')}"/>
        </li>
        <li>
            <label class="textfield_names">Last name*</label>
            <input name="input" type="text" id="addcard_lname" class="field-txtfield" value="last name" default="last name" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'last name'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
         <li>
            <label class="textfield_names">Address 1*</label>
            <input name="input" type="text" id="addcard_address1" class="field-txtfield" value="Address line 1" default="Address line 1" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'Address line 1'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
        <li>
            <label class="textfield_names">Address 2</label>
            <input name="input" type="text" id="addcard_address2" class="field-txtfield" value="Address line 2" default="Address line 2" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'Address line 2'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
        <li>
            <label class="textfield_names">City*</label>
            <input name="input" type="text" id="addcard_city" class="field-txtfield" value="City" default="City" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'City'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
        <li>
            <label class="textfield_names">State*</label>
            <input name="input" type="text" id="addcard_state" class="field-txtfield" value="State" default="State" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'State'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
        <li>
            <label class="textfield_names">Zip*</label>
            <input name="input" type="text" id="addcard_zip" class="field-txtfield" value="Zip" default="Zip" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'Zip'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
        <li>
            <label class="textfield_names">Card type*</label>
            <select name="addcard_cctype" id="addcard_cctype" class="field-txtfield">
                <option value="">-Choose-</option>
                <option value="visa">Visa Card</option>
                <option value="master">Master Card</option>
                <option value="discover">Discover Card</option>
                <option value="amex">Amex Card</option>
            </select>
        </li>
        <li>
            <label class="textfield_names">Card no.*</label>
            <input name="input" type="text" id="addcard_ccnum" class="field-txtfield" value="Card number" default="Card number" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'Card number'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
        <li>
            <label class="textfield_names">Exp mon.*</label>
            <select name="addcard_expmonth" id="addcard_expmonth" class="field-txtfield">
                <option value="">-Choose-</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
        </li>
        <li>
            <label class="textfield_names">Exp year*</label>
            <select name="addcard_expyear" id="addcard_expyear" class="field-txtfield">
                <option value="">-Choose-</option>
                <option value="2016">2016</option>
                <option value="2017">2017</option>
                <option value="2018">2018</option>
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
                <option value="2023">2023</option>
                <option value="2024">2024</option>
                <option value="2025">2025</option>
                <option value="2026">2026</option>
            </select>
        </li>
        <li>
            <label class="textfield_names">Card CVC*</label>
            <input name="input" type="text" id="addcard_ccv" class="field-txtfield" value="Card code" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'Card code'){ this.value = ''; $(this).css('color', '#000'); }"/>
        </li>
    </ul>
    <a class="black_btn_skin f-left" id="btn-buycredit-add-card" href="javascript:;">ok</a> <a class="black_btn_skin f-right" href="javascript:disablePopup('popup-addcard-buycredit-payment');">cancel</a>
</div>
<div id="bgpopup-addcard-buycredit-payment" class="backgroundPopup"></div>