<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<style type="text/css">
    table{width: 100%; margin-bottom: 20px;}
     table thead{background: #000; padding: 10px;}
     table thead  th{font-weight: bold;}
     table tbody tr td {border:1px solid #fff; text-align: center}
     
</style>
<div class="akordeon-item expanded">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
               DMCA
            </div>
        </div>
    </div>
    <div class="akordeon-item-body"  style="padding-bottom: 10px;">
        <div class="akordeon-item-content">
            
            <table>
                <thead>
                    <th>Counter Claim</th>
                    <th>report date</th>
                    <th>media thumbnail</th>
                    <th>checkbox</th>
                    <th>Date</th>
                     <th>thumbnail</th>
            </thead>
            <tbody>
                <tr>
                    <td>Counter Claim text</td>
                    <td>26 FEB 2016</td>
                    <td><img src="/memreas/img/1.jpg" width="80" /></td>
                    <td> <input id="morepage_ckb_sellmedia" class="css-checkbox" type="checkbox" />
                    <label id="lbl-sellmedia" for="morepage_ckb_sellmedia" name="demo_lbl_6" class="css-label margin-none"></label></td>
                    <td>26 FEB 2016</td>
                    <td><img src="/memreas/img/1.jpg" width="80" /></td>
                </tr>
            </tbody>
            </table>
            <ul id="content_1" class="share_memreas_details">
               
                <li>
                    <label class="textfield_names">Full Name :</label>
                    <input name="input" type="text" id="morepage_eventDate" class="share-txtfield date-picker"  value="" placeholder="Full Name" />
                </li>
                <li>
                    <label class="textfield_names">Address :</label>
                    <input name="input3" type="text" id="morepage_eventLocation" class="share-txtfield" value="" placeholder="Address" />
                </li>
                
                <li>
                    <label class="textfield_names">Phone number :</label>
                    <input name="input3" type="text" id="morepage_eventLocation" class="share-txtfield" value="" placeholder="Phone no." />
                </li>
                <li>
                     <label class="textfield_names">Email address :</label>
                     <input name="input3" type="text" id="morepage_eventLocation" class="share-txtfield" value="" placeholder="Email"/>
                   
                </li>
                
            </ul>
            <div style="clear: both; margin-top: 10px; margin-bottom: 10px; padding-top: 10px;"></div>
            <div class="btn">

            <a class="black_btn_skin" href="javascript:;" onclick="morepage_saveEvent(false);">ok</a>
            <a class="black_btn_skin" href="javascript:;">cancel</a>
            </div>
        </div>
    </div>
</div>



<div id="more_dlg_locationmap" class="popups2">
    <a id="more_btn_locationmap_close" onClick="javascript:more_closeGoogleMap(false);" class='popupClose'>x</a>
    <h2>location</h2>
    <a id="more_btn_locationmap_ok" class="black_btn_skin btn_locationmap_ok" href="javascript:more_closeGoogleMap(true);">OK</a>
    <input id="more_txt_locationmap_address" class="txt_locationmap_address" name="input" type="text" />
    <div class="clear"></div>
    <div id="more_div_locationmap_maparea" class="map_box"></div>
</div>
<div id="more_div_locationmap_back" class="backgroundPopup"></div>