<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>

<div class="akordeon-item expanded">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
               DMCA
            </div>
        </div>
    </div>
    <div class="akordeon-item-body"  style="padding-bottom: 10px;">
        <div class="akordeon-item-content">
            
            <table class="dmca-table-data" style="width: 100%;">
                <thead>
                    <th>Violation Reported</th>
                    <th>Media Id</th>
                    <th>media image</th>
                    <th>report counter claim</th>
                    <th>counter claim reported</th>
                     <th>status</th>
              </thead>
            <tbody>
               <!-- Dynamic Upload here Data -->
               
            
            </tbody>
            </table>
            
        </div>
    </div>
</div>



<div id="dmca-check-box" class="popups">
    <a id="popupReportMediaClose" onClick="disablePopup('dmca-check-box');" class='popupClose'>x</a>
        <h2>Your Counter Notice must contain the following</h2>
        
        <p>By submission of my counter claim I agree to provide my email address to the reporter and will resolve this violation without any further involvement from memreas.</p>
</div>


<div id="dmca-form-box" class="popups2">
    <a id="popupReportMediaClose" onClick="disablePopup('dmca-form-box');" class='popupClose'>x</a>
    <form style="margin-bottom: 20px;">
                
        <h2 class="dmcaTitle" style="width: 100%;">dmca violation - counter claim </h2>
            <ul id="content_1" class="share_memreas_details">
               
                <li>
                    <label class="textfield_names">Full Name :</label>
                    <input name="input" type="text" id="morepage_eventDate" class="share-txtfield"  value="" placeholder="Full Name" />
                </li>
                <li>
                    <label class="textfield_names">Address :</label>
                    <input name="input3" type="text" id="morepage_eventLocation" class="share-txtfield" value="" placeholder="Address" />
                </li>
                
                
                
                <li>
                    <label class="textfield_names">Phone number :</label>
                    <input name="input3" type="text" id="morepage_eventLocation" class="share-txtfield" value="" placeholder="Phone no." />
                </li>
                <li>
                     <label class="textfield_names">Email address :</label>
                     <input name="input3" type="text" id="morepage_eventLocation" class="share-txtfield" value="" placeholder="Email"/>
                   
                </li>
                
                <li>
                    <label class="textfield_names">Signed Written Communication:</label>
                    <a class="black_btn_skin f-center change-profile-btn fileupload-dmca" href="javascript:;">Choose file</a>
                    <span class="dmca-file-location"><a href="http://www.fememreas.com/images/" target="_blank" style="color:#fff; padding-left: 5px;">http://www.fememreas.com/images/</a></span>
                    <span class="dmca-file-info"><a href="javascript:," target="_blank" class="info-dcma"><img src="/memreas/img/info.png" /></a></span>
                </li>
                
                <li>
                    
                    <input id="morepage_isselfdestruct" class="css-checkbox" type="checkbox">
                    <label for="morepage_isselfdestruct" name="demo_lbl_5" class="css-label margin-none" style="text-align: left; margin-left: 90px !important; ">by submission of my counter claim and memreas terms and conditions i agree to provide my email address to the reporter and will resolve this violation without any further involvement from memreas.</label>
                <div style="clear: both;"></div>
                </li>
                
            </ul>
            <div style="clear: both; margin-top: 10px; margin-bottom: 10px; padding-top: 10px;"></div>
            <div class="btn">

            <a class="black_btn_skin" href="javascript:;" onclick="">ok</a>
            <a class="black_btn_skin" href="javascript:;">cancel</a>
            </div>
             </form>    
</div>



    