<?php

/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
use Application\Model\MemreasConstants;
?>

<div class="akordeon-item expanded">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">DMCA</div>
        </div>
    </div>
    <div class="akordeon-item-body" style="padding-bottom: 10px;">
        <div class="akordeon-item-content">

            <table class="dmca-table-data" style="width: 100%;">
                <thead>
                <th>Violation Reported</th>
                <th>Media Id</th>
                <th>media image</th>
                <th>report counter claim</th>
                <th>counter claim reported</th>
                <th>status</th>
                </thead>
                <tbody>
                    <!-- Dynamic Upload here Data -->


                </tbody>
            </table>

        </div>
    </div>
</div>



<div id="dmca-check-box" class="popups">
    <a id="popupReportMediaClose" onClick="disablePopup('dmca-check-box');"
       class='popupClose'>x</a>
    <h2>Your Counter Notice must contain the following and be in PDF or
        JPEG digital formats</h2>
    <p>
        Signed and written counter notice must contain the following: <br>Identification
        of the material removed and the location of the material prior to
        removal. <br>A statement under penalty of perjury that the user has a
        good faith belief that the material was removed as a result of a
        mistake or misidentification. <br>Contain your name, address, and
        phone number <br>And a statement that the you will accept service of
        process and consents to the jurisdiction of Federal District Court
    </p>
</div>


<div id="dmca-form-box" class="popups2">
    <a id="popupReportMediaClose" onClick="disablePopup('dmca-form-box');"
       class='popupClose'>x</a>

    <form name="dmcaFileUploadForm" id="dmcaFileUploadForm" class="dmcaFileUploadForm"
          enctype="multipart/form-data"
          action="https://<?php echo MemreasConstants::S3BUCKET; ?>.s3.amazonaws.com/"
          method="post" form-type="dmca-upload" style="display: none;">

        <input type="hidden" name="key" value="">
        <input type="hidden" name="Content-Type" value="">
        <input type="hidden" name="acl" value="">
        <input type="hidden" name="success_action_status" value="">
        <input type="hidden" name="policy" value="">
        <input type="hidden" name="x-amz-algorithm" value="">
        <input type="hidden" name="x-amz-credential" value="">
        <input type="hidden" name="x-amz-date" value="">
        <input type="hidden" name="x-amz-expires" value="">
        <input type="hidden" name="x-amz-signature" value="">
        <input type="hidden" name="x-amz-server-side-encryption" value="AES256">
        <input type="file" name="file" id="file" multiple="">
    </form>

    <form id="dmcaReportCounterClaimForm" style="margin-bottom: 20px;">

        <h2 class="dmcaTitle" style="width: 100%;">dmca violation - counter
            claim</h2>
        <ul id="content_1" class="share_memreas_detaill_dcma">

            <li><label class="textfield_names">Full Name :</label> <input
                    name="copyright_owner_name" type="text" id="copyright_owner_name"
                    class="share-txtfield" value="" placeholder="Contact Owner Name" />
            </li>
            <li><label class="textfield_names">Address :</label> <input
                    name="copyright_owner_address" type="text"
                    id="copyright_owner_address" class="share-txtfield" value=""
                    placeholder="Address" />
            </li>
            
            <li><label class="textfield_names">Counter Claim url :</label> <input
                    name="counter_claim_url" type="text"
                    id="counter_claim_url" class="share-txtfield" value=""
                    placeholder="Counter Claim url" />
            </li>



            <li><label class="textfield_names">Phone number :</label> <input
                    name="counter_claim_phone_number" type="text"
                    id="counter_claim_phone_number" class="share-txtfield" value=""
                    placeholder="Phone no." /></li>
            <!-- remove - use email on file-->
            <li><label class="textfield_names">media Id</label> 
                <input
                    type="text" name="media_id" id="media_id" class="share-txtfield" readonly />
                <input type="hidden" name="violation_id" id="violation_id"  />
                <input name="copyright_owner_email_address" type="hidden" id="copyright_owner_email_address" class="share-txtfield" value="" placeholder="Email" readonly/>
            </li>

            <li><label class="textfield_names">Signed Written Communication:</label>
                <!--<a class="black_btn_skin f-center change-profile-btn fileupload-dmca" href="javascript:;">Choose file</a>-->
                <div class="dmca-upload-progress" style=" vertical-align: top;">
                    <a class="black_btn_skin f-left dmca-file-btn" href="javascript:;" onclick="$('.dmcaFileUploadForm').find('input[type=file]').click();">Choose file</a>
                </div>
            </li>

            <li>
            </li>

        </ul>
        <div class="clearfix"></div>
       <div style="clear: both; margin-bottom: 20px;"> <input id="dmca_term_condition" class="css-checkbox" type="checkbox"> <label for="dmca_term_condition"
                       name="demo_lbl_5" class="css-label margin-none"
                       style="text-align: left; height: auto;" id="dmca_term_condition_label">by
                    submission of my counter claim and memreas terms and conditions i
                    agree to provide my email address to the reporter and will resolve
                    this violation without any further involvement from memreas.</label>
                </div>
        <div style="clear: both; margin-top: 10px; margin-bottom: 10px; padding-top: 10px;"></div>
        <div style="clear: both;"></div>
        <div class="btn">

            <a class="black_btn_skin" href="javascript:reportCounterClaimForm();"
               onclick="">ok</a> <a class="black_btn_skin" href="javascript:;"
               onclick="disablePopup('dmca-form-box');"  class='popupClose'>cancel</a>
        </div>
    </form>
</div>
<div id="bgdmca-form-box" class="backgroundPopup"></div>

<div id="popupComfirmDmca" class="popups">
    <a id="popupBuyMediaConfirmationClose" onClick="disablePopup('popupComfirmDmca');" class='popupClose'>x</a>
    <h2>Dmca Report</h2>
    <ul id="content_1" class="give-message-form buying-media-detail">
        <li>
            <label class="margin-none" style="line-height: 21px;" >
                We've received your dcma report violation and have taken steps to notify the user who posted the media and remove the media from our site through our automated processes. Your violation id number is: violation id.
                <br><br>
                Thanks,<br>
                memreas team<br>
            </label>
        </li>
    </ul>
    <div class="clear"></div>
    <a class="black_btn_skin f-right" href="javascript:disablePopup('popupComfirmDmca');">close</a>
</div>
<div id="bgpopupComfirmDmca" class="backgroundPopup"></div>



