<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<div class="akordeon-item">
    <div class="akordeon-item-head manage-friends-tab">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Your friends list
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <ul id="content_1" class="share_friends_contents manage-friends">
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	          </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
      	        <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
                <li>
      	          <figure class="pro-pics2"><img src="img/profile-pic.jpg" alt=""></figure>
      	          <aside class="pro-pic_names2">Friend Name</aside>
    	        </li>
    	       </ul>
                <div style="clear: both;"></div>
                <a class="black_btn_skin card-functions" href="javascript:;" onclick="manageF_removeFriends(false);" style="margin-top: 20px; display: inline-block;">Remove</a>
                <a class="black_btn_skin card-functions" href="javascript:;" onclick="manageF_resetChooseFriends();" style="margin-top: 20px; display: inline-block;">Cancel</a>
            </div>
        </div>
    </div>
</div>