<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                feedback
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="share_memreas_details">
                <li>
                    <label class="textfield_names">name :</label>
                    <input name="name_feedback" type="text" class="share-txtfield" value="your name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'your name')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">email :</label>
                    <input name="email_feedback" type="text" class="share-txtfield" value="your email" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'your email')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">message :</label>
                    <textarea name="message_feedback" cols="" rows="" class="share-txtfield"></textarea>
                    <a class="black_btn_skin f-center" href="javascript:;" style="margin-left: 30% !important;" onclick="submitFeedback();">ok</a>
                    <a class="black_btn_skin" href="#">cancel</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="akordeon-item expanded">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                usage basics
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.</p>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                faqs
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend. Vestibulum semper sollicitudin dui, quis consequat elit pellentesque non. Nam aliquet consectetur sem, in accumsan nisl eleifend non. Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu.</p>
            <p>Integer at nisl et lacus pellentesque dictum. Phasellus ullamcorper mattis quam, id facilisis orci ornare eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultrices pretium eleifend.</p>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head member-guidelines-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                member guidelines
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="scrollpopup member-guidelines">
                <?php include 'help/member-guideline.phtml'; ?>
            </ul>
        </div>
    </div>
</div>
<div class="akordeon-item expanded">
    <div class="akordeon-item-head privacy-policy-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                privacy policy
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="scrollpopup privacy-policy">
                <?php include 'help/privacy-policy.phtml'; ?>
            </ul>
        </div>
    </div>
</div>
<div class="akordeon-item expanded">
    <div class="akordeon-item-head dmca-policy-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                DMCA Policy
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="scrollpopup dmca-policy">
                <?php include 'help/dmca-policy.phtml'; ?>
            </ul>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head terms-service-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                terms of service
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="scrollpopup terms-service">
                <?php include 'help/terms-service.phtml'; ?>
            </ul>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                version:
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <p><strong>Application Version: </strong>0.987</p>
        </div>
    </div>
</div>