<div class="akordeon-item expanded">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Wifi Settings
            </div>
        </div>
    </div>
    <div class="akordeon-item-body"  style="padding-bottom: 10px;">
        <div class="akordeon-item-content">
            <input id="demo_box_1" class="css-checkbox" type="checkbox" checked="checked"/>
            <label for="demo_box_1" name="demo_lbl_4" class="css-label margin-none" >Queue uploads and downloads only when on Wifi (default)</label>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Upload / Download Options
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="option" >
                <li>
                    <input id="demo_box_2" class="css-checkbox" type="checkbox" checked="checked"/>
                    <label for="demo_box_2" name="demo_lbl_4" class="css-label margin-none" >Download Full Resolution Photos<br><small> Note: not recommended for devices with low disk space</small></label>
                </li>
                <li>
                    <input id="demo_box_3" class="css-checkbox" type="checkbox" checked="checked"/>
                    <label for="demo_box_3" name="demo_lbl_4" class="css-label margin-none" >Auto Upload<br><small> Enable automatic uploads of photos when added to gallery or events (default)</small></label>
                </li>
            </ul>
        </div>
    </div>
</div>