<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<div class="akordeon-item expanded">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                media
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <label class="label_text2"><input type="radio" id="radio-2-1" name="radio-2-set" class="regular-radio" /><label for="radio-2-1"></label>off</label>
                <label class="label_text2"><input type="radio" id="radio-2-2" name="radio-2-set" class="regular-radio" /><label for="radio-2-2"></label>people I follow</label>
                <label class="label_text2"><input type="radio" id="radio-2-3" name="radio-2-set" class="regular-radio" checked /><label for="radio-2-3"></label>everyone (default)</label>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                like notification
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <label class="label_text2"><input type="radio" id="radio-3-1" name="radio-3-set" class="regular-radio" /><label for="radio-3-1"></label>off</label>
                <label class="label_text2"><input type="radio" id="radio-3-2" name="radio-3-set" class="regular-radio" /><label for="radio-3-2"></label>people I follow</label>
                <label class="label_text2"><input type="radio" id="radio-3-3" name="radio-3-set" class="regular-radio" checked /><label for="radio-3-3"></label>everyone (default)</label>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                comment notification
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <label class="label_text2"><input type="radio" id="radio-4-1" name="radio-4-set" class="regular-radio" /><label for="radio-4-1"></label>off</label>
                <label class="label_text2"><input type="radio" id="radio-4-2" name="radio-4-set" class="regular-radio" /><label for="radio-4-2"></label>people I follow</label>
                <label class="label_text2"><input type="radio" id="radio-4-3" name="radio-4-set" class="regular-radio" checked /><label for="radio-4-3"></label>everyone (default)</label>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                event requests
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <label class="label_text2"><input type="radio" id="radio-5-1" name="radio-5-set" class="regular-radio" /><label for="radio-5-1"></label>off</label>
                <label class="label_text2"><input type="radio" id="radio-5-2" name="radio-5-set" class="regular-radio" /><label for="radio-5-2"></label>friends</label>
                <label class="label_text2"><input type="radio" id="radio-5-3" name="radio-5-set" class="regular-radio" checked /><label for="radio-5-3"></label>everyone (default)</label>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                friend requests
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <label class="label_text2"><input type="radio" id="radio-6-1" name="radio-6-set" class="regular-radio" /><label for="radio-6-1"></label>off</label>
                <label class="label_text2"><input type="radio" id="radio-6-2" name="radio-6-set" class="regular-radio" /><label for="radio-6-2"></label>friends</label>
                <label class="label_text2"><input type="radio" id="radio-6-3" name="radio-6-set" class="regular-radio" checked /><label for="radio-6-3"></label>everyone (default)</label>
            </div>
        </div>
    </div>
</div>