<ul class="share_memreas_details sell_media_form">
    <li>
        <label class="textfield_names">Username</label>
        <input name="input" type="text" id="sell-media-username" class="" value="username" default="username" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'username')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">Stripe email</label>
        <input name="input" type="text" id="sell-media-semail" class="" value="Stripe email" default="Stripe email" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Stripe email')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">First name*</label>
        <input name="input" type="text" id="sell-media-fname" class="" value="first name" default="first name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'first name')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">Last name*</label>
        <input name="input" type="text" id="sell-media-lname" class="" value="first name" default="first name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'first name')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">Address 1*</label>
        <input name="input" type="text" id="sell-media-address1" class="" value="Address line 1" default="Address line 1" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Address line 1')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">Address 2</label>
        <input name="input" type="text" id="sell-media-address2" class="" value="Address line 2" default="Address line 2" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Address line 2')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">City*</label>
        <input name="input" type="text" id="sell-media-city" class="" value="City" default="City" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'City')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">State*</label>
        <input name="input" type="text" id="sell-media-state" class="" value="State" default="State" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'State')this.value = '';" />
    </li>
    <li>
        <label class="textfield_names">Zip*</label>
        <input name="input" type="text" id="sell-media-zip" class="" value="Zip" default="Zip" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Zip')this.value = '';" />
    </li>
    <li class="add-seller-message hide-onload">
        <p></p>
    </li>
</ul>
<div class="clear"></div>
<div class="btn">

 <a class="black_btn_skin f-left" href="javascript:;" onclick="register_sell_media();">ok</a>
 <a class="black_btn_skin f-left" href="javascript:;" onclick="register_sell_media();">cancel</a>
</div>