<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>


<div id="fromSellInfo1">
<div class="akordeon-item sell-media-info-tab expanded">
	<div class="akordeon-item-head subscription-payment-plans">
		<div class="akordeon-item-head-container">
			<div class="akordeon-heading">Seller information</div>
		</div>
	</div>
    
    <div class="selleerdata">
    <h2>Seller information</h2>
                                <label class="textfield_names susername sellertxt">Username: <?php echo $_SESSION['username']; ?></label>
                                <label class="textfield_names semail sellertxt">Email: <?php echo $_SESSION['email']; ?></label>
                                <div class="clearfix"></div>
 </div>
    <div class="clearfix"></div>
	<div class="akordeon-item-body" style="padding-bottom: 10px;">
		<div class="akordeon-item-content">
			<div class="button-holder">
                            
                            
				<form name="sell_media_frm"   id="fromSellInfo">
				<ul class="share_memreas_details sell_media_form" id="sellerform">
					<li><label class="textfield_names">username*</label> <input
						name="sell-media-username" type="text" class="more-input"
						value="<?php echo $_SESSION['username']; ?>"
						onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
						onFocus="if(this.value == 'email')this.value = '';" readonly /></li>
					<li><label class="textfield_names">email address*</label> <input
						name="sell-media-email" type="text" class="more-input"
						value="<?php echo $_SESSION['email']; ?>"
						onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
						onFocus="if(this.value == 'email')this.value = '';" readonly /></li>
					<li><label class="textfield_names">first name*</label> <input
						name="input" type="text" id="sell-media-fname" class=""
						value="first name" default="first name"
						onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'first name'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li><label class="textfield_names">last name*</label> <input
						name="input" type="text" id="sell-media-lname" class=""
						value="last name" default="first name"
						onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'last name'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li><label class="textfield_names">date of birth*</label> <input
						name="input" type="text" id="sell-media-dob" class=""
						value="yyyy-mm-dd" default="yyyy-mm-dd"
						onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'yyyy-mm-dd'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li><label class="textfield_names">address 1*</label> <input
						name="input" type="text" id="sell-media-address1" class=""
						value="Address line 1" default="Address line 1"
						onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'Address line 1'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li><label class="textfield_names">address 2</label> <input
						name="input" type="text" id="sell-media-address2" class=""
						value="Address line 2" default="Address line 2"
						onBlur="if(!/\S/.test(this.value)){ this.value=''; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'Address line 2'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li><label class="textfield_names">city*</label> <input
						name="input" type="text" id="sell-media-city" class=""
						value="City" default="City"
						onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'City'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li><label class="textfield_names">state*</label> <input
						name="input" type="text" id="sell-media-state" class=""
						value="State" default="State"
						onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'State'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li><label class="textfield_names">zip*</label> <input name="input"
						type="text" id="sell-media-zip" class="" value="Zip" default="Zip"
						onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }"
						onFocus="if(this.value == 'Zip'){ this.value = ''; $(this).css('color', '#000'); }" />
					</li>
					<li class="add-seller-message hide-onload">
						<p></p>
					</li>
				</ul>
				</form>
				<div class="btn sellmedia-btn-group">
					<a class="black_btn_skin f-left" href="javascript:;"
						onclick="sellMediaStep2();">Next</a> <a
						class="black_btn_skin f-left" href="javascript:;"
						onclick="resetSellMedia();">Clear</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="akordeon-item sell-media-payout-tab expanded">
	<div class="akordeon-item-head subscription-payment-plans">
		<div class="akordeon-item-head-container">
			<div class="akordeon-heading">financial information</div>
		</div>
	</div>
	<div class="akordeon-item-body" style="padding-bottom: 10px;">
		<div class="akordeon-item-content">
			<ul class="share_memreas_details sell_media_bank">
				<!--  Production 
                <li>
                    <label class="textfield_names" style="float: none; margin-bottom: 20px;">Social Security or Tax ID Number*</label>
                    <input name="input" type="text" id="sell-media-tax-ssn-ein" class="" value="123456789" default="123456789" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '123456789')this.value = '';" />
                </li>
                <li>
                    <label class="textfield_names" style="float: none; margin-bottom: 20px;">banking institution "i.e. Citibank"*</label>
                    <input name="input" type="text" id="sell-media-bank" class="" value="banking institution" default="banking institution" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'banking institution')this.value = '';" />
                </li>
                <li>
                    <label class="textfield_names" style="float: none; margin-bottom: 20px;">bank routing number (ABA #)*</label>
                    <input name="input" type="text" id="sell-media-bank-routing" class="" value="routing number" default="routing number" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'routing number')this.value = '';" />
                </li>
                <li>
                    <label class="textfield_names" style="float: none; margin-bottom: 20px;">bank account number*</label>
                    <input name="input" type="text" id="sell-media-account-number" class="" value="account number" default="account number" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'account number')this.value = '';" />
                </li>
                 -->
				<!--  Test values -->
				<li><label class="textfield_names"
					style="float: none; margin-bottom: 20px;">Social Security or Tax ID
						Number*</label> <input name="input" type="text"
					id="sell-media-tax-ssn-ein" class="" value="000000000" default=""
					onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
					onFocus="if(this.value == '123456789')this.value = '';" /></li>
				<li><label class="textfield_names"
					style="float: none; margin-bottom: 20px;">banking institution "i.e.
						Citibank"*</label> <input name="input" type="text"
					id="sell-media-bank" class="" value="citibank" default=""
					onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
					onFocus="if(this.value == 'banking institution')this.value = '';" />
				</li>
				<li><label class="textfield_names"
					style="float: none; margin-bottom: 20px;">bank routing number (ABA
						#)*</label> <input name="input" type="text"
					id="sell-media-bank-routing" class="" value="110000000" default=""
					onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
					onFocus="if(this.value == 'routing number')this.value = '';" /></li>
				<li><label class="textfield_names"
					style="float: none; margin-bottom: 20px;">bank account number*</label>
					<input name="input" type="text" id="sell-media-account-number"
					class="" value="000123456789" default=""
					onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
					onFocus="if(this.value == 'account number')this.value = '';" /></li>
				<!--  Test values -->
				<li><input id="register-seller-agree" class="css-checkbox"
					type="checkbox" name="register_seller_agree" /> <label
					for="register-seller-agree" name="demo_lbl_1"
					class="css-label margin-none">by checking this box I agree to
						memreas <a href="javascript:;"
						onclick="popup('popupMarketplaceTerms');">Marketplace Terms of
							Service</a>
				</label></li>
			</ul>
			<div class="btn">
				<a class="black_btn_skin f-left" href="javascript:;"
					onclick="register_sell_media();">Done</a> <a
					class="black_btn_skin f-left" href="javascript:;"
					onclick="resetSellMedia();">cancel</a>
			</div>
		</div>
	</div>
</div></div>
<div id="popupMarketplaceTerms" class="popups">
	<a id="popupMarketplaceTermsClose"
		onClick="disablePopup('popupMarketplaceTerms')"
		class='popupMarketplaceTerms'>x</a>
	<h2>Marketplace Terms of Service</h2>
	<ul id="TermsAndServiceContent" class="popup_legal scrollpopup">
        <?php include 'help/marketplace-terms-service.phtml'; ?>
    </ul>
	<a class="black_btn_skin f-left" href="javascript:;"
		onclick="disablePopup('popupMarketplaceTerms');">ok</a>
</div>
<div id="bgpopupMarketplaceTerms" class="backgroundPopup"></div>
<div class="clear"></div>