<div class="akordeon-item sell-media-info-tab expanded">
    <div class="akordeon-item-head subscription-payment-plans">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Seller information
            </div>
        </div>
    </div>
    <div class="akordeon-item-body"  style="padding-bottom: 10px;">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <form name="sell_media_frm" />
                <ul class="share_memreas_details sell_media_form">
                    <li>
                        <label class="textfield_names">Username*</label>
                        <input name="input" type="text" id="sell-media-username" class="disabled" value="username" default="username" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'username')this.value = '';" readonly />
                    </li>
                    <li>
                        <label class="textfield_names">Stripe email*</label>
                        <input name="input" type="text" id="sell-media-email" class="disabled" value="Stripe email" default="Stripe email" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; }" onFocus="if(this.value == 'Stripe email'){ this.value = ''; }" readonly />
                    </li>
                    <li>
                        <label class="textfield_names">First name*</label>
                        <input name="input" type="text" id="sell-media-fname" class="" value="first name" default="first name" onBlur="if(!/\S/.test(this.value)){ this.value=this.defaultValue; $(this).css('color', '#a0a0a0'); }" onFocus="if(this.value == 'first name'){ this.value = ''; $(this).css('color', '#000'); }" />
                    </li>
                    <li>
                        <label class="textfield_names">Last name*</label>
                        <input name="input" type="text" id="sell-media-lname" class="" value="last name" default="first name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'last name')this.value = '';" />
                    </li>
                    <li>
                        <label class="textfield_names">Address 1*</label>
                        <input name="input" type="text" id="sell-media-address1" class="" value="Address line 1" default="Address line 1" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Address line 1')this.value = '';" />
                    </li>
                    <li>
                        <label class="textfield_names">Address 2</label>
                        <input name="input" type="text" id="sell-media-address2" class="" value="Address line 2" default="Address line 2" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Address line 2')this.value = '';" />
                    </li>
                    <li>
                        <label class="textfield_names">City*</label>
                        <input name="input" type="text" id="sell-media-city" class="" value="City" default="City" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'City')this.value = '';" />
                    </li>
                    <li>
                        <label class="textfield_names">State*</label>
                        <input name="input" type="text" id="sell-media-state" class="" value="State" default="State" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'State')this.value = '';" />
                    </li>
                    <li>
                        <label class="textfield_names">Zip*</label>
                        <input name="input" type="text" id="sell-media-zip" class="" value="Zip" default="Zip" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Zip')this.value = '';" />
                    </li>
                    <li class="add-seller-message hide-onload">
                        <p></p>
                    </li>
                </ul>
                </form>
                <div class="btn">
                    <a class="black_btn_skin f-left" href="javascript:;" onclick="sellMediaStep2();">Next</a>
                    <a class="black_btn_skin f-left" href="javascript:;" onclick="resetSellMedia();">Clear</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item sell-media-payout-tab expanded">
    <div class="akordeon-item-head subscription-payment-plans">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                financial information
            </div>
        </div>
    </div>
    <div class="akordeon-item-body"  style="padding-bottom: 10px;">
        <div class="akordeon-item-content">
            <ul class="share_memreas_details sell_media_bank">
                <li>
                    <label class="textfield_names" style="float: none; margin-bottom: 20px;">banking institution "i.e. Citibank"*</label>
                    <input name="input" type="text" id="sell-media-bank" class="" value="banking institution" default="banking institution" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'banking institution')this.value = '';" />
                </li>
                <li>
                    <label class="textfield_names" style="float: none; margin-bottom: 20px;">bank routing number (ABA #)*</label>
                    <input name="input" type="text" id="sell-media-bank-routing" class="" value="routing number" default="routing number" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'routing number')this.value = '';" />
                </li>
                <li>
                    <label class="textfield_names" style="float: none; margin-bottom: 20px;">bank account number*</label>
                    <input name="input" type="text" id="sell-media-account-number" class="" value="account number" default="account number" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'account number')this.value = '';" />
                </li>
                <li>
                    <input id="register-seller-agree" class="css-checkbox" type="checkbox" name="register_seller_agree"/>
                    <label for="register-seller-agree" name="demo_lbl_1" class="css-label margin-none" >Check this box to confirm memreas <a href="javascript:;" onclick="popup('popupMarketplaceTerms');">Marketplace Terms of Service</a></label>
                </li>
            </ul>
            <div class="btn">
             <a class="black_btn_skin f-left" href="javascript:;" onclick="register_sell_media();">Done</a>
             <a class="black_btn_skin f-left" href="javascript:;" onclick="resetSellMedia();">cancel</a>
            </div>
        </div>
    </div>
</div>
<div id="popupMarketplaceTerms" class="popups">
  <a id="popupMarketplaceTermsClose" onClick="disablePopup('popupMarketplaceTerms')" class='popupMarketplaceTerms'>x</a>
    <h2>Marketplace Terms of Service</h2>
    <ul id="TermsAndServiceContent" class="popup_legal scrollpopup">
        <?php include 'help/marketplace-terms-service.phtml'; ?>
    </ul>
    <a class="black_btn_skin f-left" href="javascript:;" onclick="disablePopup('popupMarketplaceTerms');">ok</a>
</div>
<div id="bgpopupMarketplaceTerms" class="backgroundPopup"></div>
<div class="clear"></div>