<div class="akordeon-item subscription-payment-plans-tab expanded">
    <div class="akordeon-item-head">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Plans
            </div>
        </div>
    </div>
    <div class="akordeon-item-body"  style="padding-bottom: 10px;">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <div class="customer-active-plans">
                    <h3>Your current active plans : </h3>
                    <div class="list-plans">
                        <p>10 GB Monthly</p>
                        <p>20 GB Monthly</p>
                        <p>30 GB Monthly</p>
                        <p>40 GB Monthly</p>
                    </div>
                </div>
                <ul class="share_memreas_details subscription-plans preload-null">
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-plan-1" name="radio-4-set" class="regular-radio" /><label for="subscription-plan-1"></label>Plan A | Description for plan A - $12</label>
                    </li>
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-plan-2" name="radio-4-set" class="regular-radio" /><label for="subscription-plan-2"></label>Plan B | Description for plan B - $24 </label>
                    </li>
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-plan-3" name="radio-4-set" class="regular-radio" checked /><label for="subscription-plan-3"></label>Plan C | Description for plan C - $48</label>
                    </li>
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-plan-4" name="radio-4-set" class="regular-radio" checked /><label for="subscription-plan-4"></label>Plan D | Description for plan C - $58</label>
                    </li>
                </ul>
                <div style="clear: both;"></div>
                <a class="black_btn_skin" href="javascript:;" onclick="activeAkordeon('subscription-payment-method-tab', subscription_step2);" style="margin-top: 20px; display: inline-block;">Next</a>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item subscription-payment-method-tab">
    <div class="akordeon-item-head subscription-payment-method">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Choose payment method
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <div class="button-holder">
                <ul class="share_memreas_details subscription-payment preload-null">
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-card-1" name="radio-4-set" class="regular-radio" />
                            <label for="subscription-plan-1"></label>Card A | xxxxxxxxxxxx7576 01/2016</label>
                    </li>
                    <li>
                        <label class="label_text2"><input type="radio" id="subscription-card-2" name="radio-4-set" class="regular-radio" />
                            <label for="subscription-plan-2"></label>Card A | xxxxxxxxxxxx8547 06/2016</label>
                    </li>
                </ul>
                <div style="clear: both;"></div>
                <a class="black_btn_skin" href="javascript:;" onclick="addCardPopup();" style="margin-top: 20px; display: inline-block;">Add</a>
                <a class="black_btn_skin card-functions hide-onload" href="javascript:;" onclick="removeCard();" style="margin-top: 20px; display: inline-block;">Remove</a>
                <a class="black_btn_skin" href="javascript:;" onclick="activeAkordeon('subscription-order-summary-tab', subscription_step3);" style="margin-top: 20px; display: inline-block;">Next</a>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item subscription-order-summary-tab">
    <div class="akordeon-item-head subscription-order-summary">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Order summany
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="share_memreas_details order-summary">
                <li>
                    <label class="textfield_names">Name :</label>
                    <input name="input" type="text" id="order-summary-date" class="share-txtfield" value="name" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'name')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">Address :</label>
                    <input name="input" type="text" id="order-summary-address1" class="share-txtfield" value="address line 1" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address line 1')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">Address Line 2:</label>
                    <input name="input" type="text" id="order-summary-address2" class="share-txtfield" value="address line 2" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address line 2')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">Card type :</label>
                    <div class="styled-select" style="width: 72%; margin: 0;">
                        <select id="order-summary-cardtype">
                            <option value="">-Choose-</option>
                            <option value="visa">Visa</option>
                            <option value="master">Master</option>
                            <option value="discover">Discover</option>
                            <option value="Amex">Amex</option>
                        </select>
                    </div>
                </li>
                <li>
                    <label class="textfield_names">Card number</label>
                    <input name="input" type="text" id="order-summary-ccnum" class="" value="card number" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'card number')this.value = '';" readonly />
                </li>
                <li>
                    <label class="textfield_names">Exp date:</label>
                    <input name="input" type="text" id="order-summary-expdate" class="" value="exp date" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'exp date')this.value = '';" readonly />
                </li>
                <li>
                    <label class="textfield_names">Exp year:</label>
                    <input name="input" type="text" id="order-summary-expyear" class="" value="exp year" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'exp year')this.value = '';" readonly />
                </li>
                <li>
                    <label class="textfield_names">City:</label>
                    <input name="input" type="text" id="order-summary-city" class="" value="city" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'city')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">State:</label>
                    <input name="input" type="text" id="order-summary-state" class="" value="state" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'state')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">Zip:</label>
                    <input name="input" type="text" id="order-summary-zip" class="" value="zip" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'zip')this.value = '';"/>
                </li>
                <li>
                    <label class="textfield_names">Plan name:</label>
                    <label class="textfield_names" style="margin-left: 10px; width: 300px;">Plan A</label>
                </li>
                <li>
                    <label class="textfield_names">Cost:</label>
                    <label class="textfield_names" style="margin-left: 10px;">$12</label>
                </li>
                <li>
                    <input id="subscription-order-agree" class="css-checkbox" type="checkbox" name="subscription_order_agree"/>
                    <label for="subscription-order-agree" name="demo_lbl_1" class="css-label margin-none" >Confirm place order.</label>
                </li>
            </ul>
            <div style="clear: both;"></div>
            <div class="bottom-actions">
                <a class="black_btn_skin" href="javascript:;" onclick="confirmOrder();" style="margin-top: 20px; display: inline-block;">Next</a>
                <a class="black_btn_skin" href="javascript:;" onclick="activeAkordeon('subscription-payment-method-tab', false);" style="margin-top: 20px; display: inline-block;">Back</a>
            </div>
        </div>
    </div>
</div>
<div class="akordeon-item subscription-order-receipt-tab">
    <div class="akordeon-item-head subscription-order-receipt">
        <div class="akordeon-item-head-container">
            <div class="akordeon-heading">
                Order receipt
            </div>
        </div>
    </div>
    <div class="akordeon-item-body">
        <div class="akordeon-item-content">
            <ul class="share_memreas_details order-recept">
                <li>
                    <label class="textfield_names">Name:</label>
                    <label class="textfield_names" style="margin-left: 10px;">John Miller</label>
                </li>
                <li>
                    <label class="textfield_names">Address:</label>
                    <label class="textfield_names" style="margin-left: 10px;">Address line 1</label>
                </li>
                <li>
                    <label class="textfield_names">Address 2:</label>
                    <label class="textfield_names" style="margin-left: 10px;">Address line 2</label>
                </li>
                <li>
                    <label class="textfield_names">Card type :</label>
                    <label class="textfield_names" style="margin-left: 10px;">Visa</label>
                </li>
                <li>
                    <label class="textfield_names">Card number</label>
                    <label class="textfield_names" style="margin-left: 10px;">xxxxxxxxxxxx5452</label>
                </li>
                <li>
                    <label class="textfield_names">Exp date:</label>
                    <label class="textfield_names" style="margin-left: 10px;">02</label>
                </li>
                <li>
                    <label class="textfield_names">Exp year:</label>
                    <label class="textfield_names" style="margin-left: 10px;">2016</label>
                </li>
                <li>
                    <label class="textfield_names">City:</label>
                    <label class="textfield_names" style="margin-left: 10px;">Newyork</label>
                </li>
                <li>
                    <label class="textfield_names">State:</label>
                    <label class="textfield_names" style="margin-left: 10px;">NY</label>
                </li>
                <li>
                    <label class="textfield_names">Zip:</label>
                    <label class="textfield_names" style="margin-left: 10px;">25525</label>
                </li>
                <li>
                    <label class="textfield_names">Plan name:</label>
                    <label class="textfield_names" style="margin-left: 10px;">Plan A</label>
                </li>
                <li>
                    <label class="textfield_names">Cost:</label>
                    <label class="textfield_names" style="margin-left: 10px;">$12</label>
                </li>
            </ul>
            <div style="clear: both;"></div>
            <div style="text-align: center;" class="message-order hide-onload">Thank you! You will receive an email confirmation shortly</div>
        </div>
    </div>
</div>