<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<h3>Notification of Copyright Infringement</h3>
<p><strong>fe.memreas.com</strong> respects your Intellectual Property Rights and has a policy to respond to notices of alleged copyright infringement that comply with the Digital Millennium Copyright Act, 1998, available on http://www.copyright.gov/legislation/dmca.pdf If you are a copyright owner or an agent thereof, and you believe that any content hosted on our website <strong>http://fe.memreas.com/infringes</strong> your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) through mail or email, by providing <strong>fe.memreas.com</strong> Designated Copyright Agent (details mentioned below), with the following information in writing. If <strong>fe.memreas.com</strong> is convinced about the violation, it will promptly take appropriate action by disabling the access to such material or remove it and also termination of the membership of those Users without notice if they are found to be "repeat infringers."</p>

<p>1. Identification of the copyrighted work you claim to have been infringed, or, if multiple copyrighted works on <strong>http://fe.memreas.com</strong> are covered by a single notification, a list of such works.</p>
<p>2. Identification of the material you claim to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material. Please provide URLs to help us locate content quickly.</p>
<p>3. Sufficient information to enable us to contact the complaining party, such as address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted.</p>
<p>4. A statement as follows: "I hereby state that I have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law".</p>
<p>5. Another statement: "I hereby state that the information in the notification is accurate, and under penalty of perjury, that I am the owner/ authorized to act on behalf of the owner of an exclusive right that is allegedly infringed".</p>
<p>6. Your physical or electronic signature.</p>
<p>Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.</p>

<h3>Counter-Notification</h3>
<p>If you are the owner of the allegedly infringed material and if you elect to send us a counter notice; in order to enable us to take cognizance of your notification, it must be in writing and must include the following:</p>
<p>1.	A physical or electronic signature of the member.</p>
<p>2.	Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled.</p>
<p>3.	A statement under penalty of perjury as follows: "I have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled."</p>
<p>4.	Another statement: "I consent to the jurisdiction of the Courts for the judicial district ________________, or (if the subscriber’s address is outside of the United States) courts located at ____________ in which <strong>http://fe.memreas.com</strong> may be accessed, and that the subscriber will accept service of process from the person who provided notification or an agent of such person".</p>
<p>5.	The member’s name, address, and telephone number.</p>
<p>Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity was removed or disabled by mistake or misidentification may be subject to liability.</p>
<p>You may submit your Counter Notification by sending it to our Designated Agent by mail or e-mail as set forth below.</p>

<p>Designated Copyright Agent</p>
<p>You can send your notifications and counter-notifications of claimed infringement to <strong>fe.memreas.com</strong> Designated Copyright Agent who can be reached as below:</p>
<p>Attention: Copyright Agent</p>
<p><strong>fe.memreas.com</strong></p>
<p>Email: <a href="mailto:admin@memreas.com">admin@memreas.com</a></p>
<p>You acknowledge that if you fail to comply with all of the requirements, your DMCA notification may not be valid.</p>