<?php 
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<h3>Notification of Copyright Infringement</h3>
<p><strong>memreas</strong> respects your intellectual property rights and has a policy to respond to notices of alleged copyright infringement that comply with the digital millennium copyright act, 1998, available on http://www.copyright.gov/legislation/dmca.pdf if you are a copyright owner or an agent thereof, and you believe that any content hosted on our website <strong>http://www.memreas.com/infringes</strong> your copyrights, you may submit a notification pursuant to the digital millennium copyright act (“dmca”) via the “report a dmca violation” link on our homepage and providing the following information:</p>

<p>1. Copyright owner’s name
<p>2. Address
<p>3. Email
<p>4. Media id – this information can be found by hovering over the media in question
<p>5. Agreement to our terms and submission of information is reflected as your electronic signature

<p>Once you have submitted this information memreas llc will inform the user who posted the media and take actions to remove access to the media.  In the event memreas finds “repeat infringers” we will initiate termination of their membership.

<p>Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.</p>

<h3>Counter-Notification</h3>
<p>if you are the owner of the allegedly infringed material and if you elect to send us a counter notice; you may do so on the website at www.memreas.com in the more section under dmca.  There you will be able to submit your counter claim containing the following information:</p>

1. Full name
2. Address
3. Phone number
4. A file upload of Signed written communication containing:
4.1 a physical or electronic signature
4.2 identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled.
4.3 a statement under penalty of perjury as follows: "i have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled."
4.4 another statement: "I consent to the jurisdiction of the courts for the judicial district of Wilmington, Delaware in which http://www.memreas.com may be accessed and that the subscriber will accept service of process from the person who provided notification or an agent of such person".
4.5 the member’s name, address, and telephone number.

<p>Once we have received your counter notice we will inform the claimant via email and provide your contact information.  Once this is complete memreas will leave resolution of the claim to the claimant and counter-claimant.  memreas will not re-instate the media but the member is free to utilize their account to submit the media so long as their account is in good standing and they are in accordance with our terms of service and dmca policy.

<p>Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity was removed or disabled by mistake or misidentification may be subject to liability.</p>
<p>You may submit your Counter Notification by sending it to our Designated Agent by mail or e-mail as set forth below.</p>

<p>Designated Copyright Agent</p>
<p>In the event you are unable to utilize the site to register your claim you can send your notifications and counter-notifications of claimed infringement to <strong>www.memreas.com</strong> Designated Copyright Agent who can be reached as below:</p>
<p>Attention: Copyright Agent</p>
<p><strong>www.memreas.com</strong></p>
<p>Email: <a href="mailto:admin@memreas.com">admin@memreas.com</a></p>
<p>You acknowledge that if you fail to comply with all of the requirements, your DMCA notification may not be valid.</p>