<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas Canvas</title>
<!--Custom css-->
<link href="/memreas/org/css/style.css" rel="stylesheet" type="text/css">
<!--Bootstrap Css-->
<link href="/memreas/org/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    <!--
    .row-fluid{
        background: #18539D;
     }
    .center-logo{
        width: 960px;
        margin: 0 auto;
    }
    .center-logo img.big-logo{ width: 100%; }
    .bottom-market-links{
        width: 280px;
        margin: 0 auto;
        margin-top: -80px;
    }
    -->
</style>
</head>

<body>
<!-- Begin : Container -->
<div class="container">
  <!-- Begin : Header -->
  <div class="row-fluid">
  	<header>
      <div class="like-btn"><div class="fb-like" data-href="https://fe.memreas.com" data-layout="standard" data-action="like" data-show-faces="false" data-share="false"></div></div>
      <h1 id="logo"><a href="http://fe.memreas.com"><img src="/memreas/img/logo.png" /></a></h1>
    </header>
  </div>
  <!-- End : Header -->
  <!-- Begin : Content -->
  	<div class="row-fluid content">
        <div class="center-logo">
            <img class="big-logo" src="/memreas/img/fb-default.gif" />
            <div class="bottom-market-links">
                <a href=""><img src="/memreas/img/gg-play.gif" /></a>
                <a href=""><img src="/memreas/img/app-store.gif" /></a>
            </div>
            <div style="clear: both; height: 80px;"></div>
        </div>
    </div>
  <!-- End : Content -->
</div>
<!-- End : Container -->
</body>
</html>
