<?php 
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;
use Application\Model\MemreasConstants;

$username = $_SESSION['username'];
$domain = MemreasConstants::CLOUDFRONT_DOWNLOAD_HOST;
?>
<div class="modal-backdrop fade out" style="display:none;"></div>
<!-- Start : Footer -->
        <footer class="rel">
            <p>&copy; 2014 memreas, llc. All rights reserved.</p>
        </footer>
<!-- End : Footer -->
