<?php 
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');        
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";
?>

<!-- Start : Footer -->
<footer>&copy; 2013 memreas, llc. All rights reserved.</footer>
<!-- End : Footer -->
