<?php 
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');        
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";
?>
<div class="modal-backdrop fade out" style="display:none;"></div>
<!-- Start : Footer -->
        <footer class="rel">
            <p>&copy; 2014 memreas, llc. All rights reserved.</p>
        </footer>
<!-- End : Footer -->
