<?php
use Zend\Session\Container;
header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1.
header('Pragma: no-cache'); // HTTP 1.0.
header('Expires: 0'); // Proxies.
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Methods: POST, GET");
header("Access-Control-Allow-Headers: x-requested-with");
$session = new Container('user');
//$user_id = $session->offsetGet('user_id');
$user_id = $data['userid'];
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/transtyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/davidstyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link href="/memreas/css/fotorama.css" rel="stylesheet">
<link rel="stylesheet" href="/memreas/css/swipebox.css">
<link href="/memreas/css/jquery.akordeon.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="/memreas/css/jNotify.jquery.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/datepicker.css" rel="stylesheet" type="text/memreas/css">


<!-- JW Player plugin -->
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.js"></script>
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.html5.js"></script>


<!--jQuery Lybrary-->
<script src="//code.jquery.com/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/memreas/js/global.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="/memreas/js/jquery.cookie.js"></script>

<!--Google Map-->
<script src="http://maps.google.com/maps/api/js?libraries=places&region=uk&language=en&sensor=true"></script>

<!-- Fotorama -->
<script src="/memreas/js/fotorama.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>
<script src="/memreas/js/bootstrap-datepicker.js"></script>

<!--Social Library-->
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script src="/memreas/js/facebook.js"></script>
<script src="/memreas/js/jquery.oauthpopup.js"></script>
<script src="/memreas/js/twitter.js"></script>

<!-- akordeon -->
<script src="/memreas/js/jquery.akordeon.js" type="text/javascript"></script>

<!-- pop-up -->
<script src="/memreas/js/popup.js" type="text/javascript"></script>

<!-- custom scrollbars plugin -->
<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>

<!-- For drag and drop upload -->
<link href="/memreas/assets/css/style.css" rel="stylesheet" />
<!-- jQuery File Upload Dependencies -->
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="/memreas/assets/js/jquery.iframe-transport.js"></script>
<script src="/memreas/assets/js/jquery.fileupload.js"></script>

<!--Backgound Strecher-->
<script src="/memreas/js/jNotify.jquery.min.js"></script>
<script type="text/javascript" src="/memreas/js/jquery.xml2json.js"></script>
<script type="text/javascript" src="/memreas/js/fetchLocalMedia.js"></script>
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript" src="/memreas/js/serverSide.js"></script>
<script src="/memreas/js/base_func.js"></script>
<script type="text/javascript" src="/memreas/js/ajax.js"></script>
<script src="/memreas/js/share.js"></script>
<script type="text/javascript" src="/memreas/js/syncing.js"></script>

<!-- Our main JS file -->
<script src="/memreas/assets/js/script.js"></script>

<script src="/memreas/js/record/AudioContextMonkeyPatch.js"></script>
<script src="/memreas/js/record/recorder.js"></script>
<script src="/memreas/js/record/audio_record.js"></script>

<!-- Memreas -->
<script src="/memreas/js/jquery.mouseSwipe.js" type="text/javascript"></script>
<script type="text/javascript" src="/memreas/js/memreas.js"></script>
<script type="text/javascript" src="/memreas/js/notification.js"></script>

<script type="text/javascript">
$(document).ready(function(){
    //Prefetch for image location
    $.fetch_server_media('<?php echo $user_id; ?>');
    $.addfile();
    share_initObjects();
    share_initAkordeon();
    share_customScrollbar();
    $(document).bgStretcher({
            images: ['/memreas/img/bg.jpg'],
            imageWidth: 1366, imageHeight: 700
    });
    $(".change-location a.browse-server").click (function(){ $.fetch_server_media($("input[name=current_user_id]").val()); });
    $(".change-location a.fetch-local").click (function(){ $(".browse-file").fadeIn (500); });
    $(".image_upload_box").mCustomScrollbar(
                {scrollButtons:{enable:true }}
    );
    $(".event-upload-image").mCustomScrollbar(
                {scrollButtons:{enable:true }}
    );
});
$(function() {
        $("#dtp_date").datepicker();
        $("#dtp_from").datepicker();
        $("#dtp_to").datepicker();
        $("#dtp_selfdestruct").datepicker();

        //Testing
    });
</script>
</head>

<body>
<div id="loadingpopup">
    <div id="loadingpopupinner">
        <img id="loadingimg" src="/memreas/img/loading.gif">
        <span id="loadingtext">Please wait...</span>
    </div>
</div>
<input type="hidden" name="user_id" value="<?php echo $data['userid']; ?>">
<!-- Begin : Container -->
<div class="container">
  <?php include 'header.phtml'; ?>

  <!-- Begin : Content - For Tab-->
      <div class="row-fluid content" style="background: #185EB3;">
      <div class="span1" id="main-tab">
          <!-- Begin : Nav -->
          <nav>
          <ul>
            <li><a href="javascript:;" class="gallery active" title="gallery" onclick="return false;"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="javascript:;" class="queue" title="queue" onclick="return false;"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="javascript:;" class="share" title="share"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="javascript:;" class="memreas" title="memreas"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="javascript:;" class="more" title="more"><img src="/memreas/img/more.png" alt=""></a></li>
          </ul>
        </nav>
        <!-- End : Nav -->
      </div>
      <div id="maintab-content">
            <!-- Begin : Content - For notification -->
          <div class="span11 notification-area" style="display: none;">
              <div class="span9">
               <ul class="notificationresults scrollClass">

                   </ul>
                    <a class="black_btn_skin f-center" href="#">ok</a>
                    <a class="black_btn_skin" href="#">cancel</a>
                  </div>
                  <div class="span3">
                      <section id="ad">
                      <div class="adbox">Your <br>Advertisement <br>space </div>
                      <div class="adbox">Your <br>Advertisement <br>space </div>
                      <div class="adbox-port">Your <br>Advertisement <br>space </div>
                      <div class="adbox-port">Your <br>Advertisement <br>space </div>
                    </section>
                  </div>
                  <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
                  </div>
          <!-- End : Notification -->
          <div class="span11 tabcontent-detail" id="gallery">
              <div class="span9">
                <ul id="tabs" class="medium_tabs">
                  <li><a href="#" title="tab1">view</a></li>
                  <li><a href="#" title="tab2">edit</a></li>
                  <li><a href="#" title="tab4">location</a></li>
                </ul>
                <div id="tab-content">
                  <div id="tab1" class="hideCls hidden-onload">
                    <input type="hidden" name="current_user_id" value="<?php echo $user_id; ?>">
                    <div class="preload-server">
                        <div class="marks"></div>
                        <div class="choose-details"><img src="/memreas/img/loader.gif" /><br/>Fetching media...</div>
                    </div>
                    <div class="browse-file">
                        <div class="marks"></div>
                        <div class="choose-details"><h3>Choose the location which you want to share</h3>
                            <input  type="file" id="dir" webkitdirectory="" style="display: none;"/>
                            <a class="btn-browse-file" href="#" onclick="$('#dir').click();">Browse files</a>
                        </div>
                    </div>
                    <div class="user-resources fotorama" data-click="false" data-swipe="true" data-ratio="800/325" data-max-width="100%"  data-allow-full-screen="true"  data-nav="thumbs">
                         <!-- USER RESOURCES WILL BE LOADED HERE -->
                    </div>
                  </div>
                  <div id="tab2" class="hideCls hidden-onload">
                    <div class="edit-area">
                        <ul id="content_1" class="pics edit-area-scroll scroll-area">
                            <div class="first-element"></div>
                        </ul>
                        <div style="clear: both;"></div>
                        <a class="black_btn_skin" href="javascript:deleteFiles();">Delete</a>&nbsp;<a class="black_btn_skin" href="javascript:;" id="btn-upload">Upload</a>
                    </div>
                  </div>
                  <div id="tab4" class="hideCls hidden-onload">
                      <div class="map">
                        <iframe width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Canada,+KY,+USA&amp;aq=0&amp;oq=Canada,&amp;sll=35.101934,-94.570312&amp;sspn=38.075006,86.572266&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Canada,+Pike,+Kentucky,+United+States&amp;ll=41.934977,-81.738281&amp;spn=11.438126,18.720703&amp;z=5&amp;iwloc=A&amp;output=embed"></iframe>
                      </div>
                  </div>
                </div>
                <div class="change-location" style="display: none;"><a class="fetch-local" href="#" style="margin-left: 10px;">Change local directory</a><a class="browse-server" href="#">Browse Server</a></div>
                 <!------------------First-pop-up-------------------->
                    <div id="popupplayer" class="video_popups">
                            <a id="popupplayerClose" onClick="disablePopup('popupplayer')" class='popupClose'>x</a>
                            <div id="myElement">Loading the player...</div>
                            <script type="text/javascript">
                                jwplayer("myElement").setup({
                                    file: "http://www.emc2financial.com/jwplayer/trail.mp4",
                                    image: "/memreas/img/large-pic-1.jpg"
                                });
                            </script>
                        </div>
                        <div id="bgpopupplayer" class="backgroundPopup"></div>
              </div>
              <div class="span3">
                  <section id="ad">
                  <div class="adbox">Your <br>Advertisement <br>space </div>
                  <div class="adbox">Your <br>Advertisement <br>space </div>
                  <div class="adbox-port">Your <br>Advertisement <br>space </div>
                  <div class="adbox-port">Your <br>Advertisement <br>space </div>
                </section>
              </div>
              <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
              <div class="row-fluid">
                  <!-- <input type="local_directory" class="hidden-input" webkitdirectory> -->
                  <!-- <input type="file" id="local_directory" webkitdirectory="" directory=""> -->
              </div>
          </div>
          <div class="span11 tabcontent-detail" id="queue" style="display: none;">
            <div class="span9">
            <div class="row-fluid">
                <ul id="tabs-queue">
                    <li><a href="#" title="upload-queue" class="tabs2">uploads</a></li>
                    <li><a href="#" title="complete" class="tabs2">completed</a></li>
                </ul>

                <div id="tab-content-queue">
                    <div id="upload-queue" class="hideCls">
                              <ul id="content_1" class="image_upload_box">
                                  <li class="first-upload"></li>
                              </ul>
                              <!-- Direct Upload to S3 -->
                                <form action="https://<?php echo $data['bucket']; ?>.s3.amazonaws.com/" method="POST" enctype="multipart/form-data" class="direct-upload">

                                    <!-- We'll specify these variables with PHP -->
                                    <!-- Order of these is Important -->
                                    <input type="hidden" name="key" value="<?php echo $data['userid']; ?>/image/${filename}">
                                    <input type="hidden" name="AWSAccessKeyId" value="<?php echo $data['accesskey']; ?>">
                                    <input type="hidden" name="acl" value="private">
                                    <input type="hidden" name="success_action_status" value="201">
                                    <input type="hidden" name="policy" value="<?php echo $data['base64Policy']; ?>">
                                    <input type="hidden" name="signature" value="<?php echo $data['signature']; ?>">

                                    <input type="file" name="file" hidden="hidden" />
                                    <div class="upload-dropzone"></div>
                                </form>
                                <input type="hidden" name="once_instance" value="0">
                          <a class="black_btn_skin f-right clear-upload" href="#">clear</a>
                          <input type="hidden" name="ContentType" value="" />
                          <input type="hidden" name="ContentName" value="" />
                    </div>
                    <div id="complete" class="hideCls">
                        <ul id="content_1" class="pics completed-upload scroll-area">
                            <div class="first-element"></div>
                        </ul>
                          <a class="black_btn_skin f-left" href="#">clear</a>
                    </div>
                </div>
                        </div>
                      </div>
                      <div class="span3">
                          <section id="ad">
                          <div class="adbox">Your <br>Advertisement <br>space </div>
                          <div class="adbox">Your <br>Advertisement <br>space </div>
                          <div class="adbox-port">Your <br>Advertisement <br>space </div>
                          <div class="adbox-port">Your <br>Advertisement <br>space </div>
                        </section>
                      </div>
                      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
                      </div>

            <div class="span11 tabcontent-detail" id="share" style="display: none;">

                <div class="span9">
                    <div class="row-fluid">
                <ul id="tabs-share" class="medium_tabs">
                    <li><a href="#" title="tab1-share">memreas details</a></li>
                    <li><a href="#" title="tab2-share">media</a></li>
                    <li><a href="#" title="tab3-share">friends</a></li>
                </ul>
                <div id="tab-content-share">
                    <div id="tab1-share" class="hideCls">
                        <div class="required">only name is required</div>
                        <ul id="content_1" class="share_memreas_details">
                        <li>
                        <label class="textfield_names">name :</label>
                        <input name="input" type="text" id="txt_name" class="share-txtfield" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';"/>
                        </li>
                        <li>
                        <label class="textfield_names">date :</label>
                        <input name="input" type="text" id="dtp_date" class="share-txtfield date-picker" readonly value="from" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'from')this.value = '';"/>
                        </li>
                        <li>
                        <label class="textfield_names">location :</label>
                        <input name="input3" type="text" id="txt_location" class="share-txtfield" value="address or current location" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address or current location')this.value = '';" onClick="share_showGoogleMap('div_locationmap_maparea');"/>
                        </li>
                        <li>
                         <input id="ckb_canpost" class="css-checkbox" type="checkbox" checked="checked"/>
                         <label for="ckb_canpost" name="demo_lbl_1" class="css-label margin-none" >friends can post pics/videos</label>
                        </li>
                        <li>
                         <input id="ckb_canadd" class="css-checkbox" type="checkbox" checked="checked"/>
                         <label for="ckb_canadd" name="demo_lbl_2" class="css-label margin-none" >friends can add Friends</label>
                        </li>
                        <li>
                         <input id="ckb_public" class="css-checkbox" type="checkbox" checked="checked"/>
                         <label for="ckb_public" name="demo_lbl_3" class="css-label margin-none" onClick="javascript:share_clickCkbPublic();" >public (anyone can add or post)</label>
                        </li>
                        <li>
                         <input id="ckb_viewable" class="css-checkbox" type="checkbox" />
                         <label for="ckb_viewable" name="demo_lbl_4" class="css-label margin-none" >viewable :</label>
                         <input name="input" type="text" id="dtp_from" class="date-picker" readonly value="from" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'from')this.value = '';"/>
                         <input name="input" type="text" id="dtp_to" class="date-picker" readonly value="to" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'to')this.value = '';"/>
                        </li>
                        <li>
                         <input id="ckb_selfdestruct" class="css-checkbox" type="checkbox" checked="checked"/>
                         <label for="ckb_selfdestruct" name="demo_lbl_5" class="css-label margin-none" >self destruct :</label>
                         <input name="input" type="text" id="dtp_selfdestruct" class="share-txtfield-2 date-picker" readonly value="" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '')this.value = '';"/>
                        </li>
                        </ul>
                        <a class="black_btn_skin f-center" href="javascript:share_addEvent();">next</a>
                        <a class="black_btn_skin" href="javascript:share_clearMemreas(false);">cancel</a>
                    </div>
                    <div id="tab2-share" class="hideCls">
                        <ul id="share_medialist" class="pics scroll-area scrollClass">
                            <!--<li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>-->
                        </ul>
                        <div class="event-upload-area" style="display: none;">
                             <ul class="event-upload-image">
                                  <li class="first-upload"></li>
                              </ul>
                            <div class="upload-dropzone upload-from-event"></div>
                        </div>
                        <div class="comment">
                            <ul>
                                <li>
                                    <div class="comment-txt clearfix">add a comment</div>
                                </li>
                                <li>
                                    <input name="input2" accept="audio/*;capture=microphone" type="text" id="txt_comment" class="comment_txtfield" value="your comments here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'your comments here')this.value = '';"/>
                                </li>
                            </ul>

                        </div>
                        <div class="add-comment-buttons">
                            <a class="black_btn_skin f-center" href="javascript:share_addComment();">next</a>
                            <a class="black_btn_skin f-middle" href="javascript:share_clearMemreas(false);">cancel</a>
                            <a class="black_btn_skin f-middle" href="javascript:showUploadEvent();">Upload to this event</a>
                        </div>
                        <div class="upload-event-buttons" style="display: none;">
                            <a class="black_btn_skin f-middle" href="javascript:hideUploadEvent();">back to media</a>
                        </div>
                    </div>
                    <div id="tab3-share" class="hideCls">
                        <div class="styled-select">
                            <select id="cmb_socialtype">
                                <option value="facebook">facebook</option>
                                <option value="twitter">twitter</option>
                            </select>
                        </div>
                        <ul id="share_friendslist" class="share_friends_contents scrollClass scroll-area">
                            <!--
                            <li>
                              <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
                              <aside class="pro-pic_names2">Friend Name</aside>
                            </li>
                            -->
                        </ul>
                        <div class="akordeon" id="buttons">
                            <div class="akordeon-item expanded">
                                <div class="akordeon-item-head">
                                    <div class="akordeon-item-head-container">
                                        <div class="akordeon-heading">
                                            email address list
                                        </div>
                                    </div>
                                </div>
                                <div class="akordeon-item-body">
                                    <div class="akordeon-item-content" style="padding:0px 10px;">
                                      <input id="txt_emaillist" name="input" type="text" class="more-input" value="add your email list here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'add your email list here')this.value = '';"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <ul class="share_friends_check_box">
                            <li>
                                <input id="ckb_makegroup" class="css-checkbox" type="checkbox" checked="checked" />
                                <label for="ckb_makegroup" name="demo_lbl_6" class="css-label">make this a group</label>
                                <input id="txt_groupname" name="input" type="text" class="share-txtfield-3" value="group name here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'group name here')this.value = '';"/>
                            </li>
                        </ul>
                        <a class="black_btn_skin f-center" href="javascript:share_makeGroup();">ok</a>
                        <a class="black_btn_skin f-middle" href="javascript:backToMedia();">cancel</a>
                    </div>
                </div>
            </div>
          </div>
          <div class="span3">
            <section id="ad">
              <div class="adbox">Your <br>Advertisement <br>space </div>
              <div class="adbox">Your <br>Advertisement <br>space </div>
              <div class="adbox-port">Your <br>Advertisement <br>space </div>
              <div class="adbox-port">Your <br>Advertisement <br>space </div>
            </section>
          </div>
          <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
          </div>

        <div id="dlg_locationmap" class="popups2">
              <a id="btn_locationmap_close" onClick="javascript:share_closeGoogleMap(false);" class='popupClose'>x</a>
            <h2>location</h2>
            <a id="btn_locationmap_ok" class="black_btn_skin" href="javascript:share_closeGoogleMap(true);">OK</a>
            <input id="txt_locationmap_address" name="input" type="text" />
            <div class="clear"></div>
            <div id="div_locationmap_maparea" class="map_box"></div>
        </div>
        <div id="div_locationmap_back" class="backgroundPopup"></div>
            <!-- END SHARE TAB -->
            <div class="span11 tabcontent-detail" id="memreas" style="display: none;">

                <div class="span9">
          <div class="row-fluid">
<ul id="tabs-memreas">
    <li><a href="#" title="memreas-tab1">me</a></li>
    <li><a href="#" title="memreas-tab2">friends</a></li>
    <li><a href="#" title="memreas-tab3">public</a></li>
</ul>

<div id="tab-content-memreas">
    <div id="memreas-tab1" class="hideCls">
              <ul id="content_1" class="pics scroll-area myMemreas scrollClass">

              </ul>
          <a class="black_btn_skin f-left" href="javascript:addMemreas();">add memreas</a>
          <a class="black_btn_skin f-right" href="#">add friends</a>
    </div>
    <div id="memreas-tab2" class="hideCls">
            <ul id="content_1" class="pics scroll-area event_images scrollClass">

              </ul>
          <a class="black_btn_skin f-center" href="javascript:addMemreas();">add memreas</a>
    </div>
    <div id="memreas-tab3" class="hideCls">
        <ul id="content_1" class="pics scrollClass event_images_public scroll-area">

              </ul>
          <a class="black_btn_skin f-center" href="javascript:addMemreas();">add memreas</a>
    </div>
</div>
        </div>
      </div>
      <div class="span3">
          <section id="ad">
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
        </section>
      </div>
      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
      </div>

            </div>
            <script>
                (function($){
                    $(window).load(function(){

                        $("#tab-content-memreas div.hideCls").hide(); // Initially hide all content
                        $("#tabs-memreas li:first").attr("id","current"); // Activate first tab
                        $("#tab-content-memreas div:first").fadeIn(); // Show first tab content*/

                        $('#tabs-memreas a').click(function(e) {

                            e.preventDefault();
                            $("#tab-content-memreas div.hideCls").hide(); //Hide all content
                            $("#tabs-memreas li").attr("id",""); //Reset id's
                            $(this).parent().attr("id","current"); // Activate this
                            $('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
                            $('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
                            if (!($('#' + $(this).attr('title') + " .scroll-area").hasClass('mCustomScrollbar'))){
                                $('#' + $(this).attr('title') + " .scroll-area").mCustomScrollbar({
                                    scrollButtons:{
                                        enable:true
                                    }
                                });
                            }
                            $('#' + $(this).attr('title') + " .scroll-area").mCustomScrollbar("update");
                        });

                    });
                })(jQuery);
            </script>
            <!-- END MEMREAS TAB -->

                      <script type="text/javascript">
                        $("#tab-content-queue div.hideCls").hide(); // Initially hide all content
                        $("#tabs-queue li:first").attr("id","current"); // Activate first tab
                        $("#tab-content-queue div:first").fadeIn(); // Show first tab content*/

                        $('#tabs-queue a').click(function(e) {

                            e.preventDefault();
                            $("#tab-content-queue div.hideCls").hide(); //Hide all content
                            $("#tabs-queue li").attr("id",""); //Reset id's
                            $(this).parent().attr("id","current"); // Activate this
                            $('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
                            if (!($('#' + $(this).attr('title') + " .scroll-area").hasClass('mCustomScrollbar'))){
                                $('#' + $(this).attr('title') + " .scroll-area").mCustomScrollbar({
                                    scrollButtons:{
                                        enable:true
                                    }
                                });
                            }
                            $('#' + $(this).attr('title') + " .scroll-area").mCustomScrollbar("update");
                        });
                      </script>
          </div>
      </div>
    </div>
  <!-- End : Content -->
</div>
<?php include 'footer.phtml'; ?>
<!-- End : Container -->
    <script>

        (function($){
            $(window).load(function(){

            $("ul.scrollClass").mCustomScrollbar({
                    scrollButtons:{
                        enable:true
                    }
                });
            /*
            $("#main-tab li:first").attr("id","current"); // Activate first tab
            $("#maintab-content div:first").fadeIn(); // Show first tab content


            $('#main-tab a').click(function(e) {

                e.preventDefault();
                $("#maintab-content div.span11").hide(); //Hide all content
                $('#main-tab a').removeClass ("active");
                $(this).attr("class","active"); // Activate this
                $('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
            });
                */
            $("#tab-content div.hideCls").hide(); // Initially hide all content
            $("#tabs li:first").attr("id","current"); // Activate first tab
            $("#tab-content div:first").fadeIn(); // Show first tab content

            $("#tabs li:eq(0) a").click (function(){ $.fetch_server_media($("input[name=user_id]").val()); });

            $('#tabs a').click(function(e) {
                e.preventDefault();
                $("#tab-content div.hideCls").hide(); //Hide all content
                $("#tabs li").attr("id",""); //Reset id's
                $(this).parent().attr("id","current"); // Activate this
                $('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
                ajaxScrollbarElement('#' + $(this).attr('title') + " .scroll-area");
            });

                //ajax demo fn
                $("a[rel='load-content']").click(function(e){

                    e.preventDefault();
                    var $this=$(this),
                        url=$this.attr("href");
                    $this.addClass("loading");
                    $.get(url,function(data){
                        $this.removeClass("loading");
                        $("ul.scrollClass .mCSB_container").html(data); //load new content inside .mCSB_container
                        $("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly loaded content
                        $("ul.scrollClass").mCustomScrollbar("scrollTo","top",{scrollInertia:200}); //scroll to top
                    });
                });
                $("a[rel='append-content']").click(function(e){
                    e.preventDefault();
                    var $this=$(this),
                        url=$this.attr("href");
                    $this.addClass("loading");
                    $.get(url,function(data){
                        $this.removeClass("loading");
                        $("ul.scrollClass .mCSB_container").append(data); //append new content inside .mCSB_container
                        $("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly appended content
                        $("ul.scrollClass").mCustomScrollbar("scrollTo","h2:last",{scrollInertia:2500,scrollEasing:"easeInOutQuad"}); //scroll to appended content
                    });
                });
            });
        })(jQuery);
    </script>

     <!-- custom swipebox plugin -->
    <script src="/memreas/js/jquery.swipebox.min.js"></script>
    <script type="text/javascript">
        jQuery(function($) {
            $(".swipebox").swipebox();
        });
    </script>


</body>
</html>
