<?php
use Zend\Session\Container;
header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1.
header('Pragma: no-cache'); // HTTP 1.0.
header('Expires: 0'); // Proxies.
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Methods: POST, GET");
header("Access-Control-Allow-Headers: x-requested-with");
$session = new Container('user');
//$user_id = $session->offsetGet('user_id');
$user_id = $data['userid'];
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/transtyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/davidstyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link href="/memreas/css/fotorama.css" rel="stylesheet">
<link rel="stylesheet" href="/memreas/css/swipebox.css">
<link href="/memreas/css/jquery.akordeon.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="/memreas/css/jNotify.jquery.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/datepicker.css" rel="stylesheet" type="text/memreas/css">

<!-- JW Player plugin -->
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.js"></script>
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.html5.js"></script>

<!--jQuery Lybrary-->
<script src="//code.jquery.com/jquery-1.8.3.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="/memreas/js/jquery.cookie.js"></script>

<!--Google Map-->
<script src="http://maps.google.com/maps/api/js?libraries=places&region=uk&language=en&sensor=true"></script>

<!-- Fotorama -->
<script src="/memreas/js/fotorama.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>
<script src="/memreas/js/bootstrap-datepicker.js"></script>
<script src="/memreas/js/bootstrap-typeahead.js"></script>


<!--Social Library-->
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script src="/memreas/js/facebook.js"></script>
<script src="/memreas/js/jquery.oauthpopup.js"></script>
<script src="/memreas/js/twitter.js"></script>

<!-- akordeon -->
<script src="/memreas/js/jquery.akordeon.js" type="text/javascript"></script>

<!-- pop-up -->
<script src="/memreas/js/popup.js" type="text/javascript"></script>

<!-- custom scrollbars plugin -->
<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>

<!-- For drag and drop upload -->
<link href="/memreas/assets/css/style.css" rel="stylesheet" />
<!-- jQuery File Upload Dependencies -->
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="/memreas/assets/js/jquery.iframe-transport.js"></script>
<script src="/memreas/assets/js/jquery.fileupload.js"></script>

<!--Backgound Strecher-->
<script src="/memreas/js/jNotify.jquery.min.js"></script>
<script type="text/javascript" src="/memreas/js/jquery.xml2json.js"></script>
<script type="text/javascript" src="/memreas/js/fetchLocalMedia.js"></script>
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript" src="/memreas/js/serverSide.js"></script>
<script src="/memreas/js/base_func.js"></script>
<script type="text/javascript" src="/memreas/js/ajax.js"></script>
<script src="/memreas/js/share.js"></script>
<script type="text/javascript" src="/memreas/js/syncing.js"></script>

<!-- Our main JS file -->
<script src="/memreas/assets/js/script.js"></script>
<script src="/memreas/js/record/AudioContextMonkeyPatch.js"></script>
<script src="/memreas/js/record/recorder.js"></script>
<script src="/memreas/js/record/audio_record.js"></script>

<!-- Memreas -->
<script src="/memreas/js/jquery.mouseSwipe.js" type="text/javascript"></script>
<script type="text/javascript" src="/memreas/js/memreas.js"></script>
<script type="text/javascript" src="/memreas/js/global.js"></script>
<script src="/memreas/js/jquery.swipebox.min.js"></script>
<script type="text/javascript" src="/memreas/js/memreas_gallery.js"></script>
</head>

<body>
<div id="loadingpopup">
  <div id="loadingpopupinner"> <img id="loadingimg" src="/memreas/img/loading.gif"> <span id="loadingtext">Please wait...</span> </div>
</div>
<input type="hidden" name="user_id" value="<?php echo $data['userid']; ?>">
<!-- Begin : Container -->
<div class="container">
  <?php include 'header1.phtml'; ?>
  
  
  <div class="row-fluid content" style="background: #185EB3;">
  <!-- Begin : Content - Left Tab-->
    <div class="span1" id="main-tab"> 
      <!-- Begin : Nav -->
      <nav>
        <ul>
          <li><a href="javascript:;" class="gallery active" title="gallery" onClick="return false;"><img src="/memreas/img/gallery.png" alt=""></a></li>
          <li><a href="javascript:;" class="queue" title="queue" onClick="return false;"><img src="/memreas/img/queue.png" alt=""></a></li>
          <li><a href="javascript:;" class="share" title="share"><img src="/memreas/img/share.png" alt=""></a></li>
          <li><a href="javascript:;" class="memreas" title="memreas"><img src="/memreas/img/memreas.png" alt=""></a></li>
          <li><a href="javascript:;" class="more" title="more"><img src="/memreas/img/more.png" alt=""></a></li>
        </ul>
      </nav>
      <!-- End : Nav --> 
    </div>
     <!-- end : Content - Left Tab-->
    <div id="maintab-content"> 
      <!-- Begin : Content - For notification -->
      <div class="span11 notification-area" style="display: none;">
       
       <div class="span12">

         <div class="span9">
          <ul class="notificationresults scrollClass">
          </ul>
          <a class="black_btn_skin f-center" href="#">ok</a> <a class="black_btn_skin" href="#">cancel</a> </div>
        <div class="span3">
          <section id="ad">
            <div class="adbox">Your <br>
              Advertisement <br>
              space </div>
            <div class="adbox">Your <br>
              Advertisement <br>
              space </div>
            <div class="adbox-port">Your <br>
              Advertisement <br>
              space </div>
            <div class="adbox-port">Your <br>
              Advertisement <br>
              space </div>
          </section>
        </div>
       </div>
        <div class="row-fluid">
          <div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div>
        </div>
      </div>
      <!-- End : Notification -->
      <!-- Begin : Content - gallery-->
      <div class="span9 tabcontent-detail" id="gallery" style="display: none;>
        <div class="">
          <ul id="tabs" class="medium_tabs">
            <li><a href="#" title="tab1">view</a></li>
            <li><a href="#" title="tab2">edit</a></li>
            <li><a href="#" title="tab4">location</a></li>
          </ul>
          <div id="tab-content">
            <div id="tab1" class="hideCls hidden-onload">
              <input type="hidden" name="current_user_id" value="<?php echo $user_id; ?>">
              <div class="preload-server">
                <div class="marks"></div>
                <div class="choose-details"><img src="/memreas/img/loader.gif" /><br/>
                  Fetching media...</div>
              </div>
              <div class="browse-file">
                <div class="marks"></div>
                <div class="choose-details">
                  <h3>Choose the location which you want to share</h3>
                  <input  type="file" id="dir" webkitdirectory="" style="display: none;"/>
                  <a class="btn-browse-file" href="#" onClick="$('#dir').click();">Browse files</a> </div>
              </div>
              <div class="user-resources" data-click="false" data-swipe="true" data-ratio="800/325" data-max-width="100%"  data-allow-full-screen="true"  data-nav="thumbs"> 
                <!-- USER RESOURCES WILL BE LOADED HERE --> 
              </div>
            </div>
            <div id="tab2" class="hideCls hidden-onload">
              <div class="edit-area">
                <ul id="content_1" class="pics edit-area-scroll scroll-area">
                  <div class="first-element"></div>
                </ul>
                <div style="clear: both;"></div>
                <a class="black_btn_skin" href="javascript:deleteFiles();">Delete</a>&nbsp;<a class="black_btn_skin" href="javascript:;" id="btn-upload">Upload</a> </div>
            </div>
            <div id="tab4" class="hideCls hidden-onload">
              <div class="map">
                <iframe width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Canada,+KY,+USA&amp;aq=0&amp;oq=Canada,&amp;sll=35.101934,-94.570312&amp;sspn=38.075006,86.572266&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Canada,+Pike,+Kentucky,+United+States&amp;ll=41.934977,-81.738281&amp;spn=11.438126,18.720703&amp;z=5&amp;iwloc=A&amp;output=embed"></iframe>
              </div>
            </div>
          </div>
          <div class="change-location" style="display: none;"><a class="fetch-local" href="#" style="margin-left: 10px;">Change local directory</a><a class="browse-server" href="#">Browse Server</a></div>
          <!------------------First-pop-up-------------------->
          <div id="popupplayer" class="video_popups"> <a id="popupplayerClose" onClick="disablePopup('popupplayer')" class='popupClose'>x</a>
            <div id="myElement">Loading the player...</div>
            <script type="text/javascript">
                                jwplayer("myElement").setup({
                                    file: "http://www.emc2financial.com/jwplayer/trail.mp4",
                                    image: "/memreas/img/large-pic-1.jpg"
                                });
                            </script> 
          </div>
          <div id="bgpopupplayer" class="backgroundPopup"></div>
        </div>
      </div>
      <!-- End : Content - gallery-->
      <!-- Begin : Content - que-->
      <div class="span9 tabcontent-detail" id="queue" style="display: none;">  
      </div>
       <!-- End : Content - que-->
        <!-- Begin : Content - memars-->
      <div class="span9 tabcontent-detail" id="memreas" style="display: none;">    
      </div>
       <!-- End : Content - memars-->
        <!-- Begin : Content - share-->
      <div class="span9 tabcontent-detail" id="share" style="display: none;">  
      </div>
      <div class="span9 tabcontent-detail" id="more" style="display: none;">  
      </div>
      <div class="span9 tabcontent-detail" id="search-result" style="display: ;">  
      </div>
       <!-- Begin : Content - share-->
      <!-- start : right-col -->
      <div id="right-col"class="span2">
          <section id="ad">
            <div class="adbox">Your <br>
              Advertisement <br>
              space </div>
            <div class="adbox">Your <br>
              Advertisement <br>
              space </div>
            <div class="adbox-port">Your <br>
              Advertisement <br>
              space </div>
            <div class="adbox-port">Your <br>
              Advertisement <br>
              space </div>
          </section>
        </div>
        <!-- End : right-col  -->
         <!-- Begin : Content - lower ad-->
      <div class="row-fluid">
          <div class="offset1 span11 ad"><img src="/memreas/img/ad.jpg" alt=""></div>
        </div>
         <!-- End : Content - lower ad-->
        
        <div class="row-fluid"> 
          <!-- <input type="local_directory" class="hidden-input" webkitdirectory> --> 
          <!-- <input type="file" id="local_directory" webkitdirectory="" directory=""> --> 
        </div>
      
      
      <div id="dlg_locationmap" class="popups2"> <a id="btn_locationmap_close" onClick="javascript:share_closeGoogleMap(false);" class='popupClose'>x</a>
        <h2>location</h2>
        <a id="btn_locationmap_ok" class="black_btn_skin" href="javascript:share_closeGoogleMap(true);">OK</a>
        <input id="txt_locationmap_address" name="input" type="text" />
        <div class="clear"></div>
        <div id="div_locationmap_maparea" class="map_box"></div>
      </div>
      <div id="div_locationmap_back" class="backgroundPopup"></div>
      <!-- END SHARE TAB -->
      
    </div>
    
    <!-- END MEMREAS TAB --> 
    
  </div>
</div>
</div>
<!-- End : Content -->
</div>
<?php include 'footer.phtml'; ?>
<!-- End : Container --> 

<!-- custom swipebox plugin -->
<script>  
 var subjects = ['PHP', 'MySQL', 'SQL', 'PostgreSQL', 'HTML', 'CSS', 'HTML5', 'CSS3', 'JSON'];   
$('#search').typeahead({ source: subjects})  
</script> 
</body>
</html>
