<?php
use Zend\Session\Container;
header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1.
header('Pragma: no-cache'); // HTTP 1.0.
header('Expires: 0'); // Proxies.
$session = new Container('user');
$user_id = $session->offsetGet('user_id')
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/transtyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/davidstyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link href="/memreas/css/fotorama.css" rel="stylesheet">
<link rel="stylesheet" href="/memreas/css/swipebox.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/css">


<!-- JW Player plugin -->
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.js"></script>
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.html5.js"></script>


<!--jQuery Lybrary-->
<script src="/memreas/js/jquery.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="/memreas/js/jquery.cookie.js"></script>

<!-- Fotorama -->
<script src="/memreas/js/fotorama.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>

<!--Backgound Strecher-->
<script type="text/javascript" src="/memreas/js/jquery.xml2json.js"></script>
<script type="text/javascript" src="/memreas/js/fetchLocalMedia.js"></script>
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript" src="/memreas/js/serverSide.js"></script>
<script type="text/javascript" src="/memreas/js/syncing.js"></script>
<script type="text/javascript" src="/memreas/js/ajax.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    //Prefetch for image location
    $.fetch_server_media('<?php echo $user_id; ?>');
    $.addfile();
    $(document).bgStretcher({
            images: ['img/bg.jpg'],
            imageWidth: 1366, imageHeight: 700
    });
    $(".change-location a.browse-server").click (function(){ $.fetch_server_media($("input[name=current_user_id]").val()); });
    $(".change-location a.fetch-local").click (function(){ $(".browse-file").fadeIn (500); });
});
</script>
</head>

<body>
<!-- Begin : Container -->
<div class="container">
  <?php include 'header.phtml'; ?>
  <!-- Begin : Content -->
      <div class="row-fluid content" style="background: #185EB3;">
      <div class="span1">
          <!-- Begin : Nav -->
          <nav>
          <ul>
            <li><a href="#" class="active"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/more.png" alt=""></a></li>
          </ul>
        </nav>
        <!-- End : Nav -->
      </div>
      <div class="span11">
      <div class="span9">
        <ul id="tabs" class="medium_tabs">
          <li><a href="#" title="tab1">view</a></li>
          <li><a href="#" title="tab2">edit</a></li>
          <li><a href="#" title="tab3">sync</a></li>
          <li><a href="#" title="tab4">location</a></li>
        </ul>
        <div id="tab-content">
          <div id="tab1" class="hideCls">
            <input type="hidden" name="current_user_id" value="<?php echo $user_id; ?>">
            <div class="preload-server">
                <div class="marks"></div>
                <div class="choose-details"><img src="/memreas/img/loader.gif" /><br/>Fetching media...</div>
            </div>
            <div class="browse-file">
                <div class="marks"></div>
                <div class="choose-details"><h3>Choose the location which you want to share</h3>
                    <input  type="file" id="dir" webkitdirectory="" style="display: none;"/>
                    <a class="btn-browse-file" href="#" onclick="$('#dir').click();">Browse files</a>
                </div>
            </div>
            <div class="user-resources" data-click="false" data-swipe="true" data-ratio="800/325" data-max-width="100%"  data-allow-full-screen="true"  data-nav="thumbs">
                 <!-- USER RESOURCES WILL BE LOADED HERE -->
            </div>
          </div>
          <div id="tab2" class="hideCls">
            <ul id="content_1" class="pics scrollClass">
              <h2>edit</h2>
              <div class="mCSB_container"></div>
            </ul>
          </div>
          <div id="tab3" class="hideCls">
            <div class="sync-content">
                <ul class="pics sync scrollClass" style="display: none;">
                </ul>
                <div class="upload"></div>
            </div>
            <div class="upload-media"><a href="javascript:;">Back</a> <a href="javascript:;" id="btn-upload">Upload</a></div>
          </div>
          <div id="tab4" class="hideCls">
              <div class="map">
                <iframe width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Canada,+KY,+USA&amp;aq=0&amp;oq=Canada,&amp;sll=35.101934,-94.570312&amp;sspn=38.075006,86.572266&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Canada,+Pike,+Kentucky,+United+States&amp;ll=41.934977,-81.738281&amp;spn=11.438126,18.720703&amp;z=5&amp;iwloc=A&amp;output=embed"></iframe>
              </div>
          </div>
        </div>
        <div class="change-location" style="display: none;"><a class="fetch-local" href="#" style="margin-left: 10px;">Change local directory</a><a class="browse-server" href="#">Browse Server</a></div>
         <!------------------First-pop-up-------------------->
            <div id="popupplayer" class="video_popups">
                    <a id="popupplayerClose" onClick="disablePopup('popupplayer')" class='popupClose'>x</a>
                    <div id="myElement">Loading the player...</div>
                    <script type="text/javascript">
                        jwplayer("myElement").setup({
                            file: "http://www.emc2financial.com/jwplayer/trail.mp4",
                            image: "/memreas/img/large-pic-1.jpg"
                        });
                    </script>
                </div>
                <div id="bgpopupplayer" class="backgroundPopup"></div>
      </div>
      <div class="span3">
          <section id="ad">
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
        </section>
      </div>
      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
      <div class="row-fluid">
          <!-- <input type="local_directory" class="hidden-input" webkitdirectory> -->
          <!-- <input type="file" id="local_directory" webkitdirectory="" directory=""> -->
      </div>
      </div>
    </div>
  <!-- End : Content -->
</div>
<?php include 'footer.phtml'; ?>
<!-- End : Container -->

    <!--pop-up-->
    <script src="/memreas/js/popup.js" type="text/javascript"></script>

    <!-- custom scrollbars plugin -->
    <script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>

        (function($){
            $(window).load(function(){

            $("ul.scrollClass").mCustomScrollbar({
                    scrollButtons:{
                        enable:true
                    }
                });

            $("#tab-content div.hideCls").hide(); // Initially hide all content
            $("#tabs li:first").attr("id","current"); // Activate first tab
            $("#tab-content div:first").fadeIn(); // Show first tab content*/

            $('#tabs a').click(function(e) {

                e.preventDefault();
                $("#tab-content div.hideCls").hide(); //Hide all content
                $("#tabs li").attr("id",""); //Reset id's
                $(this).parent().attr("id","current"); // Activate this
                $('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
            });




                //ajax demo fn
                $("a[rel='load-content']").click(function(e){

                    e.preventDefault();
                    var $this=$(this),
                        url=$this.attr("href");
                    $this.addClass("loading");
                    $.get(url,function(data){
                        $this.removeClass("loading");
                        $("ul.scrollClass .mCSB_container").html(data); //load new content inside .mCSB_container
                        $("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly loaded content
                        $("ul.scrollClass").mCustomScrollbar("scrollTo","top",{scrollInertia:200}); //scroll to top
                    });
                });
                $("a[rel='append-content']").click(function(e){
                    e.preventDefault();
                    var $this=$(this),
                        url=$this.attr("href");
                    $this.addClass("loading");
                    $.get(url,function(data){
                        $this.removeClass("loading");
                        $("ul.scrollClass .mCSB_container").append(data); //append new content inside .mCSB_container
                        $("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly appended content
                        $("ul.scrollClass").mCustomScrollbar("scrollTo","h2:last",{scrollInertia:2500,scrollEasing:"easeInOutQuad"}); //scroll to appended content
                    });
                });
            });
        })(jQuery);
    </script>

     <!-- custom swipebox plugin -->
    <script src="/memreas/js/jquery.swipebox.min.js"></script>
    <script type="text/javascript">
        jQuery(function($) {
            $(".swipebox").swipebox();
        });
    </script>


</body>
</html>
