
<!-- Begin : Header -->
<div class="row-fluid">
<header>
  <h1 id="logo"><a href="index.html">memreas</a></h1>
  <input name="input"type="text" class="search_bar" value="@person, #discover" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover')this.value = '';"/>
  <a href="notifications.html" class="notification_icon"></a>
  <div class="pro-info">
	<figure class="pro-pic"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
	<div class="pro-name">User Name</div>
  </div>
</header>
</div>
<!-- End : Header -->

