<?php
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');
$username = $session->offsetGet('username');
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";
?>

<!-- Begin : Header -->
<div class="row-fluid">
	<header>
		<div class="container">
        <div class="header-inner">
			<h1 id="logo"><a href="">memreas</a></h1>

			<div class="search-sec">
				<div class="relative">
					<input data-provide="typeahead" id="search" name="input"type="text" class="search_bar" value="@person, #discover, !memreas" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover, !memreas')this.value = '';"/>
					<span class="clear"></span>
				</div>
			</div>
			<div class="pro-info clicker">
				<div class="noti left"><a href="javascript:;" class="notification_icon"></a></div>
				<div class="right">
					<figure class="pro-pic"><img id="profile_picture" src="/memreas/img/profile-pic.jpg" alt=""><span id="noti">2</span></figure>
					<div class="pro-name">Username</div>

					<div class="drop-inner click-nav">
						<ul class="no-js">
							<li>
								<ul>
									<li class="drop-1"><a href="/">HOME</a></li>
									<li class="drop-2"><a href="">Notification</a>
										<div class="notifications-all clearfix" >
											<div class="noti-title"><strong>Scrat</strong> said on <span>06.25.2014</span>
											</div>
											<div class="noti-content">
												<p>This is Photoshop's version of Lorem ipsum prion gravida nibbe vei</p>
											</div>
											<a href="#" class="close">x</a>
											<a href="#" class="reply">reply</a>
										</div>
										<div class="notifications-all clearfix" >
											<div class="noti-title"><strong>Scrat</strong> said on <span>06.25.2014</span>
											</div>
											<div class="noti-content">
												<p>This is Photoshop's version of Lorem ipsum prion gravida nibbe vei</p>
											</div>
											<a href="#" class="close">x</a>
											<a href="#" class="reply">reply</a>
										</div>
									</li>
									<li class="drop-3"><a href="">More</a></li>
									<li class="drop-4"><a href="">Log Out</a></li>
								</ul>	
							</li>
						</ul>
						<span></span>
					</div>
				</div>
				<span class="clear"></span>
			</div>
        </div>
	  </div>
	</header>
</div>
<!-- End : Header -->

