<?php
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');
$username = $session->offsetGet('username');
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";
?>

<!-- Begin : Header -->
<div class="row-fluid">
<header>
  <h1 id="logo"><a href="/index/gallery">memreas</a></h1>
  <input name="input"type="text" class="search_bar" value="@person, #discover" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover')this.value = '';"/>
  <a href="javascript:;" class="notification_icon"></a>
  <div class="pro-info">
	<figure class="pro-pic"><img id="profile_picture" src="/memreas/img/profile-pic.jpg" alt=""></figure>
	<div class="pro-name"><?php echo $username; ?></div>
  </div>
</header>
</div>
<!-- End : Header -->

