<?php
use Zend\Session\Container;
header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1.
header('Pragma: no-cache'); // HTTP 1.0.
header('Expires: 0'); // Proxies.
$session = new Container('user');
$user_id = $session->offsetGet('user_id')
?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/transtyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/davidstyle.css" rel="stylesheet" type="text/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link href="/memreas/css/fotorama.css" rel="stylesheet">
<link rel="stylesheet" href="/memreas/css/swipebox.css">

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<!-- JW Player plugin -->
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.js"></script>
<script type="text/javascript" src="/memreas/js/jwplayer/jwplayer.html5.js"></script>

<!--jQuery Lybrary-->
<script src="/memreas/js/jquery.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="/memreas/js/jquery.cookie.js"></script>

<!-- Fotorama -->
<script src="/memreas/js/fotorama.js"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>

<!--Backgound Strecher-->
<script type="text/javascript" src="/memreas/js/jquery.xml2json.js"></script>
<script type="text/javascript" src="/memreas/js/fetchLocalMedia.js"></script>
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<script type="text/javascript" src="/memreas/js/serverSide.js"></script>
<script type="text/javascript" src="/memreas/js/syncing.js"></script>
<script type="text/javascript" src="/memreas/js/ajax.js"></script>
<script type="text/javascript">

$(document).ready(function(){
    //Prefetch for image location
    $.fetch_server_media('<?php echo $user_id; ?>');
    $.addfile();
    $(document).bgStretcher({
            images: ['img/bg.jpg'],
            imageWidth: 1366, imageHeight: 700
    });
    $(".change-location a.browse-server").click (function(){ $.fetch_server_media($("input[name=current_user_id]").val()); });
    $(".change-location a.fetch-local").click (function(){ $(".browse-file").fadeIn (500); });
});
</script>
</head>
<body>
<!-- Begin : Container -->
<div class="container">
  <?php include 'header.phtml'; ?>
  <!-- Begin : Content -->
      <div class="row-fluid content" style="background: #185EB3;">
      <div class="span1">
          <!-- Begin : Nav -->
          <nav>
          <ul>
            <li><a href="#" class="active"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="#"><img src="/memreas/img/more.png" alt=""></a></li>
          </ul>
        </nav>
        <!-- End : Nav -->
      </div>
      <div class="span11">
      <div class="span9 content">
        <!-- DYNAMIC CONTENT GOES HERE -->
      </div>
      <div class="span3">
          <section id="ad">
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
          <div class="adbox-port">Your <br>Advertisement <br>space </div>
        </section>
      </div>
      <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
      <div class="row-fluid">
          <!-- <input type="local_directory" class="hidden-input" webkitdirectory> -->
          <!-- <input type="file" id="local_directory" webkitdirectory="" directory=""> -->
      </div>
      </div>
    </div>
  <!-- End : Content -->
</div>
<?php include 'footer.phtml'; ?>
<!-- End : Container --> 
</body>
</html>