<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php
use Application\Model\MemreasConstants;
?>
<!doctype html>
<html lang="en" class="no-js">
<head>

<meta name="description" content="<?php echo MemreasConstants::MEMREAS_DESCRIPTION ?>">
<meta name="keywords" content="<?php echo MemreasConstants::MEMREAS_KEYWORDS ?>">
<title>memreas moving to open source project</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--meta responsive-->
<!-- Mark update -->
<link rel="stylesheet" type="text/css" href="/memreas/css/reset.css">
<link rel="stylesheet" type="text/css" href="/memreas/css/bootstrap.css">
<link rel="stylesheet" type="text/css"
    href="/memreas/css/responsiveslides.css">
<link rel="stylesheet" type="text/css" href="/memreas/css/register.css">
<link rel="shortcut icon" href="/memreas/img/icon.png" />
<!-- HTML5 shim for IE backwards compatibility -->
<!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<!-- End Mark update -->
<script src="/memreas/js/jquery-register.js"></script>
</head>

<body>
    
    
    <header class="rel">
        <div class="container">
            <div class="header-inner">
                <h1 id="logo">
                    <a href="">memreas</a>
                </h1>
            </div>
        </div>
    </header>
    <section id="MobileHomeScreen" style="overflow: hidden;">
    
    <div class="row-fluid">
        <div class="span12">
            <div class="span12">
                <div style="text-align: center; margin: 20px 0;">
                     <h1 style="font-family: 'Century Gothic'; text-transform: initial!important;">memreas moving to open source project  <br /> site will end services August 31, 2017.</h1>
                </div>
                <div class="relative feature" style="min-height: auto;">
                    <div class="film film-phone" style="margin: 0 auto; height: 280px;">

                        <div id="slider">
                            <ul class="rslides">
                                <li><img src="/memreas/img/slide-1-3.png" alt="Beach Party"></li>
                                <li><img src="/memreas/img/slide-1-1.png" alt="Fireworks"></li>
                                <li><img src="/memreas/img/slide-1-2.png" alt="Wedding"></li>
                            </ul>
                        </div>
                        <div class="filminner"></div>
                        <img src="/memreas/img/logo2.png" class="imabsolute" />
                    </div>


                </div>
            </div>

        </div>
    </div>

    </section>
   

    <!-- Modal JS -->

    <script src="/memreas/js/responsiveslides.min.js"></script>
	<script src="/bower_components/jquery-ui/jquery-ui.min.js"></script>

    <script>
            $(function() {
                $(".rslides").responsiveSlides();
                
                $('#SignupReg').click(function(){
                    $('#MobileHomeScreen').hide();
                    $('.mobileReform').show();
                    
                });
            });
        </script>
     
   
        
</body>
</html>
