<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php
/*
use Application\Model\MemreasConstants;
header ( 'Cache-Control: no-cache, no-store, must-revalidate' ); // HTTP 1.1.
header ( 'Pragma: no-cache' ); // HTTP 1.0.
header ( 'Expires: 0' ); // Proxies.
header ( 'Access-Control-Allow-Origin: *' );
header ( "Access-Control-Allow-Methods: POST, GET" );
header ( "Access-Control-Allow-Headers: x-requested-with" );
*/
?>
<!doctype html>
<html lang="en" class="no-js">
<head>

<meta name="description" content="PUT YOUR Description here">
<meta name="keywords" content="PUT YOUR Keyword here">
<title>Under Maintenance</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--meta responsive-->
<!-- Mark update -->
<link rel="stylesheet" type="text/css" href="/memreas/css/reset.css">
<link rel="stylesheet" type="text/css" href="/memreas/css/bootstrap.css">
<link rel="stylesheet" type="text/css"
	href="/memreas/css/responsiveslides.css">
<link rel="stylesheet" type="text/css" href="/memreas/css/register.css">
<link href="/memreas/css/modalPopLite.css" rel="stylesheet"
	type="text/css" />
<link rel="shortcut icon" href="img/icon.png" />
<!-- HTML5 shim for IE backwards compatibility -->
<!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<!-- End Mark update -->
<link rel="stylesheet" href="/memreas/css/jNotify.jquery.css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<script src="js/jquery-register.js"></script>
</head>

<body>
    
    
    <header class="rel">
		<div class="container">
			<div class="header-inner">
				<h1 id="logo">
					<a href="">memreas</a>
				</h1>
			</div>
		</div>
    </header>
    <section id="MobileHomeScreen" style="overflow: hidden;">
    
    <div class="row-fluid">
        <div class="span12">
            <div class="span12">
            	<div style="text-align: center; margin: 20px 0;">
		             <h1 style="font-family: 'Century Gothic'; text-transform: inherit;">Sorry this Page is currently Under Maintenance</h1>
		        </div>
                <div class="relative feature" style="min-height: auto;">
                    <div class="film film-phone" style="margin: 0 auto;">

                        <div id="slider">
                            <ul class="rslides">
                                <li><img src="img/slide-1-3.png" alt="Beach Party"></li>
                                <li><img src="img/slide-1-1.png" alt="Fireworks"></li>
                                <li><img src="img/slide-1-2.png" alt="Wedding"></li>
                            </ul>
                        </div>
                        <div class="filminner"></div>
                        <img src="img/logo2.png" class="imabsolute" />
                    </div>


                </div>
            </div>

        </div>
    </div>
    
    

    

    </section>
   
     <!--**********Mobile Login Layout************** -->
     
   
        
</body>
</html>
