<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php

use Application\Model\MemreasConstants;
header ( 'Cache-Control: no-cache, no-store, must-revalidate' ); // HTTP 1.1.
header ( 'Pragma: no-cache' ); // HTTP 1.0.
header ( 'Expires: 0' ); // Proxies.
header ( 'Access-Control-Allow-Origin: *' );
header ( "Access-Control-Allow-Methods: POST, GET" );
header ( "Access-Control-Allow-Headers: x-requested-with" );


//$user_id = ! empty ( $_SESSION ['user_id'] ) ? ($_SESSION ['user_id']) : '';
//$username = ! empty ( $_SESSION ['username'] ) ? ($_SESSION ['username']) : '';
//Session timeout
if (isset($_SESSION['LAST_ACTIVITY']) && (time() - $_SESSION['LAST_ACTIVITY'] > 1800)) {
	// last request was more than 30 minutes ago
	session_unset();     // unset $_SESSION variable for the run-time
	session_destroy();   // destroy session data in storage
}
$_SESSION['LAST_ACTIVITY'] = time(); // update last activity time stamp

?>
<!doctype html>
<?php if ($this->enableAdvertising) : ?>
<html class="ads">
<?php else: ?>

<html class="noads">
<?php endif; ?>
<head>
<?php
// javascript constants
$constants = "<script>";
$constants .= "var S3BUCKET = '" . MemreasConstants::S3BUCKET . "';";
$constants .= "var LOGGED_USER_ID = '" . $_SESSION ['user_id'] . "';";
$constants .= "var LISTNOTIFICATIONSPOLLTIME = '" . MemreasConstants::LISTNOTIFICATIONSPOLLTIME . "';";
$constants .= "var GALLERYDELAYTIME = '" . MemreasConstants::GALLERYDELAYTIME . "';";
$constants .= "var FREE_ACCOUNT_FILE_LIMIT = '" . MemreasConstants::FREE_ACCOUNT_FILE_LIMIT . "';";
$constants .= "var PAID_ACCOUNT_FILE_LIMIT = '" . MemreasConstants::PAID_ACCOUNT_FILE_LIMIT . "';";
$constants .= "var CLOUDFRONT_DOWNLOAD_HOST = '" . MemreasConstants::CLOUDFRONT_DOWNLOAD_HOST . "';";
$constants .= "var STRIPE_SERVER_URL = '" . MemreasConstants::MEMREAS_PAY . "';";
$constants .= "var ENABLE_SELL_MEDIA = '" . MemreasConstants::MEMREAS_SELL_MEDIA . "';";
$constants .= "var SEARCH_MIN_LENGTH = 1;";
$constants .= "</script>";
echo $constants;
?>
<meta charset="utf-8">
<meta name="viewport"
	content="user-scalable-no,initial-scale=1.0, minimum-scale=1.0,maximum-scale=1.0">
<title>memreas</title>

<script type="text/javascript">
<?php
if (! empty ( $_SESSION )) {
	$user_id = $_SESSION ['user_id'];
	$username = $_SESSION ['username'];
}
echo "var user_id = '" . $user_id . "';";
echo "var username = '" . $username . "';";
?>

			<?php if (!empty($this->CloudFrontPolicy)) { ?>
			console.log("$this->CloudFrontPolicy is not empty!!");
			console.log("cookies set...");
			console.log(document.cookie);
			<?php } ?>
		</script>	
        <?php include('onepage/css_section.phtml'); ?>
        <?php include('onepage/js_head.phtml'); ?>
    </head>

<body>
	<div id="loadingpopup" class="loadingpopup">
		<div id="loadingpopupinner" class="loadingpopupinner">
			<img id="loadingimg" src="/memreas/img/loading_animate.gif">
		</div>
	</div>

	<div id="popupAudioComment" class="popups voice-comment-load">
		<a id="popupAudioCommentClose"
			onClick="disablePopup('popupAudioComment');" class='popupClose'>x</a>
		<h2>comments</h2>
		<div style="text-align: center; position: relative;"
			class="audio-control">
			<img src="/memreas/img/audio-comment.jpg"
				style="width: 400px; margin-top: 20px; margin-bottom: 20px;" />
			<div class="control-buttons">
				<a class="button-start-stop" href="javascript:voiceCommentStart();"><img
					src="/memreas/img/audio-start.png" border="0" /></a> <span
					class="recording-timer">00:00</span>
			</div>
		</div>
		<div style="text-align: center;">
			<a class="black_btn_skin" href="javascript:completeComment();">Ok</a>
			&nbsp; <a class="black_btn_skin"
				href="javascript:voiceCommentCancel();">Cancel</a>
		</div>
	</div>
	<div id="bgpopupAudioComment" class="backgroundPopup"></div>

	<input type="hidden" name="user_id" value="<?php echo $user_id; ?>">
	<input type="hidden" name="username" value="<?php echo $username; ?>">
            <?php include 'onepage/header.phtml'; ?>
        <!-- Begin : Container -->
	<div class="container clearfix top20">

		<!-- Begin : Content - For Tab-->
		<div class="row-fluid content">
                <?php include('onepage/nav.phtml'); ?>

                <!-- Main Tab Content -->
			<div id="maintab-content">
				<!-- Begin : Content - For search -->
                    <?php include('onepage/search.phtml'); ?>
                    <!-- End : search -->

				<!-- Begin : Content - For notification -->
                    <?php include('onepage/notification.phtml'); ?>
                    <!-- End : Notification -->

				<!-- Gallery Main Tab -->
                    <?php include('onepage/gallery.phtml'); ?>
                    <!-- End: Gallery Main Tab -->

				<!-- Queue Main Tab -->
                    <?php include ('onepage/queue.phtml'); ?>
                    <!-- End: Queue Main Tab -->

				<!-- Share Main Tab -->
                    <?php include ('onepage/share.phtml'); ?>
                    <!-- End : Share Main Tab -->

				<!-- Memreas Main Tab -->
                    <?php include ('onepage/memreas.phtml'); ?>
                    <?php include ('onepage/memreas_detail.phtml'); ?>
                    <!-- End : Memreas Main Tab -->

				<!-- More Tab -->
				<?php include ('onepage/more_page.phtml'); ?>
				<!-- End : More Tab -->
			</div>
			<!-- End: Main Tab Content -->
			<div class="clear"></div>
		</div>

	</div>
	<!-- End : Content -->
	</div>
	<!-- Bottom Ads -->
    <?php include('onepage/bottom_advertising.phtml'); ?>
    <!-- End Bottom Ads -->

        
    <?php include 'onepage/footer.phtml'; ?>
    <?php include('onepage/js_section.phtml'); ?>
    <!-- End : Container -->
	<script src="/memreas/js/main.js"></script>
	<div style="clear: both;"></div>
	<img src="" style="display: none;" id="temp-aviary-img" />
</body>
</html>
