<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<?php

use Application\Model\MemreasConstants;
header ( 'Cache-Control: no-cache, no-store, must-revalidate' ); // HTTP 1.1.
header ( 'Pragma: no-cache' ); // HTTP 1.0.
header ( 'Expires: 0' ); // Proxies.
header ( 'Access-Control-Allow-Origin: *' );
header ( "Access-Control-Allow-Methods: POST, GET" );
header ( "Access-Control-Allow-Headers: x-requested-with" );
?>
<!doctype html>
<html lang="en" class="no-js">
<head>

<meta name="description" content="PUT YOUR Description here">
<meta name="keywords" content="PUT YOUR Keyword here">
<title>memreas - Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--meta responsive-->
<!-- Mark update -->
<link rel="stylesheet" type="text/css" href="/memreas/css/reset.css">
<link rel="stylesheet" type="text/css" href="/memreas/css/bootstrap.css">
<link rel="stylesheet" type="text/css"
	href="/memreas/css/responsiveslides.css">
<link rel="stylesheet" type="text/css" href="/memreas/css/register.css">
<link href="/memreas/css/modalPopLite.css" rel="stylesheet"
	type="text/css" />
<link rel="shortcut icon" href="/memreas/img/icon.png" />
<!-- HTML5 shim for IE backwards compatibility -->
<!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<!-- End Mark update -->
<link rel="stylesheet" href="/memreas/css/jNotify.jquery.css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<script src="/memreas/js/jquery-register.js"></script>
</head>

<body>
    
    
    <header class="rel">
		<div class="container">
			<div class="header-inner">
				<h1 id="logo">
					<a href="">memreas</a>
				</h1>
			</div>
		</div>
    </header>
    <section id="MobileHomeScreen">
    
    <div class="row-fluid">
        <div class="span12">
            <div class="span12">
                <div class="relative feature" style="min-height: auto;">
                    <div class="film film-phone" style="margin: 0 auto;">

                        <div id="slider">
                            <ul class="rslides">
                                <li><img src="/memreas/img/slide-1-3.png" alt="Beach Party"></li>
                                <li><img src="/memreas/img/slide-1-1.png" alt="Fireworks"></li>
                                <li><img src="/memreas/img/slide-1-2.png" alt="Wedding"></li>
                            </ul>
                        </div>
                        <div class="filminner"></div>
                        <img src="/memreas/img/logo2.png" class="imabsolute" />
                    </div>


                </div>
            </div>

        </div>
    </div>
    
    

    
    
    
    <div class="row-fluid">
        <div class="span12" style="text-align: center; margin-bottom: 10px;">
	        <div class="mobile-content" id="Android">
			     You will receive an email to verify your email address. You can download our APK for Android via this link  <a href="http://www.memreas.com/android">http://www.memreas.com/android</a>
		     </div>
	        <div class="mobile-content" id="iOS">
			     You will receive an email to verify your email address. if you would like to join the iOS beta test please email admin@memreas.com with subject TestFlight Access.
		     </div>
	        <div class="mobile-content" id="unknown">
			     You will receive an email to verify your email address
		     </div>
	        <p>&nbsp;</p>
            <input type="button" onclick=""  id="SignupReg" class="btn btn-lyt create-accnt" value="Sign Up" style="width: 96%;">
        </div>
    </div>
    </section>
   
     <!--**********Mobile Login Layout************** -->
     <!--**********Mobile Registration Layout************** -->
     

    
    <div class="row-fluid mobileReform" style="display: none;">
        <div class="span12">
           <div class="signup">
							
							<div class="profile clearfix mobile-profile">
								<figure class="profile_picture">
									<output id="list"></output>
								</figure>
                                                            <div class="btn-lg file relative" style="float:left;margin-top: 0px;">
									<input type="hidden" name="profile_image" value="0">
									<form name="frm_profile_pic" id="frm-profile-pic"
										class="direct-upload" enctype="multipart/form-data"
                                                                                action="https://<?php echo $data['bucket']; ?>.s3.amazonaws.com/">
										<input type="hidden" name="key" value="{$filename}"> <input
											type="hidden" name="Content-Type" value=""> <input
											type="hidden" name="acl" value=""> <input type="hidden"
											name="success_action_status" value=""> <input type="hidden"
											name="policy" value=""> <input type="hidden"
											name="x-amz-algorithm" value=""> <input type="hidden"
											name="x-amz-credential" value=""> <input type="hidden"
											name="x-amz-date" value=""> <input type="hidden"
											name="x-amz-expires" value=""> <input type="hidden"
											name="x-amz-signature" value=""> <input type="hidden"
											name="x-amz-server-side-encryption" value="AES256"> <input
											class="" id="file" type="file" name="file">
									</form>
									<input type="hidden" name="register_user_id" value="" /> <span
										class="absolute">choose profile picture</span>
								</div>
							</div>
							<form enctype="multipart/form-data"
								action="<?php echo $this->url('index',array('action'=>'registration'));?>"
								method="post" name="register" id="register"
								onsubmit="return validateRegstration();" class="mobile-form">
								<label for="email" class="textlabel">email</label> <input name="email"
									id="inEmail" type="email" placeholder="Your Email"
									onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
									onFocus="if(this.value == 'Your Email')this.value = '';" /> <label
									for="username" class="textlabel">username</label> <input name="username"
									type="text" id="inUserName" placeholder="Your Username"
									onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
									onFocus="if(this.value == 'User Name')this.value = '';" /> <label
									for="password" class="textlabel">password</label>
								<div class="password">
									<input maxlength="32" name="password" id="inPassword"
										type="password" placeholder="Password"
										onFocus="if(this.value == 'Password')this.value = '';"
										onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" /><span
										class="password-level"></span>
								</div>
								<label for="inVerifyPassword"class="textlabel" >verify password</label> <input
									name="verifypassword" id="inVerifyPassword" type="password"
									placeholder="Verify Password"
									onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
									onFocus="if(this.value == 'Verify Password')this.value = '';" />
<!--								<label for="invited_by" class="event-name">!event name</label> -->
<input type="hidden" name="secrete_title" id="secrete_title"  />  
                                                                <input
									name="invited_by" id="invited_by" class="signup_textfields"
									type="text" value="invited by @person (optional)"
									onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue"
									onFocus="if(this.value == 'invited by @person (optional)')this.value = '';"
									style="display: none;"> <input type="checkbox"
									class="css-checkbox" id="demo_box_2" name="legal_agree"> <label
									class="css-label" for="demo_box_2"><a
									onclick="popup('popupContact');" href="javascript:;"
									class="legal clicker-1" id="button">terms of service</a></label>
								<input type="submit" id="btnCall"
									class="btn btn-lyt create-accnt" value="Create an account">
							</form>
						</div>

        </div>
    </div>
    
    

    
    
   
    
   
    <div class="row-fluid">
        <div class="span12" style="text-align: center;">
            <p>&copy; memreas llc  2016.</p>
            
        </div>
        
    </div>
     
     
     <!--**********Mobile Registration Layout************** -->
	<div id="loadingpopup">
		<div id="loadingpopupinner">
			<img id="loadingimg" src="/memreas/img/loading.gif"> <span
				id="loadingtext">Please wait...</span>
		</div>
	</div>
	

	<!--Body Starts Here-->


	
	<!--Body Ends Here-->

	<!--Footer-->
	
	<!--End of Footer-->

	<!-- Overlay splash -->
	<div class="splash">
		<div class="pull-left filmstrip">
			<div class="relative feature">
				<div class="film absolute">
					<img src="/memreas/img/memreas-alpha.png" alt="Film Strip"
						style="width: 100%;">
				</div>
				<div id="slider" class="absolute">
					<ul class="rslides">
						<li><img src="/memreas/img/slide-3.png" alt="Beach Party"></li>
						<li><img src="/memreas/img/slide-1.png" alt="Fireworks"></li>
						<li><img src="/memreas/img/slide-2.png" alt="Wedding"></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- overlay splash ends here -->

	<!-- Modal JS -->
	<script type="text/javascript" src="/memreas/js/modalPopLite.min.js"></script>
	<script src="/memreas/js/responsiveslides.min.js"></script>
	<script src="/memreas/js/jNotify.jquery.min.js"></script>
	<script type="text/javascript" src="/memreas/js/global.js"></script>
	<script type="text/javascript" src="/memreas/js/ajax.js"></script>
	<script src="/memreas/js/jquery-ui.min.js"></script>
	<script src="/memreas/assets/js/jquery.iframe-transport.js"></script>
	<script src="/memreas/assets/js/jquery.fileupload.js"></script>
	<script type="text/javascript" src="/memreas/js/registration.js"></script>
	<script src="/memreas/js/popup.js" type="text/javascript"></script>
	<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script>
            $(function() {
                $(".rslides").responsiveSlides();
                
                $('#SignupReg').click(function(){
                    $('#MobileHomeScreen').hide();
                    $('.mobileReform').show();
                    
                });
            });
        </script>

	<!--Script for File-->
	<script>
        <?php
								
								if (isset ( $_GET ['email_verified'] ) && $_GET ['email_verified'] == 1) {
									echo "jsuccess('Your account has been verified successfully');";
								}
								if (isset ( $_GET ['credits_activated'] ) && $_GET ['credits_activated'] == 1) {
									echo "jsuccess('Your account has been credited. Enjoy!');";
								}
								if (isset ( $_GET ['email_verified'] ) && $_GET ['email_verified'] == 0) {
									echo "jerror('Your account has not been verified');";
								}
								if (isset ( $_GET ['credits_already_activated'] ) && $_GET ['credits_already_activated'] == 1) {
									echo "jsuccess('These credits were applied in a prior activation.');";
								}
								?>
            if (window.FileReader) {
                function handleFileSelect(evt) {
                    var files = evt.target.files;
                    var f = files[0];
                    var reader = new FileReader();

                    reader.onload = (function(theFile) {
                        return function(e) {
                            document.getElementById('list').innerHTML = ['<img src="', e.target.result,'" title="', theFile.name, '" style="width: 75px; height: 75px;" />'].join('');
                        };
                    })(f);

                    reader.readAsDataURL(f);
                }
                //document.getElementById('file').addEventListener('change', handleFileSelect, false);
                $(function(){
                    $("#file").change(handleFileSelect);
                });
            } else {
                jerror('This browser does not support FileReader! Preview will not available');
            }


            


            if(window.innerWidth <= 600){
                window.addEventListener('load', splash); 
            } else {
                $('.splash').css({'display':'none'});
            }


            function splash() {
                var filmstrip =  $('.splash .filmstrip.pull-left');
                var filmstripHeight = filmstrip.height();
                filmstrip.css({
                    "top": (window.innerHeight - filmstripHeight)/2+ 'px'
                });
                filmstrip.show();
                setTimeout(function  () {
                    $('.splash').fadeOut('normal');
                    $('.splash').remove();
                },2000); // setTimeout
            } // splash


          
        </script>
	<script type="text/javascript" charset="utf-8">
            jQuery('#file').css('opacity',0);
            $(function(){
	            var mobile_device = getMobileOperatingSystem();
	            $("#" + mobile_device).fadeIn(500);
            });
        </script>
	<!--End Script for File-->
        
        
</body>
</html>
