<?php
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";
?>

<!-- Begin : Nav -->
<div class="span1" id="main-tab">
    <nav>
        <ul>
            <li><a href="javascript:;" class="gallery active" title="gallery" onclick="return false;"><img src="/memreas/img/gallery.png" alt=""></a></li>
            <li><a href="javascript:;" class="queue" title="queue" onclick="return false;"><img src="/memreas/img/queue.png" alt=""></a></li>
            <li><a href="javascript:;" class="share" title="share"><img src="/memreas/img/share.png" alt=""></a></li>
            <li><a href="javascript:;" class="memreas" title="memreas"><img src="/memreas/img/memreas.png" alt=""></a></li>
            <li><a href="javascript:;" class="more" title="more"><img src="/memreas/img/more.png" alt=""></a></li>
        </ul>
    </nav>
</div>
<!-- End : Nav -->
