<?php 
/////////////////////////////////
// Author: David Kang
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');        
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";
?>

<!-- Begin : Nav -->
<div class="span1">
	<nav>
	  <ul>
		<li><a href="gallery.html"><img src="/memreas/img/gallery.png" alt=""></a></li>
		<li><a href="queue.html"><img src="/memreas/img/queue.png" alt=""></a></li>
		<li><a href="share.html" class="active"><img src="/memreas/img/share.png" alt=""></a></li>
		<li><a href="memreas-me-friends.html"><img src="/memreas/img/memreas.png" alt=""></a></li>
		<li><a href="more.html"><img src="/memreas/img/more.png" alt=""></a></li>
	  </ul>
	</nav>
</div>
<!-- End : Nav -->
