<?php

use Application\Model\MemreasConstants;

header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1.
header('Pragma: no-cache'); // HTTP 1.0.
header('Expires: 0'); // Proxies.
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Methods: POST, GET");
header("Access-Control-Allow-Headers: x-requested-with");
?>
<!doctype html>
<html lang="en" class="no-js">
    <head>

        <meta name="description" content="PUT YOUR Description here">
        <meta name="keywords" content="PUT YOUR Keyword here">
        <title>memreas - public page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--meta responsive-->
        <!-- Mark update -->
        <link rel="stylesheet" type="text/css" href="/memreas/css/reset.css">
        <link rel="stylesheet" type="text/css" href="/memreas/css/bootstrap.css">
        <link rel="stylesheet" type="text/css"
              href="/memreas/css/responsiveslides.css">
        <link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />

        <link href="/memreas/css/style.css" rel="stylesheet" type="text/css">

        <link rel="stylesheet" type="text/css" href="/memreas/css/register.css">
        <link rel="shortcut icon" href="/memreas/img/icon.png" />
        <!-- HTML5 shim for IE backwards compatibility -->
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
                <![endif]-->
        <!-- End Mark update -->
        <script src="/memreas/js/jquery-register.js"></script>
    </head>

    <body>


        <header class="rel">
            <div class="pull-right" style="width: auto; margin-right: 10px;">
                <input type="button" onclick="{window.location= '/index';}" value="log in" name="log in" class="btn btn-sm login-btn" style="margin-right: 10px;">
                <input type="button" onclick="{window.location= '/index';}" value="Register" name="log in" class="btn btn-sm login-btn">
            </div>
            <div class="container">
                <div class="header-inner">

                    <h1 id="logo" style="float: none;">
                        <a href="" style="height: auto;">memreas</a>
                    </h1>
                </div>
            </div>
        </header>
        <section id="MobileHomeScreen" style="overflow: hidden; background: #193D65; padding-left: 15px; padding-top: 15px;">
            <div class="row-fluid">
                <div class="span9">
                    <ul class=" scrollClass  publicMemreas scroll-area mCustomScrollbar _mCS_9 _mCS_16">
                        <li>
                            <div class="event_section">
                                <section class="row-fluid clearfix">
                                    <figure class="pro-pics2"><img class="public-profile-img" src="https://d3sisat5gdssl6.cloudfront.net/static/profile-pic.jpg?Expires=1460475591&amp;Signature=SSj~2qX19toFZGaf8GZS2paWoP8Ikj0zyXaWzQbU4YYzNpj0V0zkjKdScztZ1enY246RaICv-kDDipfX-VORal5DLdY-dqbHsQ~Z~UcNUS8vUxM2Q1FV9lF0GBzvmKhf7LzFGagssRljtDtwOrkheogHEel3gKA5U5h0Pr7MZBuQ-bUwtEN0y00DKw06JLTFqEjCpeXobqyyuFj~-1-z7qGITJXF~WQ~YwIyRP59OU8P4JMyDmgDtbEDTF6QxJd2U-x1t8y9Sd~cwQc2fW7vQBwWMVok8ezI0kxhiVaTbT5-Ly4eGU2djE9443wlKV1XYHEi6hOMOEFCT0dZXYlk-Q__&amp;Key-Pair-Id=APKAISSKGZE3DR5HQCHA" alt=""></figure>
                                    <aside class="pro-names2" style="margin-top:0px;">@glenn12 : !test1234</aside>
                                    <a href="javascript:;" title="Like media" class="memreas-detail-likecount" style="margin-left:10px;"><img src="/memreas/img/like.png" alt=""></a><span style="position: relative;top: -10px;left: -17px;color: #fff;">1</span><a href="javascript:;" title="Comment" style="position: relative;top:5px;"><img src="/memreas/img/comment.png" alt=""></a><span style="position: relative;top: -8px;left: -19px;color: #fff;">1</span>
                                    <div style="clear:both;"></div>
                                    <ul class="event-pics">
                                        <li class="image"><a href="javascript:;"  style="cursor: pointer;"><img src="https://d3sisat5gdssl6.cloudfront.net/d94e8835-5379-4c55-bbc4-3c3028c433bc/d1f70c59-cc09-4495-b967-5137eb8eb6c3/thumbnails/448x306/IMG_8090.JPG?Expires=1460475701&amp;Signature=KyXoB8D2S0Vt9kfmDfxt8AsqVqK7kOIRZY0mkmN2TXmpqiK0PQibXtsskvzu6st16dp4iiBXi3tXn6hnzjuNE~T~wsyB3DtQUHpd110RHt25Ur3ET5MhLXn-5uQtSbemkSpw7WaKisRwRakRfiMquWqiXOvJ-aZAzTlJnrV09YMCt7Jf3eyxGB4SSZWmE3rRP7MyvBFz4VDqimMeozG20Zzi2hTLL3H8dgjD5w7fET49b~Kofhc9zGz-GkWlXHxRSM0PmG8uZOJazvlrhxqDIeFQw-GcO0DXQnz3lqOrVa3GFjaZ3nNeIArUb6yfR-g3nu2JwKCGPSZZgnJBi23Zrw__&amp;Key-Pair-Id=APKAISSKGZE3DR5HQCHA" style=""></a></li>
                                        <li class="image"><a href="javascript:;"  style="cursor: pointer;"><img src="https://d3sisat5gdssl6.cloudfront.net/d94e8835-5379-4c55-bbc4-3c3028c433bc/d1f70c59-cc09-4495-b967-5137eb8eb6c3/thumbnails/448x306/IMG_8090.JPG?Expires=1460475701&amp;Signature=KyXoB8D2S0Vt9kfmDfxt8AsqVqK7kOIRZY0mkmN2TXmpqiK0PQibXtsskvzu6st16dp4iiBXi3tXn6hnzjuNE~T~wsyB3DtQUHpd110RHt25Ur3ET5MhLXn-5uQtSbemkSpw7WaKisRwRakRfiMquWqiXOvJ-aZAzTlJnrV09YMCt7Jf3eyxGB4SSZWmE3rRP7MyvBFz4VDqimMeozG20Zzi2hTLL3H8dgjD5w7fET49b~Kofhc9zGz-GkWlXHxRSM0PmG8uZOJazvlrhxqDIeFQw-GcO0DXQnz3lqOrVa3GFjaZ3nNeIArUb6yfR-g3nu2JwKCGPSZZgnJBi23Zrw__&amp;Key-Pair-Id=APKAISSKGZE3DR5HQCHA" style=""></a></li>
                                        <li class="image"><a href="javascript:;"  style="cursor: pointer;"><img src="https://d3sisat5gdssl6.cloudfront.net/d94e8835-5379-4c55-bbc4-3c3028c433bc/d1f70c59-cc09-4495-b967-5137eb8eb6c3/thumbnails/448x306/IMG_8090.JPG?Expires=1460475701&amp;Signature=KyXoB8D2S0Vt9kfmDfxt8AsqVqK7kOIRZY0mkmN2TXmpqiK0PQibXtsskvzu6st16dp4iiBXi3tXn6hnzjuNE~T~wsyB3DtQUHpd110RHt25Ur3ET5MhLXn-5uQtSbemkSpw7WaKisRwRakRfiMquWqiXOvJ-aZAzTlJnrV09YMCt7Jf3eyxGB4SSZWmE3rRP7MyvBFz4VDqimMeozG20Zzi2hTLL3H8dgjD5w7fET49b~Kofhc9zGz-GkWlXHxRSM0PmG8uZOJazvlrhxqDIeFQw-GcO0DXQnz3lqOrVa3GFjaZ3nNeIArUb6yfR-g3nu2JwKCGPSZZgnJBi23Zrw__&amp;Key-Pair-Id=APKAISSKGZE3DR5HQCHA" style=""></a></li>
                                    </ul>
                                    <div style="clear:both;"></div>
                                </section>
                                <div id="viewport" class="mouse_swip" onselectstart="return false;">
                                    <div id="friendPublic-d94e8835-5379-4c55-bbc4-3c3028c433bc" class="swipeclass"></div>
                                </div>
                            </div>
                        </li>


                        <li>

                            <div class="event_section">
                                <section class="row-fluid clearfix">
                                    <figure class="pro-pics2"><img class="public-profile-img" src="https://d3sisat5gdssl6.cloudfront.net/622772ff-ecad-41de-b176-2271d8f81f21/928a1090-2e06-49a2-82bc-ba10e8f524c7/thumbnails/79x80/Delete_button.jpg?Expires=1460475588&amp;Signature=fn3Lc80thbjEAjokrX4ydxmTAtd3FCEWpygXhQsAnOkAZQW5lN13a4H4ha3yVIxjTnfc-d~SD0IilhkIt1ZC1iZGWpb3tinunhiG3b0UtXWU6F0Hhxvpxysa47pQNiYQVJRJQJf2WQ-EgmEK8MlES6yJasPP3mcp-koGkQ-wu8hZ7NRnazi8uy-7qP4xJJsrBXp1-ZwSxoTt1zYT1O2WWUgj12RY-ISEKqseSKlPOl~84ZRfpNSkNtx8DTPN2KECqLxx2~afpkhO65UK3V76zn33xhX1Flu4YPXOWUENVZiN7lCgxSkoouHalSkmY7NNG5VWO4hefHZlX1LL8hkV7Q__&amp;Key-Pair-Id=APKAISSKGZE3DR5HQCHA" alt=""></figure>
                                    <aside class="pro-names2" style="margin-top:0px;">@glenn : !test buys na</aside>
                                    <a href="javascript:;" title="Like media" class="memreas-detail-likecount" style="margin-left:10px;"><img src="/memreas/img/like.png" alt=""></a><span style="position: relative;top: -10px;left: -17px;color: #fff;">0</span><a href="javascript:;" title="Comment" style="position: relative;top:5px;"><img src="/memreas/img/comment.png" alt=""></a><span style="position: relative;top: -8px;left: -19px;color: #fff;">2</span>
                                    <div style="clear:both;"></div>
                                    <ul class="event-pics">
                                        <li class="image">
                                            <a href="javascript:;" onclick="popupBuyMedia();" style="cursor: pointer;">
                                                <div class="sell-event-overlay"></div>
                                                <span class="sell-event-buyme"><i>Buy</i></span><img src="https://d3sisat5gdssl6.cloudfront.net/622772ff-ecad-41de-b176-2271d8f81f21/bb0d0ffa-83b8-441f-abd7-dbb45b55954b/thumbnails/448x306/Screenshot_2016-03-05-13-03-49.png?Expires=1460475701&amp;Signature=AHcAAw9xtNlw3UJkT0WWuuynSBiPssfd2hyX7T91o2avixY5TVadaBB4ZKrDuTxuBxF1pPOkLakvUvxBLFYr-watGC2t~-89PEqJpYe1rxrr8bcxhjjaDcq1~TeH7iR~9FQ7TbWdJbruDBlKiGmZFV3UyVK0DF8edrw6-sP3JuB41yB3S6TE6lXB6sOBa4fDdQCs~0-gemHpFdVD4tllQUHb8zd2nDOprIo16bK4uFdBXzFi4I6lFBRWUQ70sWVkQFasITCs7noueG~CnkWFpMven8pgFbXM-ebc1NuDssV2VrYBEne3Vq1G0xwf8xM4kpHlNojIBdup18CJI9TZmQ__&amp;Key-Pair-Id=APKAISSKGZE3DR5HQCHA" style="">
                                            </a>
                                        </li>
                                    </ul>
                                    <div style="clear:both;"></div>
                                </section>
                                <div id="viewport" class="mouse_swip" onselectstart="return false;">
                                    <div id="friendPublic-622772ff-ecad-41de-b176-2271d8f81f21" class="swipeclass"></div>
                                </div>
                            </div>
                        </li>


                    </ul>





                </div>
                <div class="span3">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- memreas_skyscraper_ad -->
                    <ins class="adsbygoogle"
                         style="display:inline-block;width:300px;height:600px"
                         data-ad-client="ca-pub-2182144607113281"
                         data-ad-slot="7131339051"></ins>
                    <script>
                                                (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>

            </div>

            <!-- layuout-->


            <!-- layuout-->




            <div class="row-fluid">
                <div class="span12">

                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- memreas_auto_size_ad -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-2182144607113281"
                         data-ad-slot="4950165058"
                         data-ad-format="auto"></ins>
                    <script>
                                                (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>   



                </div>


            </div>

            

        </section>


        <!-- Modal JS -->

        <script src="/memreas/js/responsiveslides.min.js"></script>
        <script src="/memreas/js/jquery-ui.min.js"></script>
        <script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>


        <script>
                                                $(function () {
                                                    $(".rslides").responsiveSlides();

                                                    $('#SignupReg').click(function () {
                                                        $('#MobileHomeScreen').hide();
                                                        $('.mobileReform').show();

                                                    });
                                                });
        </script>



    </body>
</html>