<?php
use Application\Model\MemreasConstants;
header ( 'Cache-Control: no-cache, no-store, must-revalidate' ); // HTTP 1.1.
header ( 'Pragma: no-cache' ); // HTTP 1.0.
header ( 'Expires: 0' ); // Proxies.
header ( 'Access-Control-Allow-Origin: *' );
header ( "Access-Control-Allow-Methods: POST, GET" );
header ( "Access-Control-Allow-Headers: x-requested-with" );
?>
<!doctype html>
<html lang="en" class="no-js">
<head>

<meta name="description" content="<?php echo MemreasConstants::MEMREAS_DESCRIPTION ?>">
<meta name="keywords" content="<?php echo MemreasConstants::MEMREAS_KEYWORDS ?>">
<title>memreas - public <?php echo $this->type ?> page</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--meta responsive-->
<!-- Mark update -->
<link rel="stylesheet" type="text/css" href="/memreas/css/reset.css">
<link rel="stylesheet" type="text/css" href="/memreas/css/bootstrap.css">
<link rel="stylesheet" type="text/css"
	href="/memreas/css/responsiveslides.css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />

<link href="/memreas/css/style.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" type="text/css" href="/memreas/css/register.css">
<link rel="shortcut icon" href="/memreas/img/icon.png" />


<link rel="stylesheet" href="/memreas/cssblue/blueimp-gallery.css">
<link rel="stylesheet"
	href="/memreas/cssblue/blueimp-gallery-indicator.css">
<link rel="stylesheet" href="/memreas/cssblue/blueimp-gallery-video.css">

<!-- HTML5 shim for IE backwards compatibility -->
<!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
                <![endif]-->
<!-- End Mark update -->
<script src="/memreas/js/jquery-register.js"></script>
<style type="text/css">
.logibnt {
	margin-right: 10px;
	font-family: "Century Gothic";
	font-size: 16px;
	cursor: pointer;
	padding: 7px 25px;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #e2e3e7),
		color-stop(100%, #b5b9c0));
	border-radius: 7px;
	color: #3b3b3b;
	padding: 10px 20px;
	text-shadow: 0 1px 1px #fff;
}

.btnactioncont {
	width: auto !important;
	margin-right: 10px;
	margin-top: 16px;
}

.sell-event-buyme {
	position: relative;
	display: inline-block;
	cursor: pointer;
	float: left;
	/* margin-left: -104px; */
	width: 145px;
	height: 141px;
	background-color: rgba(249, 249, 249, 0.4);
	margin-left: -174px;
	top: 3px;;
	background-image: url("/memreas/img/blue-btn.png");
	background-repeat: no-repeat;
	background-position: top center
}

.navbar-fixed-top {
	position: relative;
}

.overlaypopUp {
	position: absolute;
	cursor: pointer;
	background: rgba(246, 246, 246, 0.5);
	height: 260px;
	z-index: 999;
	width: 72%;
}

.btnpublicbuynow {
	width: 100px;
	color: #fff;
	background-color: #2DA1EA;
	color: #fff;
	border-radius: 10px;
	padding: 12px;
	font-size: 28px;
	left: 30%;
	font-family: "Century Gothic";
	position: relative;
	top: 50%;
}
#content-1{
    height: 300px;
    width: auto;
    max-width: 50%;
    min-width: 600px;
    display: inline-block;
    vertical-align: bottom;
    
}
#content-1 img{width:90px; height: 90px; }
#content-1 li{display: block;}
.public-profile-img{width: 80px; height: 80px;}
 .event_section{border-bottom:none;}

 ::-webkit-scrollbar {
	width: 8px;
}
::-webkit-scrollbar-button {
	width: 8px;
	height:5px;
}
::-webkit-scrollbar-track {
	background:#eee;
	border: thin solid lightgray;
	box-shadow: 0px 0px 3px #dfdfdf inset;
	border-radius:10px;
}
::-webkit-scrollbar-thumb {
	background:#193D65;
	border: thin solid gray;
	border-radius:10px;
}
::-webkit-scrollbar-thumb:hover {
	background:#7d7d7d;
}			
</style>
<script>
var type = "<?php echo $this->type; ?>";
var tag = "<?php echo $this->tag; ?>";
var name = "<?php echo $this->name; ?>";
</script>
</head>

<body style="background: #193D65 !important;">
	<div id="loadingpopup">
		<div id="loadingpopupinner">
			<img id="loadingimg" src="/memreas/img/loading.gif"> <span
				id="loadingtext">loading...</span>
		</div>
	</div>

	<!-- <header class="rel" style="position: fixed; top: 0;">  -->
	<header class="navbar-fixed-top">
		<div class="pull-right btnactioncont">

			<a href="/index" class="logibnt"> Login</a> <a href="/index"
				class="logibnt"> Sign Up </a>
		</div>
		<div class="container">
			<div class="header-inner">

				<h1 id="logo" style="float: none;">
					<a href=""
						style="height: auto; background: url('/memreas/img/logo.png') no-repeat scroll 5px 3px rgba(0, 0, 0, 0)">memreas</a>
				</h1>
			</div>
		</div>
		<div style="clear: both;"></div>
		<div style="clear: both;"></div>
	</header>
	<div class="container-fluid body-content">
		<div class="row-fluid" style="margin-top: 20px; margin-bottom: 20px;">
			<div class="span12 text-center"
				style="margin-top: 20px; margin-bottom: 20px;">
				<script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<ins class="adsbygoogle" style="display: block"
					data-ad-client="ca-pub-2182144607113281" data-ad-slot="4950165058"
					data-ad-format="auto"></ins>
				<script>
                		(adsbygoogle = window.adsbygoogle || []).push({});
                </script>
			</div>
		</div>
		<div class="row-fluid" style="margin-bottom: 20px;">
			<div
				class="<?php echo ($this->enableAdvertising) ? 'span9' : 'span9';?>">
                           
                                       
                            
				<ul id="public_list" 
					class="publicpagelising scrollClass  publicMemreas scroll-area"
					style="height: 100%; overflow: auto;">
					<?php //js populates... ?>
				</ul>
			</div>
			<div class="span3">
				<script async
					src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
				<ins class="adsbygoogle" style="display: block"
					data-ad-client="ca-pub-2182144607113281" data-ad-slot="9363121856"
					data-ad-format="auto"></ins>
				<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
				</script>
			</div>
		</div>
		<!-- layout-->
		<!-- </section>-->
	</div>

	<!-- Memreas tab popup section -->
	<div id="popupReqisterToBuy" class="popups">
		<a id="popupReqisterToClose"
			onClick="disablePopup('popupReqisterToBuy');" class='popupClose'>x</a>
		<h2>Private Media - Register to purchase</h2>
		<p>&nbsp;</p>
		<ul id="content_1" class="give-message-form buying-media-detail">
			<li><label class="textfield_names" style="width: 150px;">you must
					register to purchase access</label>
				<div class="clear"></div></li>
		</ul>
		<div class="clear"></div>
		<a class="black_btn_skin f-right"
			href="javascript:disablePopup('popupReqisterToBuy');">close</a>
	</div>
	<!-- end popup section -->


	<footer>
		<div class="rel">
			<p>©2016 memreas llc</p>
		</div>

	</footer>

	<!-- Modal JS -->
<?php ?>
	<script src="/memreas/js/responsiveslides.min.js"></script>
	<script src="/bower_components/jquery-ui/jquery-ui.min.js"></script>
	<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script src="/memreas/js/jquery.oauthpopup.js"></script>
	<script src="/memreas/jsblue/blueimp-helper.js"></script>
	<script src="/memreas/jsblue/blueimp-gallery.js"></script>
	<script src="/memreas/jsblue/blueimp-gallery-fullscreen.js"></script>
	<script src="/memreas/jsblue/blueimp-gallery-indicator.js"></script>
	<script src="/memreas/jsblue/blueimp-gallery-video.js"></script>
	<script src="/memreas/jsblue/jquery.blueimp-gallery.js"></script>
	<script src="/memreas/js/ajax.js"></script>
	<script src="/memreas/js/global.js"></script>
	<script src="/memreas/js/popup.js"></script>
	<script src="/memreas/js/public_memreas_page.js"></script>
	<script>
$(function () {
	$(".rslides").responsiveSlides();
	$('#SignupReg').click(function () {
		$('#MobileHomeScreen').hide();
		$('.mobileReform').show();
	});
	$('.logibnt').click(function(){
		window.location='/index';  
	})
       
       
       				
        
});
        </script>



</body>
</html>