<?php
/////////////////////////////////
// Author: John Meah
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');
$user_id = $session->offsetGet('user_id');
echo "user_id ----> " . $user_id;
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";

?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>memreas</title>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

<!--jQuery Lybrary-->
<!--
<script src="/memreas/js/jquery.js"></script>
-->
<!-- JQuery -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>

<!--memreas paypal-->
<script src="/memreas/js/sampleAjax.js"></script>
<!-- Fetch the user_id -->
<script type="text/javascript">
var user_id = "<?php echo $user_id; ?>";

	//List Card(s)
    $(document).ready(function () {
        $("#btnSubmit").click(onSubmitCallClicked);
    });
    function onSubmitCallClicked() {
        jQuery.sampleAjax();
    }

</script>
</head>
<body>


<div id="tabs">
  <ul>
    <li><a href="#tabs-2">Fetch Web Service Results</a></li>
  </ul>

  <div id="tabs-2">
	<form id="xml_form" name=xml_form" action="/index/sampleAjax">
	<div id="xml_input">
	<table>
		<tr>
			<td>Web Service Action:
		</tr>
		<tr>
			<td><input id="ws_action" type="text" name="ws_action"/>
		</tr>
		<tr>
			<td>Input:
		</tr>
		<tr>
			<td><textarea id="xml_form_input" name="xml_form_input" rows="10" cols="120">Replace with input xml here...</textarea>
		</tr>
	</table>
  	</div>
	<div id="xml_output">
	<table>
		<tr>
			<td>Results:
		</tr>
		<tr>
			<td><textarea id="xml_form_output" name="xml_form_output" rows="10" cols="120">Result will be shown here.</textarea>
		</tr>
	</table>
  	</div>
	<table>
		<div id="card_list">
		</div>
		<tr>
			<td>
			<td><input id="btnSubmit" type="button" name="ok" value="submit">
		</tr>
	</table>

  </div>


</form>
</div>


</body>
</html>