<?php 
/////////////////////////////////
// Author: John Meah
// Copyright memreas llc 2013
/////////////////////////////////

use Guzzle\Http\Client;
use Zend\Session\Container;

$session = new Container('user');        
$user_id = $session->offsetGet('user_id');
$domain = "http://d1ckv7o9k6o3x9.cloudfront.net/";

?>

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/memreas/css/style.css" rel="stylesheet" type="text/memreas/css">
<link href="/memreas/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link rel="stylesheet" href="/memreas/css/swipebox.css">
<link href="/memreas/css/jquery.akordeon.css" rel="stylesheet" type="text/css" />

<!--Bootstrap Css-->
<link href="/memreas/css/bootstrap.min.css" rel="stylesheet" type="text/memreas/css">
<link href="/memreas/css/datepicker.css" rel="stylesheet" type="text/memreas/css">

<!--jQuery Lybrary-->
<!--script src="/memreas/js/jquery.js"></script-->
<script type='text/javascript' src='http://code.jquery.com/jquery-1.8.3.js'></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>

<!--Google Map-->
<script src="http://maps.google.com/maps/api/js?libraries=places&region=uk&language=en&sensor=true"></script>

<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>
<script src="/memreas/js/bootstrap-datepicker.js"></script>

<!--Social Library-->
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script src="/memreas/js/facebook.js"></script>
<script src="/memreas/js/twitter.js"></script>

<!--Backgound Strecher-->
<script type="text/javascript" src="/memreas/js/bgstretcher.js"></script>
<!-- akordeon -->
<script src="/memreas/js/jquery.akordeon.js" type="text/javascript"></script>
<!-- pop-up -->
<script src="/memreas/js/popup.js" type="text/javascript"></script>
<!-- custom scrollbars plugin -->
<script src="/memreas/js/jquery.mCustomScrollbar.concat.min.js"></script>
<!-- custom swipebox plugin -->    
<script src="/memreas/js/jquery.swipebox.min.js"></script>

<script src="/memreas/js/base_func.js"></script>
<script src="/memreas/js/ajax.js"></script>
<script src="/memreas/js/share.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
		$(document).bgStretcher({
			images: ['/memreas/img/bg.jpg'],
			imageWidth: 1366, imageHeight: 700
		});
		share_initObjects();
     	share_initAkordeon();
	});
	
	(function($){
		$(window).load(function(){
			share_customScrollbar();
		});
	})(jQuery);
	
	jQuery(function($) {
		$(".swipebox").swipebox();
	});
	
	$(function() {
		$("#dtp_date").datepicker();
		$("#dtp_from").datepicker();
		$("#dtp_to").datepicker();
		$("#dtp_selfdestruct").datepicker();
	});
</script>

<!-- variable to show the advertisement -->
<?php $show_ad = true; ?>

</head>

<div id="loadingpopup">
	<div id="loadingpopupinner">
		<img id="loadingimg" src="/memreas/img/loading.gif"/>
		<span id="loadingtext">Please wait...</span>
	</div>
</div>

<body>
	<input id="user_id" val="<?php echo $user_id ?>" hidden></input>

	<?php require 'header.phtml' ?>
		
	<!-- Begin : Container -->
	<div class="container">
	  <!-- Begin : Content -->
		<div class="row-fluid content">
		  <?php require 'nav.phtml' ?>
		  
		  <div class="span11 <?php if ($show_ad == false) echo("fixed") ?>">
		  <?php if ($show_ad == true) { ?>
		  <div class="span9">
		  <?php } ?>
			<div class="row-fluid">
				<ul id="tabs" class="medium_tabs">
					<li><a href="#" title="share_tab1">memreas details</a></li>
					<li><a href="#" title="share_tab2">media</a></li>
					<li><a href="#" title="share_tab3">friends</a></li>
				</ul>
				<div id="tab-content">
					<div id="share_tab1" class="hideCls">
						<div class="required">only name is required</div>
						<ul id="content_1" class="share_memreas_details scrollClass">
						<li>
						<label class="textfield_names">name :</label>
						<input name="input" type="text" id="txt_name" class="share-txtfield" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';"/>
						</li>
						<li>
						<label class="textfield_names">date :</label>
						<input name="input" type="text" id="dtp_date" class="share-txtfield date-picker" readonly value="from" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'from')this.value = '';"/>
						</li>
						<li>
						<label class="textfield_names">location :</label>
						<input name="input3" type="text" id="txt_location" class="share-txtfield" value="address or current location" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'address or current location')this.value = '';" onClick="share_showGoogleMap('div_locationmap_maparea');"/>
						</li>
						<li>
						 <input id="ckb_canpost" class="css-checkbox" type="checkbox" checked="checked"/>
						 <label for="ckb_canpost" name="demo_lbl_1" class="css-label margin-none" >friends can post pics/videos</label>
						</li>
						<li>
						 <input id="ckb_canadd" class="css-checkbox" type="checkbox" checked="checked"/>
						 <label for="ckb_canadd" name="demo_lbl_2" class="css-label margin-none" >friends can add Friends</label>
						</li>
						<li>
						 <input id="ckb_public" class="css-checkbox" type="checkbox" checked="checked"/>
						 <label for="ckb_public" name="demo_lbl_3" class="css-label margin-none" onClick="javascript:share_clickCkbPublic();" >public (anyone can add or post)</label>
						</li>
						<li>
						 <input id="ckb_viewable" class="css-checkbox" type="checkbox" checked="checked"/>
						 <label for="ckb_viewable" name="demo_lbl_4" class="css-label margin-none" >viewable :</label>
						 <input name="input" type="text" id="dtp_from" class="date-picker" readonly value="from" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'from')this.value = '';"/>
						 <input name="input" type="text" id="dtp_to" class="date-picker" readonly value="to" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'to')this.value = '';"/>
						</li>
						<li>
						 <input id="ckb_selfdestruct" class="css-checkbox" type="checkbox" checked="checked"/>
						 <label for="ckb_selfdestruct" name="demo_lbl_5" class="css-label margin-none" >self destruct :</label>
						 <input name="input" type="text" id="dtp_selfdestruct" class="share-txtfield-2 date-picker" readonly value="" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '')this.value = '';"/>       
						</li>
						</ul>
						<a class="black_btn_skin f-center" href="javascript:share_addEvent();">next</a> 
						<a class="black_btn_skin" href="javascript:share_clearMemreas();">cancel</a>
					</div>
					<div id="share_tab2" class="hideCls">
						<ul id="content_1" class="share scrollClass">
							<li><a href="/memreas/img/large-pic-1.jpg" class="swipebox" title="photo-1"><img src="/memreas/img/small-pic-1.jpg" alt=""></a></li>
						</ul>
						<div class="comment">
							<ul>
								<li>
									<div class="comment-txt <?php if ($show_ad == false) echo("clearfix") ?>">add a comment</div>
								</li>
								<li>
									<input name="input2" type="text" id="txt_comment" class="comment_txtfield" value="your comments here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'your comments here')this.value = '';"/>
								</li>
							</ul>    
						</div>
						<a class="black_btn_skin f-center" href="javascript:share_addComment();">next</a> 
						<a class="black_btn_skin f-middle" href="javascript:share_clearMedia();">cancel</a>
					</div>
					<div id="share_tab3" class="hideCls">
						<div class="styled-select">
							<select id="cmb_socialtype">
								<option value="facebook">facebook</option>
								<option value="twitter">twitter</option>
							</select>
						</div>
						<ul id="share_friendslist" class="share_friends_contents scrollClass">
							<!--
							<li>
							  <figure class="pro-pics2"><img src="/memreas/img/profile-pic.jpg" alt=""></figure>
							  <aside class="pro-pic_names2">Friend Name</aside>
							</li>
							-->
						</ul>
						<div class="akordeon" id="buttons">
							<div class="akordeon-item expanded">
								<div class="akordeon-item-head">
									<div class="akordeon-item-head-container">
										<div class="akordeon-heading">
											email address list
										</div>
									</div>
								</div>
								<div class="akordeon-item-body">
									<div class="akordeon-item-content" style="padding:0px 10px;">
									  <input id="txt_emaillist" name="input" type="text" class="more-input" value="add your email list here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'add your email list here')this.value = '';"/>
									</div>
								</div>
							</div>
						</div>
						<ul class="share_friends_check_box">
							<li>
								<input id="ckb_makegroup" class="css-checkbox" type="checkbox" checked="checked" />
								<label for="ckb_makegroup" name="demo_lbl_6" class="css-label">make this a group</label>
								<input id="txt_groupname" name="input" type="text" class="share-txtfield-3" value="group name here" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'group name here')this.value = '';"/>
							</li>
						</ul>
						<a class="black_btn_skin f-center" href="javascript:share_makeGroup();">ok</a>
						<a class="black_btn_skin f-middle" href="javascript:share_clearFriends();">cancel</a> 
					</div>
				</div>
			</div>
		  <?php if ($show_ad == true) { ?>
		  </div>
		  <div class="span3">
			<section id="ad">
			  <div class="adbox">Your <br>Advertisement <br>space </div>
			  <div class="adbox">Your <br>Advertisement <br>space </div>
			  <div class="adbox-port">Your <br>Advertisement <br>space </div>
			  <div class="adbox-port">Your <br>Advertisement <br>space </div>
			</section>
		  </div>
		  <div class="row-fluid"><div class="ad"><img src="/memreas/img/ad.jpg" alt=""></div></div>
		  </div>
		  <?php } ?>
		  
		<div id="dlg_locationmap" class="popups2">
		  	<a id="btn_locationmap_close" onClick="javascript:share_closeGoogleMap(false);" class='popupClose'>x</a>
			<h2>location</h2>
			<a id="btn_locationmap_ok" class="black_btn_skin" href="javascript:share_closeGoogleMap(true);">OK</a>
			<input id="txt_locationmap_address" name="input" type="text" />
			<div class="clear"></div>
			<div id="div_locationmap_maparea" class="map_box"></div>
		</div>
		<div id="div_locationmap_back" class="backgroundPopup"></div> 
		</div>
	  <!-- End : Content -->
	</div>
	<!-- End : Container -->
	
	<?php require 'footer.phtml' ?>

</body>
</html>
