<?php 

require 'twitteroauth.phtml';

define('TWITTER_CONSUMER_KEY',      'qIPCqlYRHip1chaY1tt0w');
define('TWITTER_CONSUMER_SECRET',   'ofDFMhBUS12Di6HlB0Cb7rkiKc7X4zpv85m3tXaZ1wY');
define('TWITTER_REQUEST_URL',       'https://api.twitter.com/oauth/request_token');
define('TWITTER_ACCESS_URL',        'https://api.twitter.com/oauth/access_token');
define('TWITTER_AUTHORIZE_URL',     'https://api.twitter.com/oauth/authorize');

session_start();

// The TwitterOAuth instance  
$twitteroauth = new TwitterOAuth('qIPCqlYRHip1chaY1tt0w', 'ofDFMhBUS12Di6HlB0Cb7rkiKc7X4zpv85m3tXaZ1wY');  
// Requesting authentication tokens, the parameter is the URL we will be redirected to  
$request_token = $twitteroauth->getRequestToken('http://localhost.com/twitter_oauth.php');  
  
// Saving them into the session  
$_SESSION['oauth_token'] = $request_token['oauth_token'];  
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];  
  
// If everything goes well..  
if($twitteroauth->http_code==200){  
    // Let's generate the URL and redirect  
    $url = $twitteroauth->getAuthorizeURL($request_token['oauth_token']); 
    header('Location: '. $url); 
} else { 
    // It's a bad idea to kill the script, but we've got to know when there's an error.  
    die('Something wrong happened.');  
}  
 
?>

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>
</head>

<body>
</body>
</html>